### ISSUE TITLE
RKE2 v1.28.10+rke2r1 cluster fails when one of the server nodes goes down

### ISSUE THREAD

**Issue by serhiynovos** [rancher/rke2#6265] opened 2024-06-27 07:54 UTC
I have running RKE2 cluster provisioned by Rancher. Recently I updated it to 1.28.10+rke2r1 over rancher and noticed that now when I stop one server node, some part of worker nodes will stop working. In logs I see it tries to connect only to this server node and as I remember they should automatically reconnect to any other two working server nodes.

**Comment by serhiynovos** [comment] 2024-06-27 07:58
Looks like it's also related to https://github.com/rancher/rke2/issues/6249

**Comment by serhiynovos** [comment] 2024-06-27 09:30
Also when 1st server node is stopped agents are also stopped and cluster is unreachable from Rancher UI

**Comment by brandond** [comment] 2024-06-27 18:30
Duplicate of https://github.com/rancher/rke2/issues/5949

Please test with v1.28.11 when available.

**Closed by brandond** 2024-06-27 18:30 UTC
