### ISSUE TITLE
Rancher Rollback Support

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#565] opened 2020-12-05 02:40 UTC
We'd like to support the rollback feature in Rancher. There are are some pitfalls that need consideration as per our design calls.
This issue will need updating as we discuss further. For now this is a placeholder to track this effort.

**Comment by davidnuzik** [comment] 2021-05-04 19:57
@briandowns similar to the main etcd snapshot issue, this issue doesn't need to involve the full Rancher and UI integration now. As such can we move this "To Test" now? If you are comfortable with that could you change the state to test?

**Comment by davidnuzik** [comment] 2021-06-29 15:39
@bmdepesa needs QA testing. Ensure Rancher etcd rollback works as epected.

**Comment by bmdepesa** [comment] 2021-06-29 18:06
Duplicate of https://github.com/rancher/rancher/issues/32392

**Closed by bmdepesa** 2021-06-29 18:06 UTC
Labels: by-2.6-ga
