### ISSUE TITLE
RKE2 with SLES15SP2 - cannot download images from nexus based repo with authentification

### ISSUE THREAD

**Issue by peter-englmaier** [rancher/rke2#676] opened 2021-01-27 15:49 UTC
I am trying to get RKE2 v1.19.7+rke2r1 to work with SLES15SP2. I am trying to download images from a repository with authorization, which works with another SLES15SP2 host with docker, but with kubectl on the rke2 cluster, I get the following error:
```
"Failed to pull image "private.repo.ch:443/software/node:1.0": rpc error: code = NotFound desc = failed to pull and unpack image "private.repo.ch:443/software/node:1.0": failed to resolve reference "private.repo.ch:443/software/node:1.0":  private.repo.ch:443/software/node:1.0: not found
```
When I try to download the image using crictl pull --creds user:password private.repo.ch:443/software/node:1.0
I am getting the same error regardless of which creds I give, even without creds. It looks like it does not send the credentials. 

I can, however, side load the images using "ctn image import" and then it can be used in the cluster.

SLES15SP2 is not yet listed as validated, but it should work on any linux.

Related to #592 and maybe #647 (I did not specify a different default repository).

Best, Peter

**Comment by peter-englmaier** [comment] 2021-02-26 11:24
Tested with RKE2 v1.19.8+rke2r1 again. Does not work. 

```
ctr --debug image pull --user user:password private.repo.ch:443/software/node:1.0
DEBU[0000] fetching                                      image=" private.repo.ch:443/software/node:1.0"
DEBU[0000] resolving                                     host="private.repo.ch:443"
DEBU[0000] do request                                    host="private.repo.ch:443" request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=containerd/v1.4.3-k3s3 request.method=HEAD url="https://private.repo.ch:443/v2/software/node/manifests/1.0"
DEBU[0000] fetch response received                       host="private.repo.ch:443" response.header.cache-control="must-revalidate,no-cache,no-store" response.header.connection=keep-alive response.header.content-length=485 response.header.content-type="text/html;charset=iso-8859-1" response.header.date="Fri, 26 Feb 2021 11:08:41 GMT" response.header.keep-alive="timeout=5" response.header.server=nginx response.header.strict-transport-security="max-age=7776000" response.status="404 Not Found" url="https://private.repo.ch:443/v2/software/node/manifests/1.0"
ctr: failed to resolve reference "private.repo.ch:443/software/node:1.0": private.repo.ch:443/software/node:1.0: not found

```
The version of containerd is unchanged v1.4.3-k3s3

**Comment by brandond** [comment] 2021-02-26 20:04
`DEBU[0000] fetch response received                       host="private.repo.ch:443" response.header.cache-control="must-revalidate,no-cache,no-store" response.header.connection=keep-alive response.header.content-length=485 response.header.content-type="text/html;charset=iso-8859-1" response.header.date="Fri, 26 Feb 2021 11:08:41 GMT" response.header.keep-alive="timeout=5" response.header.server=nginx response.header.strict-transport-security="max-age=7776000" response.status="404 Not Found" url="https://private.repo.ch:443/v2/software/node/manifests/1.0"`

That looks like a NOT FOUND response, not UNAUTHORIZED. Are you sure that's the right image?

**Comment by brandond** [comment] 2021-02-26 20:18
Just to show that it works, here's a pull from my private registry mirror using TLS + authentication:

```
[root@centos01 ~]# ctr --debug --address=/run/k3s/containerd/containerd.sock --namespace=k8s.io image pull --skip-verify --user user:pass docker-io.registry.k3s.khaus/library/busybox:latest
DEBU[0000] fetching                                      image="docker-io.registry.k3s.khaus/library/busybox:latest"
DEBU[0000] resolving                                     host=docker-io.registry.k3s.khaus
DEBU[0000] do request                                    host=docker-io.registry.k3s.khaus request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=containerd/1.4.3 request.method=HEAD url="https://docker-io.registry.k3s.khaus/v2/library/busybox/manifests/latest"
DEBU[0000] fetch response received                       host=docker-io.registry.k3s.khaus response.header.content-length=158 response.header.content-type="application/json; charset=utf-8" response.header.date="Fri, 26 Feb 2021 20:17:05 GMT" response.header.docker-distribution-api-version=registry/2.0 response.header.www-authenticate="Basic realm=\"docker.io registry mirror\"" response.header.x-content-type-options=nosniff response.status="401 Unauthorized" url="https://docker-io.registry.k3s.khaus/v2/library/busybox/manifests/latest"
DEBU[0000] Unauthorized                                  header="Basic realm=\"docker.io registry mirror\"" host=docker-io.registry.k3s.khaus
DEBU[0000] do request                                    host=docker-io.registry.k3s.khaus request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=containerd/1.4.3 request.method=HEAD url="https://docker-io.registry.k3s.khaus/v2/library/busybox/manifests/latest"
DEBU[0001] fetch response received                       host=docker-io.registry.k3s.khaus response.header.content-length=2080 response.header.content-type=application/vnd.docker.distribution.manifest.list.v2+json response.header.date="Fri, 26 Feb 2021 20:17:06 GMT" response.header.docker-content-digest="sha256:c6b45a95f932202dbb27c31333c4789f45184a744060f6e569cc9d2bf1b9ad6f" response.header.docker-distribution-api-version=registry/2.0 response.header.etag="\"sha256:c6b45a95f932202dbb27c31333c4789f45184a744060f6e569cc9d2bf1b9ad6f\"" response.header.x-content-type-options=nosniff response.status="200 OK" url="https://docker-io.registry.k3s.khaus/v2/library/busybox/manifests/latest"
```

**Comment by peter-englmaier** [comment] 2021-02-27 13:32
Hi @brandond 
The output was edited for privacy. It is the right image. Yes, "Not found" sounds like it is not there  - can it be, that the presence of the image is checked (without creds) before the actuall download is attempted (with creds)? I think the private repo does not allow that.

I am now on vacation for a week and cannot check, but I will see if your output helps me to trouble-shoot. Many thanks!

**Comment by brandond** [comment] 2021-02-28 02:50
If your registry sends a 404 instead of 401 when credentials are required, that is incorrect behavior on the part of your registry.

**Comment by rancher-max** [comment] 2021-03-04 22:11
I also cannot repro this on SLES15SP2 using an AMI from AWS. My output was similar to what @brandond mentioned in https://github.com/rancher/rke2/issues/676#issuecomment-786872574. 

That being said, v1.20.4 has improved private registry support. The easiest way to do this is to setup a mirror at `/etc/rancher/rke2/registries.yaml` such as:
```yaml
---
mirrors:
  docker.io:
    endpoint:
      - "myregistry.fake.com"
  k8s.gcr.io:
    endpoint:
      - "myregistry.fake.com"
configs:
  "myregistry.fake.com":
    auth:
      username: fakeuser
      password: fakepass
    tls:
      cert_file: /home/ec2-user/cert.pem
      key_file:  /home/ec2-user/key.pem
      ca_file: /home/ec2-user/ca.pem
```
And your cluster will use the authentication from this to pull images. Ensure this is setup on each node.

I'm going to close this out, but if you're still seeing these issues on v1.20.4 please feel free to reopen with a few more details that can help us track down the root cause and why we may be getting different results.

**Closed by rancher-max** 2021-03-04 22:11 UTC

**Comment by brandond** [comment] 2021-03-09 21:11
Did you expect your repo to act as a transparent mirror for docker.io? If so you need to configure that:

```yaml
mirrors:
  private.repo.ch:
    endpoint:
      - "https://private.repo.ch:443"
  docker.io:
    endpoint:
      - "https://private.repo.ch:443"
configs:
  "private.repo.ch:443":
    auth:
      username: user
      password: secret
    tls:
      ca_file: /etc/rancher/rke2/fullcertchain.pem
```

**Comment by peter-englmaier** [comment] 2021-03-11 07:59
Hi @brandond 
No, this repository is not a transparent mirror. But it is nice to know how easy it would be to use it this way.
I fixed the problem now: our repository (nexus) sits behind a nginx proxy. The configuration setup by some colleague surprisingly routed to the backend nexus server based on agent header. With containerd the agent string is different of course, so the proxy routing had to be adapted.
So, yes, RKE2v1.19.8 works with SLES15SP2. Looking forward for rke2 to replace rke1 in rancher ;-)
Thanks again,
Peter

**Comment by jackelynoliveira** [comment] 2021-12-22 15:14
> Tested with RKE2 v1.19.8+rke2r1 again. Does not work.
> 
> ```
> ctr --debug image pull --user user:password private.repo.ch:443/software/node:1.0
> DEBU[0000] fetching                                      image=" private.repo.ch:443/software/node:1.0"
> DEBU[0000] resolving                                     host="private.repo.ch:443"
> DEBU[0000] do request                                    host="private.repo.ch:443" request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=containerd/v1.4.3-k3s3 request.method=HEAD url="https://private.repo.ch:443/v2/software/node/manifests/1.0"
> DEBU[0000] fetch response received                       host="private.repo.ch:443" response.header.cache-control="must-revalidate,no-cache,no-store" response.header.connection=keep-alive response.header.content-length=485 response.header.content-type="text/html;charset=iso-8859-1" response.header.date="Fri, 26 Feb 2021 11:08:41 GMT" response.header.keep-alive="timeout=5" response.header.server=nginx response.header.strict-transport-security="max-age=7776000" response.status="404 Not Found" url="https://private.repo.ch:443/v2/software/node/manifests/1.0"
> ctr: failed to resolve reference "private.repo.ch:443/software/node:1.0": private.repo.ch:443/software/node:1.0: not found
> ```
> 
> The version of containerd is unchanged v1.4.3-k3s3

This issue, along with this [gist](https://gist.github.com/superseb/3b78f47989e0dbc1295486c186e944bf), were very useful for me to understand a problem I was having to pull images from a Nexus private registry for an Rancher provisioned RKE2 cluster.

After connecting to one of the cluster's machines, I ran this command so I could reproduce the error I was having:
`/var/lib/rancher/rke2/bin/ctr --address=/run/k3s/containerd/containerd.sock --debug image pull --user <username>:<password> <registry>/<image>:<tag>`
