### ISSUE TITLE
RKE2 ingress-nginx, metrics-server and coredns pods stuck in ContainerCreating status

### ISSUE THREAD

**Issue by uchalasani** [rancher/rke2#3218] opened 2022-08-05 18:10 UTC
**Environmental Info:**
RKE2 Version: v1.24.3+rke2r1
rke2 version v1.24.3+rke2r1 (bd4f6718b91f553a6abb639ba9cef6288d2b3508)
go version go1.18.1b7

Node(s) CPU architecture, OS, and Version: 

Linux rancherb01.<domain-name> 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

3 servers and 10 agents (But I did not re-install agents after removing)

**Describe the bug:**

After Installation on 3 servers, 4 pods (ingress-nginx, metrics-server, coredns and coredns-autoscaler) stuck in ContainerCreating status

**Steps To Reproduce:**

- Server-1: create file /etc/rancher/rke2/config.yaml with the following contents:
```
node-label:
  - "nodeload=control"
debug: false
write-kubeconfig-mode: "0644"
cluster-cidr: "10.42.0.0/16"
service-cidr: "10.43.0.0/16"
token: <Custom Name>-dev-rke2-2022-08-02
tls-san:
  - rancher.<Domain Nmae>
  - 127.0.0.1
  - kibana-dev.<Domain Nmae>
  - ...
node-taint:
  - "CriticalAddonsOnly=true:NoExecute"
```

- Installed RKE2: 
```
        sudo INSTALL_RKE2_ARTIFACT_PATH=/var/lib/rancher/rke2/agent/images \
             INSTALL_RKE2_TYPE=agent \
             INSTALL_RKE2_CHANNEL=stable \
             INSTALL_RKE2_METHOD=tar \
             /home/uchalasani/rpms/rke2/install.sh

```
- Enabled and started : rke2-agent.service
- Server-2 and Server-3: create file /etc/rancher/rke2/config.yaml with the following contents:
```
token: <Custom Name>-dev-rke2-2022-08-02
tls-san:
  - rancher.<Domain Nmae>
  - 127.0.0.1
  - kibana-dev.<Domain Nmae>
  - ...
node-label:
  - "nodeload=medium"
```

- Installed RKE2 on both Server-2 and Server-3: 
```
        sudo INSTALL_RKE2_ARTIFACT_PATH=/var/lib/rancher/rke2/agent/images \
             INSTALL_RKE2_TYPE=agent \
             INSTALL_RKE2_CHANNEL=stable \
             INSTALL_RKE2_METHOD=tar \
             /home/uchalasani/rpms/rke2/install.sh

```
- Enabled and started on both Server-2 and Server-3: rke2-agent.service

**Expected behavior:**

All the pods are up and running.

**Actual behavior:**

After Installation on 3 servers, 4 pods (ingress-nginx, metrics-server, coredns and coredns-autoscaler) stuck in ContainerCreating status

**Additional context / logs:**

Nodes status.
```
NAME                                STATUS   ROLES                       AGE   VERSION          INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME
rancherb01.<domain>   Ready    control-plane,etcd,master   16h   v1.24.3+rke2r1   10...1   <none>        CentOS Linux 7 (Core)   3.10.0-1160.36.2.el7.x86_64   containerd://1.6.6-k3s1
rancherb02.<domain>   Ready    control-plane,etcd,master   16h   v1.24.3+rke2r1   10...2   <none>        CentOS Linux 7 (Core)   3.10.0-1160.36.2.el7.x86_64   containerd://1.6.6-k3s1
rancherb03.<domain>   Ready    control-plane,etcd,master   16h   v1.24.3+rke2r1   10...3   <none>        CentOS Linux 7 (Core)   3.10.0-1160.36.2.el7.x86_64   containerd://1.6.6-k3s1
```
Pods status:
```
k get pods -n kube-system
NAME                                                         READY   STATUS              RESTARTS   AGE
cloud-controller-manager-rancherb01.<domain>   1/1     Running             0          16h
cloud-controller-manager-rancherb02.<domain>   1/1     Running             0          16h
cloud-controller-manager-rancherb03.<domain>   1/1     Running             0          16h
etcd-rancherb01.<domain>                       1/1     Running             0          16h
etcd-rancherb02.<domain>                       1/1     Running             0          16h
etcd-rancherb03.<domain>                       1/1     Running             0          16h
helm-install-rke2-canal-nd2x4                                0/1     Completed           0          16h
helm-install-rke2-coredns-4hlxd                              0/1     Completed           0          16h
helm-install-rke2-ingress-nginx-xdr7x                        0/1     ContainerCreating   0          16h
helm-install-rke2-metrics-server-gk54z                       0/1     ContainerCreating   0          16h
kube-apiserver-rancherb01.<domain>             1/1     Running             0          16h
kube-apiserver-rancherb02.<domain>             1/1     Running             0          16h
kube-apiserver-rancherb03.<domain>             1/1     Running             0          16h
kube-controller-manager-rancherb01.<domain>    1/1     Running             0          16h
kube-controller-manager-rancherb02.<domain>    1/1     Running             0          16h
kube-controller-manager-rancherb03.<domain>    1/1     Running             0          16h
kube-proxy-rancherb01.<domain>                 1/1     Running             0          16h
kube-proxy-rancherb02.<domain>                 1/1     Running             0          16h
kube-proxy-rancherb03.<domain>                 1/1     Running             0          16h
kube-scheduler-rancherb01.<domain>             1/1     Running             0          16h
kube-scheduler-rancherb02.<domain>             1/1     Running             0          16h
kube-scheduler-rancherb03.<domain>             1/1     Running             0          16h
rke2-canal-8fmpg                                             2/2     Running             0          16h
rke2-canal-j2kmn                                             2/2     Running             0          16h
rke2-canal-mnx9c                                             2/2     Running             0          16h
rke2-coredns-rke2-coredns-76cb76d66-kzg4k                    0/1     ContainerCreating   0          16h
rke2-coredns-rke2-coredns-autoscaler-58867f8fc5-sxt84        0/1     ContainerCreating   0          16h
```
Pod describe:
```
k -n kube-system describe pod/rke2-coredns-rke2-coredns-autoscaler-58867f8fc5-sxt84
Name:                 rke2-coredns-rke2-coredns-autoscaler-58867f8fc5-sxt84
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 rancherb02.<Doman Name>/10...2
Start Time:           Thu, 04 Aug 2022 21:49:13 -0400
Labels:               app.kubernetes.io/instance=rke2-coredns
                      app.kubernetes.io/name=rke2-coredns-autoscaler
                      k8s-app=kube-dns-autoscaler
                      pod-template-hash=58867f8fc5
Annotations:          checksum/configmap: a6f45b1282e0ee665683bf2c860c8bdcb7a57e2596d10aee0f1131e3871da804
                      cni.projectcalico.org/containerID: e72016d8293f99583333fb8b0cc8d52a09f4bc4708572ba294b06b7b24c0cf20
                      cni.projectcalico.org/podIP: 10.42.2.15/32
                      cni.projectcalico.org/podIPs: 10.42.2.15/32
                      kubernetes.io/psp: global-unrestricted-psp
                      scheduler.alpha.kubernetes.io/critical-pod:
                      scheduler.alpha.kubernetes.io/tolerations: [{"key":"CriticalAddonsOnly", "operator":"Exists"}]
Status:               Pending
IP:
IPs:                  <none>
Controlled By:        ReplicaSet/rke2-coredns-rke2-coredns-autoscaler-58867f8fc5
Containers:
  autoscaler:
    Container ID:
    Image:         rancher/hardened-cluster-autoscaler:v1.8.5-build20211119
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      /cluster-proportional-autoscaler
      --namespace=kube-system
      --configmap=rke2-coredns-rke2-coredns-autoscaler
      --target=Deployment/rke2-coredns-rke2-coredns
      --logtostderr=true
      --v=2
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  64Mi
    Requests:
      cpu:        25m
      memory:     16Mi
    Liveness:     http-get http://:8080/healthz delay=10s timeout=10s period=30s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-brd8q (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-brd8q:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 node-role.kubernetes.io/control-plane:NoSchedule op=Exists
                             node-role.kubernetes.io/etcd:NoExecute op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                    From     Message
  ----     ------                  ----                   ----     -------
  Warning  FailedCreatePodSandBox  68s (x56019 over 15h)  kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: open /proc/sys/net/ipv4/ip_unprivileged_port_start: no such file or directory: unknown
```

Common message in all 4 failed pods describe is : 
```
runc create failed: unable to start container process: error during container init: open /proc/sys/net/ipv4/ip_unprivileged_port_start: no such file or directory: unknown
```

**Comment by brandond** [comment] 2022-08-05 18:20
Duplicate of 
* https://github.com/k3s-io/k3s/issues/5912

This will be fixed in the next release. In the mean time you can do one of:
* downgrade to the previous release
* apply the workaround listed in that issue
* upgrade your kernel to a newer version (from EPEL or the like)

**Comment by uchalasani** [comment] 2022-08-05 18:23
Thanks @brandond for your prompt help. I appreciate it.

**Comment by uchalasani** [comment] 2022-08-05 18:24
You can close it.

**Comment by brandond** [comment] 2022-08-05 18:24
Will leave this open for QA to validate.

**Comment by uchalasani** [comment] 2022-08-05 18:35
> Will leave this open for QA to validate.

I applied both workarounds suggested. But no luck.
I would like to downgrade. Which version should I downgrade to?

**Comment by brandond** [comment] 2022-08-05 18:37
Which workarounds did you do? Can you show your `config.toml.tmpl` and `kubectl get node` after applying the workarounds? Note you only need to do one of those; if you upgrade to a kernel that supports those sysctls (4.11.0 or newer) you don't need to do anything else.

**Comment by uchalasani** [comment] 2022-08-05 18:42
Ok. I did not do the Kernel updates yet. I certainly can do that. I first applied YAML with dnsPolicy: ClusterFirst. I did not see any changes in the pods status. So I applied YAML with hostNetwork: true. 
```
NAME                                STATUS   ROLES                       AGE   VERSION          INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME
rancherb01.<Domain>   Ready    control-plane,etcd,master   17h   v1.24.3+rke2r1   10.194.231.71   <none>        CentOS Linux 7 (Core)   3.10.0-1160.36.2.el7.x86_64   containerd://1.6.6-k3s1
rancherb02.<Domain>   Ready    control-plane,etcd,master   16h   v1.24.3+rke2r1   10.194.231.72   <none>        CentOS Linux 7 (Core)   3.10.0-1160.36.2.el7.x86_64   containerd://1.6.6-k3s1
rancherb03.<Domain>   Ready    control-plane,etcd,master   16h   v1.24.3+rke2r1   10.194.231.73   <none>        CentOS Linux 7 (Core)   3.10.0-1160.36.2.el7.x86_64   containerd://1.6.6-k3s1
```
I am not sure where can I find config.toml.tmpl file?

**Comment by brandond** [comment] 2022-08-05 18:47
Where did you find anything about changing the DNS policy? I was referring to the workaround listed in https://github.com/k3s-io/k3s/issues/5912:
> k3s turned on unprivileged ports and ICMP by default in this PR: https://github.com/k3s-io/k3s/pull/5538 . It seems that containerd has some problems on this kernel version (maybe unprivileged ports are not supported on it) and [these two unprivileged flags are disabled in containerd by default](https://github.com/containerd/containerd/blob/main/docs/cri/config.md). After adding a config template to `/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl` and turning off these two flags, pods were created successfully.

**Comment by uchalasani** [comment] 2022-08-05 18:51
> Where did you see anything about changing the DNS policy? I was referring to the workaround listed in [k3s-io/k3s#5912](https://github.com/k3s-io/k3s/issues/5912):
> 
> > k3s turned on unprivileged ports and ICMP by default in this PR: [k3s-io/k3s#5538](https://github.com/k3s-io/k3s/pull/5538) . It seems that containerd has some problems on this kernel version (maybe unprivileged ports are not supported on it) and [these two unprivileged flags are disabled in containerd by default](https://github.com/containerd/containerd/blob/main/docs/cri/config.md). After adding a config template to `/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl` and turning off these two flags, pods were created successfully.
> 
> tl;dr change the two unprivileged flags to false.

I did find workaround YAML's in issue: https://github.com/rancher/rke2/issues/3195
Ok, Thanks. I will test out these workarounds. 
I appreciate your prompt help.

**Comment by uchalasani** [comment] 2022-08-05 18:54
Unfortunately our YUM Repo/mirrors does not have any newer kernels than 3.10.0. So that is not an option for now.

**Comment by brandond** [comment] 2022-08-05 19:02
That is is unrelated to the issue we're discussing here, but may also be affecting you. Lets not muddy the waters by mixing the discussion of both together.

There are newer kernels for EL7 available in EPEL and other community repos, but I understand your reluctance to use them. Either of the other work-arounds should be easier than updating the kernel.

**Comment by uchalasani** [comment] 2022-08-05 21:03
@brandond How do I make `/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl` file changes permanently. Looks like the changes got reverted after a reboot.
After changing the file, I did not see any changes in the pods. So I deleted them. The issue is still same even after this pod's deletion. So I rebooted the VM's. Then my changes are reverted back.

**Comment by brandond** [comment] 2022-08-05 21:16
https://rancher.com/docs/k3s/latest/en/advanced/#configuring-containerd has the most up to date docs. Substitute rke2 for any occurrences of k3s in the paths.

**Comment by uchalasani** [comment] 2022-08-06 01:50
@brandond Great news! I followed the above 2nd URL with most up to date docs. Now all the services for the servers are running fine. I cannot thank you enough for the timely help!

**Comment by rancher-max** [comment] 2022-08-11 22:20
### Validated on `master` branch commit `aebe4bb2e0bab9779bfe207d7d24e22b2a52a190`
  
## Environment Details

  
*Infrastructure*
- [x] Cloud (AWS - community ami CentOS 7.9.2009 `ami-00f8e2c955f7ffa9b`)
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
$ uname -a && cat /etc/os-release
Linux ip-172-31-33-210.us-east-2.compute.internal 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
  
*Cluster Configuration:*

1 server
  
*Config.yaml:*

N/A
  
*Additional files*

N/A
  
## Testing Steps

1. Install rke2
  
**Replication Results:**
- rke2 version used for replication: v1.24.3+rke2r1: `curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION=v1.24.3+rke2r1 INSTALL_RKE2_CHANNEL=latest sh -`
 

```
$ kubectl get nodes,pods -A -o wide
NAME                                               STATUS   ROLES                       AGE     VERSION          INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION           CONTAINER-RUNTIME
node/ip-172-31-33-210.us-east-2.compute.internal   Ready    control-plane,etcd,master   3m49s   v1.24.3+rke2r1   172.31.33.210   <none>        CentOS Linux 7 (Core)   3.10.0-1160.el7.x86_64   containerd://1.6.6-k3s1

NAMESPACE     NAME                                                                       READY   STATUS              RESTARTS   AGE     IP              NODE                                          NOMINATED NODE   READINESS GATES
kube-system   pod/cloud-controller-manager-ip-172-31-33-210.us-east-2.compute.internal   1/1     Running             0          3m44s   172.31.33.210   ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/etcd-ip-172-31-33-210.us-east-2.compute.internal                       1/1     Running             0          3m27s   172.31.33.210   ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/helm-install-rke2-canal-kphl8                                          0/1     Completed           0          3m30s   172.31.33.210   ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/helm-install-rke2-coredns-lqmsb                                        0/1     Completed           0          3m30s   172.31.33.210   ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/helm-install-rke2-ingress-nginx-wzzgj                                  0/1     ContainerCreating   0          3m30s   <none>          ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/helm-install-rke2-metrics-server-nlff2                                 0/1     ContainerCreating   0          3m30s   <none>          ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/kube-apiserver-ip-172-31-33-210.us-east-2.compute.internal             1/1     Running             0          3m15s   172.31.33.210   ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/kube-controller-manager-ip-172-31-33-210.us-east-2.compute.internal    1/1     Running             0          3m46s   172.31.33.210   ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/kube-proxy-ip-172-31-33-210.us-east-2.compute.internal                 1/1     Running             0          3m44s   172.31.33.210   ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/kube-scheduler-ip-172-31-33-210.us-east-2.compute.internal             1/1     Running             0          3m46s   172.31.33.210   ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/rke2-canal-c77wl                                                       2/2     Running             0          3m22s   172.31.33.210   ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/rke2-coredns-rke2-coredns-76cb76d66-x82xh                              0/1     ContainerCreating   0          3m23s   <none>          ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/rke2-coredns-rke2-coredns-autoscaler-58867f8fc5-xwmhh                  0/1     ContainerCreating   0          3m23s   <none>          ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
```
 
**Validation Results:**
- rke2 version used for validation: `curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_COMMIT=aebe4bb2e0bab9779bfe207d7d24e22b2a52a190 INSTALL_RKE2_CHANNEL=latest INSTALL_RKE2_METHOD=rpm sh -`

```
rke2 version v1.24.3-dev+aebe4bb2 (aebe4bb2e0bab9779bfe207d7d24e22b2a52a190)
go version go1.18.1b7
```
 

- All containers running/completed and node is ready
```
$ kubectl get nodes,pods -A -o wide
NAME                                               STATUS   ROLES                       AGE     VERSION          INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION           CONTAINER-RUNTIME
node/ip-172-31-33-210.us-east-2.compute.internal   Ready    control-plane,etcd,master   2m53s   v1.24.3+rke2r1   172.31.33.210   <none>        CentOS Linux 7 (Core)   3.10.0-1160.el7.x86_64   containerd://1.6.6-k3s1

NAMESPACE     NAME                                                                       READY   STATUS      RESTARTS   AGE     IP              NODE                                          NOMINATED NODE   READINESS GATES
kube-system   pod/cloud-controller-manager-ip-172-31-33-210.us-east-2.compute.internal   1/1     Running     0          2m48s   172.31.33.210   ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/etcd-ip-172-31-33-210.us-east-2.compute.internal                       1/1     Running     0          2m33s   172.31.33.210   ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/helm-install-rke2-canal-l8spl                                          0/1     Completed   0          2m36s   172.31.33.210   ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/helm-install-rke2-coredns-5xwgb                                        0/1     Completed   0          2m36s   172.31.33.210   ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/helm-install-rke2-ingress-nginx-vx9v8                                  0/1     Completed   0          2m36s   10.42.0.2       ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/helm-install-rke2-metrics-server-sffjn                                 0/1     Completed   0          2m36s   10.42.0.3       ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/kube-apiserver-ip-172-31-33-210.us-east-2.compute.internal             1/1     Running     0          2m46s   172.31.33.210   ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/kube-controller-manager-ip-172-31-33-210.us-east-2.compute.internal    1/1     Running     0          2m50s   172.31.33.210   ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/kube-proxy-ip-172-31-33-210.us-east-2.compute.internal                 1/1     Running     0          2m41s   172.31.33.210   ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/kube-scheduler-ip-172-31-33-210.us-east-2.compute.internal             1/1     Running     0          2m50s   172.31.33.210   ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/rke2-canal-9x868                                                       2/2     Running     0          2m27s   172.31.33.210   ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/rke2-coredns-rke2-coredns-76cb76d66-t6798                              1/1     Running     0          2m28s   10.42.0.4       ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/rke2-coredns-rke2-coredns-autoscaler-58867f8fc5-hgbqx                  1/1     Running     0          2m28s   10.42.0.5       ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/rke2-ingress-nginx-controller-nptnv                                    1/1     Running     0          104s    10.42.0.8       ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
kube-system   pod/rke2-metrics-server-6979d95f95-g5p7k                                   1/1     Running     0          113s    10.42.0.6       ip-172-31-33-210.us-east-2.compute.internal   <none>           <none>
```
- metrics are working:
```
$ k top node
NAME                                          CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
ip-172-31-33-210.us-east-2.compute.internal   747m         37%    2129Mi          56%   
```

**Closed by rancher-max** 2022-08-11 22:20 UTC
