### ISSUE TITLE
RKE2 uninstallation does not remove files under /usr/local/lib/systemd/system and /usr/local/bin/

### ISSUE THREAD

**Issue by rahendatri** [rancher/rke2#3733] opened 2023-01-02 14:55 UTC
**Environmental Info:**
RKE2 Version: v1.24.8+rke2r1
Node(s) CPU architecture, OS, and Version: Intel(R) Xeon(R) Gold 6230N CPU @ 2.30GHz, x86_64, Red Hat Enterprise Linux 8.6 (Ootpa)

**Describe the bug:**

According to https://github.com/rancher/rke2/issues/341, rke2 version later than `v1.18.10-rc1+rke2r1` removes files under `/usr/local/lib/systemd/system`.

**Steps To Reproduce:**

- Installed RKE2: 
- Uninstalled RKE2 using `rke2-uninstall.sh`
- Check files under `/usr/local/lib/systemd/system`
```
[root@machine ~]# systemctl status rke2-server
● rke2-server.service - Rancher Kubernetes Engine v2 (server)
   Loaded: loaded (/usr/local/lib/systemd/system/rke2-server.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: https://github.com/rancher/rke2#readme

```

- and files under `/usr/local/bin/`
```
ll /usr/local/bin
total 167708
-rwxr-xr-x. 1 root root 171721192 Nov 18 04:19 rke2
-rwxr-xr-x. 1 root root      2750 Nov 18 04:05 rke2-killall.sh
-rwxr-xr-x. 1 root root      3434 Nov 18 04:05 rke2-uninstall.sh

```

**Expected behavior:**
Both folders must not contain RKE2 files once uninstalled : `usr/local/lib/systemd/system` and `/usr/local/bin`

- Check files under `/usr/local/lib/systemd/system`
```
[root@machine ~]# ll /usr/local/lib/systemd/system/ | grep -i rke2


```

- and files under `/usr/local/bin/`
```
ll /usr/local/bin
total 0

```

**Comment by rahendatri** [comment] 2023-01-02 15:17
It seems like there is a slight problem here :
* https://github.com/rancher/rke2/blob/023804d1854a85030958a1948e5bebcf579e2581/bundle/bin/rke2-uninstall.sh#L23

Root path is /usr instead of /usr/local for RedHat.

**Comment by brandond** [comment] 2023-01-02 18:53
On RHEL distros, those files are owned by the RPM and should be removed when the package is uninstalled. Are you using the tar or rpm installation? Is the RPM being uninstalled successfully?

**Comment by rahendatri** [comment] 2023-01-02 21:51
@brandond I used the tar installation according to the airgap installation method :
`INSTALL_RKE2_ARTIFACT_PATH=/root/rke2-artifacts sh install.sh`

I just checked the installation script here (https://get.rke2.io/). It seems to me that it installs correctly with tar method. However, the `DEFAULT_TAR_PREFIX="/usr/local"` variable (see `setup_env()` function) is always set.

So to recap :
* tar installation uses `/usr/local` as root directory
* uninstallation script expects `/usr`

I would suggest to modify the `rke2-uninstall.sh` script ([these lines](https://github.com/rancher/rke2/blob/023804d1854a85030958a1948e5bebcf579e2581/bundle/bin/rke2-uninstall.sh#L81-L86)) to add `/usr/local`.

Looking forward to any suggestions.

**Comment by rahendatri** [comment] 2023-01-03 17:16
Hi, should I make a PR to implement above suggestion (if it is approved) ?

**Comment by brandond** [comment] 2023-01-03 19:47
Yes, a PR would be welcome. Thanks!

**Comment by brandond** [comment] 2023-01-09 19:11
I think this is probably a duplicate of https://github.com/rancher/rke2/issues/601

**Comment by rahendatri** [comment] 2023-01-11 08:32
Hi, yes this is a duplicate.
I can confirm (https://github.com/rancher/rke2/issues/601#issue-766907275) that currently TAR installation method cannot be detected on RedHat because of this line : https://github.com/rancher/rke2/blob/023804d1854a85030958a1948e5bebcf579e2581/bundle/bin/rke2-uninstall.sh#L22


I'll submit a PR soon.

**Comment by caroline-suse-rancher** [comment] 2023-06-28 19:58
Closing as a duplicate

**Closed by caroline-suse-rancher** 2023-06-28 19:58 UTC
