### ISSUE TITLE
Pod hostPort not exposed on a node after rke2 upgrade

### ISSUE THREAD

**Issue by slavonicsniper** [rancher/rke2#2325] opened 2022-01-07 13:09 UTC
**Environmental Info:**
RKE2 Version: 
rke2 version v1.21.6+rke2r1 (b915fc986e84582458af7131fe7f4e686f2af493)
go version go1.16.6b7

Node(s) CPU architecture, OS, and Version: 
5.11.0-37-generic #41~20.04.2-Ubuntu x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 servers (control plane and worker role)
cni: cilium (kubeProxyReplacement: disabled)

**Describe the bug:**
When creating a pod with `hostPort`, the port is not exposed on a k8s node anymore. The iptable rule is not created by kube-proxy. It was working fine on `v1.20.9+rke2r2`.

**Steps To Reproduce:**

- Installed RKE2: 
/etc/rancher/rke2/config.yaml:
```
token: <token>
tls-san:
  - <hostname1>
  - <hostname2>
  - <ip1>
  - <ip2>
cni: cilium
disable:
  - rke2-canal
  - rke2-ingress-nginx
kubelet-arg:
  - "config=/etc/rancher/rke2/kubelet.yaml"
```
- upgraded from `v1.20.9+rke2r2` to `v1.21.6+rke2r1` using [system-upgrade-controller](https://github.com/rancher/system-upgrade-controller)

**Expected behavior:**
Pods that exposes the ports via `hostPort` on the k8s nodes are still reachable. 

**Actual behavior:**
Pods that exposes the ports via `hostPort` on the k8s nodes are not reachable anymore and there are no HOSTPORT rules in iptables anymore.

**Additional context / logs:**
Could not find any related logs provided by kubelet, rke2-server service.
When using [Cilium’s eBPF kube-proxy replacement](https://docs.cilium.io/en/v1.10/gettingstarted/kubeproxy-free/#kubernetes-without-kube-proxy) and setting `kubeProxyReplacement: probe`, the hostPort works again provided via cilium. 
```
KubeProxyReplacement Details:
  Status:                Probe
  Socket LB Protocols:   TCP, UDP
  Devices:               <int> <ip> (Direct Routing)
  Mode:                  SNAT
  Backend Selection:     Random
  Session Affinity:      Enabled
  XDP Acceleration:      Disabled
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Enabled (Range: 30000-32767) 
  - LoadBalancer:   Enabled 
  - externalIPs:    Enabled 
  - HostPort:       Enabled
```
I noticed that there were some changes how kube-proxy is deployed in the rke2 but not sure whether this could have anything to do with it.

**Comment by brandond** [comment] 2022-01-07 16:51
Is there anything in the kube-proxy pod logs? Are they properly created if you reboot the node after upgrading?

**Comment by slavonicsniper** [comment] 2022-01-10 15:07
@brandond 

kube-proxy logs:

```
W0110 13:08:04.436115       1 server.go:224] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.                                                              │
│ W0110 13:08:04.436676       1 proxier.go:653] Failed to read file /lib/modules/5.11.0-44-generic/modules.builtin with error open /lib/modules/5.11.0-44-generic/modules.builtin: no such file or directory. You can ignore this message w │
│ W0110 13:08:04.438306       1 proxier.go:663] Failed to load kernel module ip_vs with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules                                     │
│ W0110 13:08:04.439583       1 proxier.go:663] Failed to load kernel module ip_vs_rr with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules                                  │
│ W0110 13:08:04.440599       1 proxier.go:663] Failed to load kernel module ip_vs_wrr with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules                                 │
│ W0110 13:08:04.441846       1 proxier.go:663] Failed to load kernel module ip_vs_sh with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules                                  │
│ W0110 13:08:04.442832       1 proxier.go:663] Failed to load kernel module nf_conntrack with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
.
.
.
│ W0110 13:13:13.497026       1 warnings.go:70] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice                                                                │
```

i guess that's fine.

reboot does not solve the issue.

**Comment by brandond** [comment] 2022-01-10 17:40
Can you show an example of a pod manifest that's not working for you? As far as I know, kube-proxy only sets up rules for services, not pods...

**Comment by slavonicsniper** [comment] 2022-01-11 15:55
I use https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/templates/server-statefulset.yaml. Probably you are right about kube-proxy not dealing with a pod but what changed then? The same pod manifest worked `v1.20.9+rke2r2`.

**Comment by brandond** [comment] 2022-01-11 17:26
Are you just not seeing some iptables rule that you expect, or are you saying that hostPort ports aren't working at all?

**Comment by slavonicsniper** [comment] 2022-01-14 09:04
hostPort ports aren't working at all. When reading [this](https://docs.cilium.io/en/v1.8/gettingstarted/kubeproxy-free/#:~:text=Similarly%2C%20we%20can%20inspect%20through%20iptables%20in%20the%20host%20namespace%20that%20no%20iptables%20rule%20for%20the%20HostPort%20service%20is%20present%3A) it looks like there should be rules for a pod hostPort as well.

**Comment by slavonicsniper** [comment] 2022-01-14 11:56
> I use https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/templates/server-statefulset.yaml. Probably you are right about kube-proxy not dealing with a pod but what changed then? The same pod manifest worked `v1.20.9+rke2r2`.

I use only this manifest at the moment where pod hostPort is used. How did you test it? Do you get anything from `iptables-save | grep HOSTPORT` after creating a pod with hostPort?

**Comment by brandond** [comment] 2022-01-14 16:42
cc @manuelbuil - any ideas what might be going on here?

**Comment by vadorovsky** [comment] 2022-01-14 17:39
The problem is that we disable eBPF kube-proxy replacement, which by default handles hostPort. But when the normal kube-proxy is used, Cilium should be chained with the portmap CNI plugins to be able to handle hostPort.

Upstream Helm charts allow to do that with:
https://docs.cilium.io/en/v1.10/gettingstarted/cni-chaining-portmap/

`--set cni.chainingMode=portmap` in Helm

But we don't expose that option in rke2-cilium chart :(

I think the sane fix will be,

1. First of all, enabling eBPF kube-proxy replacement.
2. Exposing the `cni.chainingMode` option in Helm just in case someone wants to stick to normal kube-proxy

I will work on that and try to make both things happen next week.

**Comment by slavonicsniper** [comment] 2022-01-17 15:23
@manuelbuil 
> Could you please check these two things: 1 - Show me the output of `sudo ls -altr /opt/cni/bin` 2 - Show me the output of `sudo cat /etc/cni/net.d/05-cilium.conf`

```
sudo ls -altr /opt/cni/bin
total 15544
drwxr-xr-x 3 root root     4096 May  3  2021 ..
-rwxr-xr-x 1 root root  2258536 May  3  2021 loopback
drwxr-xr-x 2 root root     4096 Dec 18 10:05 .
-rwxr-xr-x 1 root root 13647872 Dec 18 10:05 cilium-cni

sudo cat /etc/cni/net.d/05-cilium.conf
{
  "cniVersion": "0.3.1",
  "name": "cilium",
  "type": "cilium-cni",
  "enable-debug": false
}
```

@vadorovsky thanks for your explanation. On `v1.20.9+rke2r2` (hostPort working fine), we did not set `--set cni.chainingMode=portmap` when deploying the cilium. Could you please let me know what component made sure that pod hostPort functionality worked? Should i understand it that back then it was not necessary to setup `--set cni.chainingMode=portmap` for the pod hostPort to work and now from the certain rke2 version it is?
Thanks

**Comment by vadorovsky** [comment] 2022-01-17 23:39
@slavonicsniper As a temporary workaround, you can create the `/var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml` file with the following content:

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    cilium:
      cni:
        chainingMode: portmap
```

And redeploy your cluster.

For the next releases for rke2, I will try to enable [Kubernetes Without kube-proxy](https://docs.cilium.io/en/v1.9/gettingstarted/kubeproxy-free/) and then hostPort should work by default on Cilium, without any custom configs.

Sorry for the inconvenience!

**Comment by slavonicsniper** [comment] 2022-01-18 09:14
@vadorovsky I have already implemented a workaround (kubeProxyReplacement: probe) as we cannot redeploy the cluster. I was only curious how it worked before without defining `chainingMode: portmap` on cilium but if you cannot answer that, it's fine. Thanks for taking care of it anyway.

**Comment by vadorovsky** [comment] 2022-01-18 09:24
>I was only curious how it worked before without defining chainingMode: portmap on cilium but if you cannot answer that, it's fine.

Actually, no idea. From my understanding, hostPort shouldn't work without kubeProxyReplacement and without chainingMode on any Cilium version.

**Comment by websi96** [comment] 2022-03-02 22:35
TIL -> chainingMode:portmap would need the official portmap plugin: [https://www.cni.dev/plugins/current/meta/portmap/](https://www.cni.dev/plugins/current/meta/portmap/)

This is documented here: [https://docs.cilium.io/en/v1.10/gettingstarted/cni-chaining-portmap/#portmap-hostport](https://docs.cilium.io/en/v1.10/gettingstarted/cni-chaining-portmap/#portmap-hostport)

For now I solve it with kubeProxyReplacement: probe like so:

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    cilium:
      kubeProxyReplacement: probe
      cni:
        chainingMode: none
      hostPort:
        enabled: true
```

Maybe I will also give the replacement a try..

**Comment by revog** [comment] 2022-10-21 13:14
> > I was only curious how it worked before without defining chainingMode: portmap on cilium but if you cannot answer that, it's fine.
> 
> Actually, no idea. From my understanding, hostPort shouldn't work without kubeProxyReplacement and without chainingMode on any Cilium version.

Sorry for hi-jacking this issue. 

But I stumbled over the exactly same behaviour. We were running RKE2 1.21.10 (with kube-proxy) for months now and did an upgrade to 1.23.12 (still with kube-proxy). After this update, the hostPorts on our Rancher Mgt (installed with Rancher built-in Ingress) did not work anymore. After adding `kubeProxyReplacement: probe` the things were good again.

So why did this work in the past without this explicit option set?

**Comment by manuelbuil** [comment] 2022-10-26 08:58
> > > I was only curious how it worked before without defining chainingMode: portmap on cilium but if you cannot answer that, it's fine.
> > 
> > 
> > Actually, no idea. From my understanding, hostPort shouldn't work without kubeProxyReplacement and without chainingMode on any Cilium version.
> 
> Sorry for hi-jacking this issue.
> 
> But I stumbled over the exactly same behaviour. We were running RKE2 1.21.10 (with kube-proxy) for months now and did an upgrade to 1.23.12 (still with kube-proxy). After this update, the hostPorts on our Rancher Mgt (installed with Rancher built-in Ingress) did not work anymore. After adding `kubeProxyReplacement: probe` the things were good again.
> 
> So why did this work in the past without this explicit option set?

I think the issue is this one: https://github.com/rancher/rke2/issues/3490#issuecomment-1290419166, it was enabled by default in the past

**Comment by caroline-suse-rancher** [comment] 2023-06-28 21:56
Closing due to age and resolution

**Closed by caroline-suse-rancher** 2023-06-28 21:56 UTC
