### ISSUE TITLE
Node does not come up: Failed to check local etcd status for learner management: context deadline exceeded

### ISSUE THREAD

**Issue by salyh** [rancher/rke2#4510] opened 2023-07-26 12:16 UTC
**Environmental Info:**
RKE2 Version: 
rke2 version v1.27.3+rke2r1 (7c79e5e2c21c84613a301360512377bd9aebd833)
go version go1.20.5 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Linux dev 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:29:30 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

Cluster Configuration:
Single node cluster (1 server) on vmware fusion 13 (host system: macos 12.6.7 M1 arm64)

**Describe the bug:**
I try to install a single node cluster on a vmware fusion vm. Guest is Ubuntu 22.04 minimal arm64. Network mode is NAT.

**Steps To Reproduce:**

- Installed RKE2: 
export INSTALL_RKE2_VERSION=v1.27.3+rke2r1
curl -sfL https://get.rke2.io | sh -
systemctl start rke2-server.service

**Expected behavior:**
Node comes up

**Actual behavior:**
Node does not come up

**Additional context / logs:**
```
Jul 26 12:01:35 dev rke2[7925]: time="2023-07-26T12:01:35Z" level=info msg="Updating TLS secret for kube-system/rke2-serving (count: 10): map[listener.cattle.io/cn-10.43.0.1:10.43.0.1 listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-192.168.184.133:192.168.184.133 listener.cattle.io/cn-__1-f16284:::1 listener.cattle.io/cn-dev:dev listener.cattle.io/cn-kubernetes:kubernetes listener.cattle.io/cn-kubernetes.default:kubernetes.default listener.cattle.io/cn-kubernetes.default.svc:kubernetes.default.svc listener.cattle.io/cn-kubernetes.default.svc.cluster.local:kubernetes.default.svc.cluster.local listener.cattle.io/cn-localhost:localhost listener.cattle.io/fingerprint:SHA1=00263F1C7B99BAEC308EACCFFD1519431A0BAFC3]"
Jul 26 12:01:36 dev rke2[7925]: time="2023-07-26T12:01:36Z" level=info msg="Running kube-proxy --cluster-cidr=10.42.0.0/16 --conntrack-max-per-core=0 --conntrack-tcp-timeout-close-wait=0s --conntrack-tcp-timeout-established=0s --healthz-bind-address=127.0.0.1 --hostname-override=dev --kubeconfig=/var/lib/rancher/rke2/agent/kubeproxy.kubeconfig --proxy-mode=iptables"
Jul 26 12:02:24 dev rke2[7925]: {"level":"warn","ts":"2023-07-26T12:01:59.908Z","logger":"etcd-client","caller":"v3@v3.5.7-k3s1/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0x4000418e00/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Jul 26 12:02:24 dev rke2[7925]: {"level":"info","ts":"2023-07-26T12:01:59.909Z","logger":"etcd-client","caller":"v3@v3.5.7-k3s1/client.go:210","msg":"Auto sync endpoints failed.","error":"context deadline exceeded"}
Jul 26 12:02:24 dev rke2[7925]: {"level":"warn","ts":"2023-07-26T12:02:14.910Z","logger":"etcd-client","caller":"v3@v3.5.7-k3s1/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0x4000418e00/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Jul 26 12:02:24 dev rke2[7925]: {"level":"info","ts":"2023-07-26T12:02:14.911Z","logger":"etcd-client","caller":"v3@v3.5.7-k3s1/client.go:210","msg":"Auto sync endpoints failed.","error":"context deadline exceeded"}
Jul 26 12:02:24 dev rke2[7925]: {"level":"warn","ts":"2023-07-26T12:02:16.741Z","logger":"etcd-client","caller":"v3@v3.5.7-k3s1/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0x4000418e00/192.168.184.133:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Jul 26 12:02:24 dev rke2[7925]: time="2023-07-26T12:02:16Z" level=error msg="Failed to check local etcd status for learner management: context deadline exceeded"
Jul 26 12:02:24 dev rke2[7925]: time="2023-07-26T12:02:24Z" level=info msg="Tunnel authorizer set Kubelet Port 10250"

```
[rke2-logs.tar.gz](https://github.com/rancher/rke2/files/12172255/rke2-logs.tar.gz)

**Comment by brandond** [comment] 2023-07-26 19:14
It looks like etcd is crashing for some reason. Check the etcd and kube-apiserver pod logs under /var/log/pods.

**Comment by brandond** [comment] 2023-07-29 20:00
`2023-07-29T18:27:27.912525625Z stderr F {"level":"info","ts":"2023-07-29T18:27:27.912Z","caller":"embed/etcd.go:306","msg":"starting an etcd server","etcd-version":"3.5.7","git-sha":"Not provided (use ./build instead of go build)","go-version":"go1.20.4 X:boringcrypto","go-os":"linux","go-arch":"amd64","max-cpu-set":8,"max-cpu-available":8,"member-initialized":false,"name":"os-stable-cp-2-8d392595","data-dir":"/var/lib/rancher/rke2/server/db/etcd","wal-dir":"","wal-dir-dedicated":"","member-dir":"/var/lib/rancher/rke2/server/db/etcd/member","force-new-cluster":false,"heartbeat-interval":"500ms","election-timeout":"5s","initial-election-tick-advance":true,"snapshot-count":10000,"max-wals":5,"max-snapshots":5,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://localhost:2380"],"listen-peer-urls":["https://127.0.0.1:2380","https://128.140.85.5:2380"],"advertise-client-urls":["https://128.140.85.5:2379"],"listen-client-urls":["https://127.0.0.1:2379","https://128.140.85.5:2379"],"listen-metrics-urls":["http://127.0.0.1:2381"],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"os-stable-cp-2-8d392595=https://128.140.85.5:2380","initial-cluster-state":"existing","initial-cluster-token":"etcd-cluster","quota-backend-bytes":2147483648,"max-request-bytes":1572864,"max-concurrent-streams":4294967295,"pre-vote":true,"initial-corrupt-check":true,"corrupt-check-time-interval":"0s","compact-check-time-enabled":false,"compact-check-time-interval":"1m0s","auto-compaction-mode":"","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":"","downgrade-check-interval":"5s"}`
`2023-07-29T18:27:27.91370269Z stderr F {"level":"fatal","ts":"2023-07-29T18:27:27.913Z","caller":"etcdmain/etcd.go:204","msg":"discovery failed","error":"cannot fetch cluster info from peer urls: could not retrieve cluster information from the given URLs","stacktrace":"go.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2\n\t/go/src/go.etcd.io/etcd/server/etcdmain/etcd.go:204\ngo.etcd.io/etcd/server/v3/etcdmain.Main\n\t/go/src/go.etcd.io/etcd/server/etcdmain/main.go:40\nmain.main\n\tgo.etcd.io/etcd/server/main.go:32\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}`

> `"initial-cluster":"os-stable-cp-2-8d392595=https://128.140.85.5:2380"`
> `cannot fetch cluster info from peer urls: could not retrieve cluster information from the given URLs`

Etcd is unable to to connect to the other cluster members. Please check the port requirements in the documentation, and make sure that you've opened the correct ports between your nodes.

**Comment by brandond** [comment] 2023-07-29 23:25
I can't reproduce this. Can you confirm that the two nodes can communicate via the selected addresses? Do you need to adjust the network configuration for your vms to ensure that they're on the same virtual network, or use --node-ip to select the correct interface address?

**Comment by leagueofsoups** [comment] 2023-08-14 16:33
I get this problem from time to time.
crictl ps -a shows infinite restart on etcd container, not reproducible after restarting rke2-server systemd unit.

```
rke2 version v1.27.2+rke2r1 (300a06dabe679c779970112a9cb48b289c17536c)
go version go1.20.4 X:boringcrypto
```

```
{"level":"info","ts":"2023-08-14T16:11:03.025Z","caller":"etcdmain/config.go:343","msg":"loaded server configuration, other configuration command line flags and environment variables will be ignored if provided","path":"/var/lib/rancher/rke2/server/db/etcd/config"}
{"level":"info","ts":"2023-08-14T16:11:03.025Z","caller":"etcdmain/etcd.go:73","msg":"Running: ","args":["etcd","--config-file=/var/lib/rancher/rke2/server/db/etcd/config"]}
{"level":"info","ts":"2023-08-14T16:11:03.025Z","caller":"etcdmain/etcd.go:100","msg":"failed to detect default host","error":"could not find default route"}
{"level":"warn","ts":"2023-08-14T16:11:03.025Z","caller":"etcdmain/etcd.go:446","msg":"found invalid file under data directory","filename":"config","data-dir":"/var/lib/rancher/rke2/server/db/etcd"}
{"level":"warn","ts":"2023-08-14T16:11:03.025Z","caller":"etcdmain/etcd.go:446","msg":"found invalid file under data directory","filename":"name","data-dir":"/var/lib/rancher/rke2/server/db/etcd"}
{"level":"info","ts":"2023-08-14T16:11:03.025Z","caller":"etcdmain/etcd.go:116","msg":"server has been already initialized","data-dir":"/var/lib/rancher/rke2/server/db/etcd","dir-type":"member"}
{"level":"info","ts":"2023-08-14T16:11:03.025Z","caller":"embed/etcd.go:124","msg":"configuring peer listeners","listen-peer-urls":["https://10.12.42.224:2380","https://127.0.0.1:2380"]}
{"level":"info","ts":"2023-08-14T16:11:03.025Z","caller":"embed/etcd.go:484","msg":"starting with peer TLS","tls-info":"cert = /var/lib/rancher/rke2/server/tls/etcd/peer-server-client.crt, key = /var/lib/rancher/rke2/server/tls/etcd/peer-server-client.key, client-cert=, client-key=, trusted-ca = /var/lib/rancher/rke2/server/tls/etcd/peer-ca.crt, client-cert-auth = true, crl-file = ","cipher-suites":[]}
{"level":"info","ts":"2023-08-14T16:11:03.026Z","caller":"embed/etcd.go:132","msg":"configuring client listeners","listen-client-urls":["https://10.12.42.224:2379","https://127.0.0.1:2379"]}
{"level":"info","ts":"2023-08-14T16:11:03.026Z","caller":"embed/etcd.go:306","msg":"starting an etcd server","etcd-version":"3.5.7","git-sha":"Not provided (use ./build instead of go build)","go-version":"go1.20.3 X:boringcrypto","go-os":"linux","go-arch":"amd64","max-cpu-set":32,"max-cpu-available":32,"member-initialized":false,"name":"alfa-kubecontrol1.i-eaccbdd0","data-dir":"/var/lib/rancher/rke2/server/db/etcd","wal-dir":"","wal-dir-dedicated":"","member-dir":"/var/lib/rancher/rke2/server/db/etcd/member","force-new-cluster":false,"heartbeat-interval":"500ms","election-timeout":"5s","initial-election-tick-advance":true,"snapshot-count":10000,"max-wals":5,"max-snapshots":5,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://localhost:2380"],"listen-peer-urls":["https://10.12.42.224:2380","https://127.0.0.1:2380"],"advertise-client-urls":["https://10.12.42.224:2379"],"listen-client-urls":["https://10.12.42.224:2379","https://127.0.0.1:2379"],"listen-metrics-urls":["http://10.12.42.224:2381","http://127.0.0.1:2381"],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"alfa-kubecontrol1.i-eaccbdd0=https://10.12.42.224:2380","initial-cluster-state":"existing","initial-cluster-token":"etcd-cluster","quota-backend-bytes":2147483648,"max-request-bytes":1572864,"max-concurrent-streams":4294967295,"pre-vote":true,"initial-corrupt-check":true,"corrupt-check-time-interval":"0s","compact-check-time-enabled":false,"compact-check-time-interval":"1m0s","auto-compaction-mode":"","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":"","downgrade-check-interval":"5s"}
{"level":"info","ts":"2023-08-14T16:11:03.026Z","caller":"etcdserver/backend.go:81","msg":"opened backend db","path":"/var/lib/rancher/rke2/server/db/etcd/member/snap/db","took":"189.039µs"}
{"level":"info","ts":"2023-08-14T16:11:03.050Z","caller":"embed/etcd.go:373","msg":"closing etcd server","name":"alfa-kubecontrol1.i-eaccbdd0","data-dir":"/var/lib/rancher/rke2/server/db/etcd","advertise-peer-urls":["http://localhost:2380"],"advertise-client-urls":["https://10.12.42.224:2379"]}
{"level":"info","ts":"2023-08-14T16:11:03.050Z","caller":"embed/etcd.go:375","msg":"closed etcd server","name":"alfa-kubecontrol1.i-eaccbdd0","data-dir":"/var/lib/rancher/rke2/server/db/etcd","advertise-peer-urls":["http://localhost:2380"],"advertise-client-urls":["https://10.12.42.224:2379"]}
{"level":"fatal","ts":"2023-08-14T16:11:03.050Z","caller":"etcdmain/etcd.go:204","msg":"discovery failed","error":"cannot fetch cluster info from peer urls: could not retrieve cluster information from the given URLs","stacktrace":"go.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2\n\t/go/src/go.etcd.io/etcd/server/etcdmain/etcd.go:204\ngo.etcd.io/etcd/server/v3/etcdmain.Main\n\t/go/src/go.etcd.io/etcd/server/etcdmain/main.go:40\nmain.main\n\tgo.etcd.io/etcd/server/main.go:32\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
```

**Comment by brandond** [comment] 2023-08-14 18:12
> p.s: I use rr dns as registration endpoint.

Do you have all of the intended servers listed in the DNS entry for the registration endpoint, or just the ones that are up and running?

**Comment by brandond** [comment] 2023-08-14 18:52
I would avoid listing non-operational servers in the RR record. Use of RR DNS for the fixed registration endpoint works best with DNS services that allow for health-checking.

**Comment by leagueofsoups** [comment] 2023-08-14 19:20
Thanks for the answer.  I realized that this behavior is not a bug.

**Comment by caroline-suse-rancher** [comment] 2023-08-14 21:45
Closing as not able to reproduce

**Closed by caroline-suse-rancher** 2023-08-14 21:45 UTC

**Comment by bendemott** [comment] 2024-04-14 21:32
In my case this is an issue related to the host environment (Debian)
see: https://stackoverflow.com/questions/55571566/unable-to-bring-up-kubernetes-api-server

> The problem is cgroupv2 introduced with Ubuntu 21.04 and above(Debian since version 11).
You need to tell containerd to use the systemdCgroup driver via the config file(/etc/containerd/config.toml).
