### ISSUE TITLE
ServiceLB pods in Kube-System fail to deploy on v1.27.15

### ISSUE THREAD

**Issue by davidgaster** [rancher/rke2#6575] opened 2024-08-15 17:06 UTC
**Environmental Info:**
rke2 version v1.27.15+rke2r1 (4014ef7e8fbfb47e6a1e2261a73ca50aef8ba7fb)
go version go1.21.11 X:boringcrypto

**Node(s) CPU architecture, OS, and Version**

Linux lattice.local 4.18.0-553.el8_10.x86_64 #1 SMP Fri May 10 15:19:13 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
NAME="Red Hat Enterprise Linux"
VERSION="8.10 (Ootpa)"

Cluster Configuration:

3 servers

**Describe the bug:**

When RKE2 is started with `enable-servicelb: true` set in its `config.yaml`, LoadBalancer services are stuck in a Pending state. `svclb-*` pods are failing to be created in the `kube-system` namespace. Event logs show this error:
```
Events:
  Type     Reason                  Age                   From                Message
  ----     ------                  ----                  ----                -------
  Warning  SyncLoadBalancerFailed  7m41s (x19 over 72m)  service-controller  Error syncing load balancer: failed to ensure load balancer: failed to create kube-system/svclb-contour-root-envoy-bbb9774b apps/v1, Kind=DaemonSet for  lattice/contour-root-envoy: DaemonSet.apps "svclb-contour-root-envoy-bbb9774b" is invalid: [spec.template.spec.containers[0].env[4].valueFrom.fieldRef.fieldPath: Invalid value: "status.hostIPs": error converting fieldPath: field label not supported: status.hostIPs, spec.template.spec.containers[1].env[4].valueFrom.fieldRef.fieldPath: Invalid value: "status.hostIPs": error converting fieldPath: field label not supported: status.hostIPs]
```

I will note that the exact same configuration works perfectly fine on RKE2 v1.25.12.

**Steps To Reproduce:**

- Installed RKE2: via RPM method. All RKE2 selinux, common, and server RPMs are installed, and required yum dependencies as well.
- `/etc/rancher/rke2/config.yaml`:
```
selinux: true
profile: cis
disable:
- rke2-ingress-nginx
enable-servicelb: true
```

**Expected behavior:**

RKE2 is able to provision LoadBalancer services.

**Actual behavior:**

LoadBalancer services become stuck in Pending.

**Additional context / logs:**

One note I am seeing is some of the kube-system pods are on 1.29 versions for some reason on 1.27.15. E.g.:
```
      image: index.docker.io/rancher/rke2-cloud-provider:v1.29.3-build20240515
      image: docker.io/rancher/rke2-cloud-provider:v1.29.3-build20240515
```
On the working RKE2 1.27.12 install, I see 1.28 versions:
```
      image: index.docker.io/rancher/rke2-cloud-provider:v1.28.2-build20231016
      image: docker.io/rancher/rke2-cloud-provider:v1.28.2-build20231016
```

Why are these cloud provider versions not on 1.27.*?

**Comment by davidgaster** [comment] 2024-08-15 17:14
Looks like a very similar issue to https://github.com/rancher/rke2/issues/5882

**Comment by brandond** [comment] 2024-08-15 17:26
Yes, this is a duplicate of https://github.com/rancher/rke2/issues/5882

See the workaround at https://github.com/rancher/rke2/issues/5882#issuecomment-2096833673

**Closed by brandond** 2024-08-15 17:26 UTC
