### ISSUE TITLE
Air-gapped installation failing due to kube-controller-manager requiring C2S CA Bundle

### ISSUE THREAD

**Issue by nick-bob** [rancher/rke2#814] opened 2021-03-24 17:59 UTC
Running version: 1.18.13~rke2r1 on a hardened centos7 image.

We're having some issues with our air-gapped installation. Please advise.

The error is identical to this [here](https://bugzilla.redhat.com/show_bug.cgi?id=1915500).

```
During cluster bootstrapping, the kube-controller-manager is continually crashing for the following:
W0112 17:48:43.474274       1 plugins.go:105] WARNING: aws built-in cloud provider is now deprecated. The AWS provider is deprecated and will be removed in a future release
I0112 17:48:43.474561       1 aws.go:1251] Building AWS cloudprovider
I0112 17:48:43.474623       1 aws.go:1211] Zone not specified in configuration file; querying AWS metadata service
F0112 17:48:43.999923       1 controllermanager.go:259] error building controller context: cloud provider could not be initialized: could not init cloud provider "aws": error finding instance i-06ad0cf0811862648: "error listing AWS instances: \"RequestError: send request failed\\ncaused by: Post \\\"https://ec2.us-iso-east-1.c2s.ic.gov/\\\": x509: certificate signed by unknown authority\""
```

Is there a way to configure the kube-controller-manager to use the C2S CA bundle?

**Comment by brandond** [comment] 2021-03-24 18:07
We mount the host certificate dirs into the apiserver static pod, but not into any others. We could probably add that same behavior to the controller manager pod at the very least.

https://github.com/rancher/rke2/blob/d0685892f69477a50b7466a2a8d73e83983d62a8/pkg/podexecutor/staticpod.go#L135

**Comment by davidnuzik** [comment] 2021-04-06 17:12
@brandond looks like this should be in To Test state as well. Can you fix this?

**Comment by rancher-max** [comment] 2021-04-12 23:23
I cannot fully reproduce as I do not have access to aws govcloud, but I believe this should be resolved in v1.20.5-alpha1+rke2r2, and will be available in the upcoming release `v1.20.6+rke2r1`

- Mounts are present on kube-controller pods (notice the `/etc/...` mounts that were not present previously:
```
Containers:
  kube-controller-manager:
    ...
    Mounts:
      /etc/pki/tls/certs from dir1 (rw)
      /etc/ssl/certs from dir0 (rw)
      /var/lib/rancher/rke2/server/cred/controller.kubeconfig from file1 (ro)
      /var/lib/rancher/rke2/server/db/etcd/name from file0 (ro)
      /var/lib/rancher/rke2/server/tls/client-ca.crt from file2 (ro)
      /var/lib/rancher/rke2/server/tls/client-ca.key from file3 (ro)
      /var/lib/rancher/rke2/server/tls/client-controller.crt from file4 (ro)
      /var/lib/rancher/rke2/server/tls/client-controller.key from file5 (ro)
      /var/lib/rancher/rke2/server/tls/server-ca.crt from file6 (ro)
      /var/lib/rancher/rke2/server/tls/service.key from file7 (ro)
...
Volumes:
  dir0:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/ssl/certs
    HostPathType:  DirectoryOrCreate
  dir1:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/pki/tls/certs
    HostPathType:  DirectoryOrCreate
...
```
- Validated on both an airgap setup without using cloudprovider and a non-airgap setup with cloudprovider (since I cannot do airgap with cloudprovider as aforementioned)

**Closed by rancher-max** 2021-04-12 23:23 UTC
Labels: enhancement

**Comment by joshrwolf** [comment] 2021-04-13 03:28
@nick-bob for some additional clarification, I was able to confirm @rancher-max's statement testing on our internal mock c2s environment

typically in the past when `kube-controller-manager` used an older version of the aws go sdk, we recommended running the out of tree aws controller and mounting the ca certs and `cloud.conf` to point to the appropriate endpoints. 

For newer versions of `kube-controller-manager` (which are included in the versions @rancher-max listed above), the in-tree provider appears to be sufficient to support (t)c2s endpoints.  Combined with the additional host mounts, the next version of `rke2` should make the experience much cleaner.

For brevity, below is the full experience for using `v1.20.6+rke2r1` (when it's out) on (t)c2s with the in-tree aws provider, as well as how to override the endpoints on the off chance that the in-tree provider is insufficient (or you have custom api endpoints):

1. ensure CA bundle is in `/etc/pki/tls/certs` OR `/etc/ssl/certs`, most (T)C2S AMI's have this baked in.  If they do not you can add it to the system ca trust store with:

```bash
mv <c2s.pem> /etc/pki/ca-trust/source/anchors/
update-ca-trust
```

2. (optional) define custom aws endpoints for services used by the cloud controller

```yaml
# /etc/rancher/rke2/cloud.conf
[Global]
[ServiceOverride "ec2"]
  Service=ec2
  Region=us-iso-east-1
  URL=https://ec2.us-iso-east-1.c2s.ic.gov
  SigningRegion=us-iso-east-1
[ServiceOverride "s3"]
  Service=s3
  Region=us-east-1
  URL=https://s3.us-iso-east-1.c2s.ic.gov
  SigningRegion=us-iso-east-1
[ServiceOverride "elasticloadbalancing"]
  Service=elasticloadbalancing
  Region=us-iso-east-1
  URL=https://elasticloadbalancing.us-iso-east-1.c2s.ic.gov
  SigningRegion=us-iso-east-1
```

3. configure `rke2` to use aws provider with custom cloud configuration

```yaml
# /etc/rancher/rke2/config.yaml
cloud-provider-name: aws
cloud-provider-config: "/etc/rancher/rke2/cloud.conf"
...
```

4. __important__: ensure aws pre-requisites are met, seen [here](https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/aws/).  These are the same pre-requisites regardless of which aws or distro you're on.

4. install rke2 as normal ([example](https://docs.rke2.io/install/quickstart/#2-enable-the-rke2-server-service))

5. validate successful node registration by checking node labels for the existence of aws information (bolded below):

```
NAME                           STATUS   ROLES                       AGE   VERSION                LABELS
ip-10-0-105-142.ec2.internal   Ready    control-plane,etcd,master   20m   v1.20.5-dev+857cd6c8   beta.kubernetes.io/arch=amd64,__beta.kubernetes.io/instance-type=m5d.xlarge__,beta.kubernetes.io/os=linux,__failure-domain.beta.kubernetes.io/region=us-iso-east-1__,__failure-domain.beta.kubernetes.io/zone=us-iso-iso-east-1c__,kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-10-0-105-142.ec2.internal,kubernetes.io/os=linux,node-role.kubernetes.io/control-plane=true,node-role.kubernetes.io/etcd=true,node-role.kubernetes.io/master=true,__node.kubernetes.io/instance-type=m5d.xlarge__,rke2.io/hostname=ip-10-0-105-142.ec2.internal,rke2.io/internal-ip=10.0.105.142,__topology.kubernetes.io/region=us-iso-east-1__,__topology.kubernetes.io/zone=us-iso-east-1c__
```

thanks for raising this issue, hopefully this helps!

**Comment by nick-bob** [comment] 2021-04-19 03:17
Thanks a lot everyone, you all are rock stars. With the info @brandond provided, we were able to deploy a temp "hotfix" build pretty quickly. Thanks for the heads up and guidance @joshrwolf. I'm sure this will come handy at some point.
