### ISSUE TITLE
RKE2 running on t3a.medium instance at system load of 10+

### ISSUE THREAD

**Issue by dnoland1** [rancher/rke2#168] opened 2020-08-07 20:37 UTC
Set up a basic two node cluster using two t3a.medium instances on AWS. Using v1.18.4-beta1+rke2. Since install and after about 20 minutes, the server system load is settling just above 10, which seems a bit high. Running RKE and K3s clusters on same specs using results in load below 1. Top output:
```
top - 20:35:24 up 51 min,  2 users,  load average: 15.11, 15.49, 14.98
Tasks: 165 total,   4 running, 161 sleeping,   0 stopped,   0 zombie
%Cpu(s):  9.2 us,  8.0 sy,  0.0 ni, 16.8 id,  0.0 wa,  0.0 hi,  0.1 si, 65.9 st
MiB Mem :   3888.5 total,    156.9 free,   1596.4 used,   2135.2 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   2587.3 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND     
   2273 root      20   0 1507640 752352  59868 S  11.7  18.9   8:39.34 kube-apiser+
 108877 root      20   0  808908 125144  58552 S  11.0   3.1   0:56.37 kube-contro+
    391 systemd+  20   0   24044  12128   8124 S   6.3   0.3   0:56.97 systemd-res+
    514 root      20   0   26584  16248   8372 S   6.3   0.4   1:31.41 networkd-di+
 109010 root      20   0  744600  42884  30692 S   6.0   1.1   0:09.00 kube-schedu+
   2054 root      20   0 1922036  94520  49836 S   5.7   2.4   2:43.65 kubelet     
 158547 root      20   0   18872   3196   1812 S   5.7   0.1   0:08.76 systemd-ude+
 171959 root      20   0 1050896  46064  33244 S   5.7   1.2   0:03.97 calico-node 
   2162 root      20   0   10.2g 148092  32648 S   4.3   3.7   2:24.07 etcd        
   2028 root      20   0 1890096  57788  18288 S   3.7   1.5   5:29.65 containerd  
```

Worker is about half the load, but still on the high side from what I would expect:
```
top - 20:36:08 up 52 min,  1 user,  load average: 7.70, 7.32, 5.43
Tasks: 151 total,   4 running, 147 sleeping,   0 stopped,   0 zombie
%Cpu(s):  8.6 us,  8.1 sy,  0.0 ni, 17.4 id,  0.0 wa,  0.0 hi,  0.0 si, 65.9 st
MiB Mem :   3888.5 total,    120.5 free,    703.1 used,   3064.9 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   3020.2 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                               
    864 root      20   0  852164  33996  14896 S  11.6   0.9   1:30.57 snapd                                                                                                 
 266730 root      20   0 1050896  47380  34368 S   9.3   1.2   0:08.69 calico-node                                                                                           
      1 root      20   0  102752  12508   8548 R   8.6   0.3   1:15.41 systemd                                                                                               
 177231 root      20   0   19800   3988   1728 S   7.0   0.1   0:46.36 systemd-udevd                                                                                         
 177228 root      20   0   18808   2992   1728 S   5.6   0.1   0:16.08 systemd-udevd                                                                                         
   1270 ubuntu    20   0   18764   9896   8076 R   4.3   0.2   1:11.70 systemd                                                                                               
    508 root      20   0   26452  17804   9948 S   4.0   0.4   1:44.16 networkd-dispat                                                                                       
   2103 root      20   0 1847792 100136  63188 S   4.0   2.5   1:18.56 kubelet                                                                                               
   2162 root      20   0  712396  11300   6996 S   3.7   0.3   0:09.63 containerd-shim                                                                                       
```

OS details:
```
# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by briandowns** [comment] 2020-08-07 20:56
This is pretty consistently returning that kube-apiserver is taking the majority of CPU percentage.

```
ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%mem | head
```

**Comment by brandond** [comment] 2020-08-07 21:15
The steal time on both of these instances is quite high: `65.9 st`- are they out of CPU credits?

Per the table below, t3a.medium instances are only spec'd to sustain 20% cpu utilization, if you go above this for too long you are eventually gong to get throttled.
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-credits-baseline-concepts.html#earning-CPU-credits

**Comment by briandowns** [comment] 2020-08-07 21:16
This behavior is on my local vm's as well.

**Comment by asm76** [comment] 2020-09-01 11:31
It looks same as #57 issue. To make sure, can you check the system logs with `journalctl -f`?

**Comment by galal-hussein** [comment] 2020-09-21 21:42
looks like a duplicate of https://github.com/rancher/rke2/issues/57#issuecomment-696338396, I cant reproduce this issue as, I tested with 3 t3.medium servers in HA and also as a single server and two agents, both ran over an hour with cpu usage less than 4% consistently, I am closing this one as well, please @dnoland1 reopen if you still getting the issue with beta20

**Closed by galal-hussein** 2020-09-21 21:42 UTC
Labels: [zube]: Working

**Comment by dnoland1** [comment] 2020-10-09 23:37
Tried on latest version:
```
# rke2 -v
rke2 version v1.18.9+rke2r1 (67ded31a6924dac8d0c497b7b1c180a28d8a31af)
```
Looking much better. Server:
```
top - 23:36:43 up 14 min,  1 user,  load average: 0.31, 1.40, 1.47
Tasks: 124 total,   1 running, 123 sleeping,   0 stopped,   0 zombie
%Cpu(s):  2.2 us,  1.9 sy,  0.0 ni, 94.6 id,  0.3 wa,  0.0 hi,  0.2 si,  0.8 st
MiB Mem :   3888.5 total,    111.6 free,   1004.5 used,   2772.4 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   2831.2 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   1574 root      20   0  705320 538676  70172 S   3.7  13.5   1:52.87 kube-apiserver
   1463 root      20   0   10.7g  59760  24004 S   2.3   1.5   0:25.89 etcd
   3680 root      20   0  750108  45316  30896 S   1.7   1.1   0:12.18 calico-node
   1345 root      20   0  143276  60400  25644 S   1.3   1.5   3:14.58 containerd
   1362 root      20   0  215160  94320  64272 S   1.3   2.4   0:28.82 kubelet
```
Agent:
```
top - 23:36:23 up 13 min,  1 user,  load average: 0.17, 0.22, 0.16
Tasks:  93 total,   1 running,  92 sleeping,   0 stopped,   0 zombie
%Cpu(s):  2.7 us,  3.5 sy,  0.0 ni, 92.7 id,  0.0 wa,  0.0 hi,  0.0 si,  1.1 st
MiB Mem :   3888.5 total,   1298.8 free,    285.5 used,   2304.2 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   3396.3 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   2659 root      20   0  750108  44032  29428 S   2.3   1.1   0:06.68 calico-node
   1979 root      20   0  214568  84032  60572 S   1.7   2.1   0:05.26 kubelet
   1966 root      20   0  140992  53772  25484 S   1.0   1.4   0:25.36 containerd
   2139 root      20   0  142392  32740  25832 S   0.7   0.8   0:00.40 kube-proxy
     11 root      20   0       0      0      0 I   0.3   0.0   0:00.15 rcu_sched
   1951 root      20   0  261984 121204  78264 S   0.3   3.0   0:10.85 rke2
```
