### ISSUE TITLE
Certificate rotate fails

### ISSUE THREAD

**Issue by frit0-rb** [rancher/rke2#5356] opened 2024-02-06 09:20 UTC
**Environmental Info:**
RKE2 Version: rke2 version v1.26.11+rke2r1 (7ee1cfc93db32d05f3270711b24c429515019e8a)
go version go1.20.11 X:boringcrypto

Node(s) CPU architecture, OS, and Version: Linux 4.18.0-513.11.1.el8_9.x86_64 #1 SMP Thu Dec 7 03:06:13 EST 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 3 controllers (servers), 5 workers (agents)

**Describe the bug:**

I got a Cluster originally created via Rancher and now working like a imported cluster. I want to rotate the certificates, but when I run rke2 certificate rotate, looks fine and when I restart the service rke2-server the .crt from kube-controller-manager.crt still be the old cert.

**Expected behavior:**

The behavior expected is to rotate the kube-controller-manager.crt in all controllers server

**Actual behavior:**

Still the same old certificate an never rotate

**Additional context / logs:**

We want to know how is the best way to rotate all certificated in RKE2 without Rancher, with in my case with 3 controllers

**Comment by brandond** [comment] 2024-02-06 18:23
I believe this is a duplicate of https://github.com/rancher/rancher/issues/41125#issuecomment-1711807298

These files are managed by Rancher, not RKE2.

**Closed by brandond** 2024-02-06 18:23 UTC

**Comment by frit0-rb** [comment] 2024-02-07 08:56
Let me ask you something @brandond , like you are telling me files like kube-controller-manager.crt shouldn´t exist when a cluster is imported in Rancher and you manage from Rancher, right? Because that is the case, the Cluster is imported but that files exist.

![image](https://github.com/rancher/rke2/assets/56691791/72670f3e-733d-475c-9181-6d6fb0d29f58)

So like you telling the yaml info shouldn´t has that config, right?

One important thing, this cluster was original created via Rancher and then register again in Rancher like imported Cluster

![image](https://github.com/rancher/rke2/assets/56691791/ee32438c-a814-4fae-a803-1e557c6c54f9)

**Comment by brandond** [comment] 2024-02-07 16:37
> this cluster was original created via Rancher and then register again in Rancher like imported Cluster

So this was a Rancher-provisioned cluster, that you then deleted from Rancher, and then imported as a new cluster? I'm not sure that's supported. You are going to be missing out on many of the cluster management features that are available when Rancher recognizes the cluster as provisioned. That would include certificate rotation for certificates that are created due to rancher adding that `--cert-dir` arg to the controller args.

You can follow the steps in that issue I linked above to manually delete the certificates, but this will continue to be a problem for you due to loss of functionality due to the cluster being re-imported. Long-term I would work on replacing this cluster with one that is either actually provisioned by rancher, or is a standalone install of RKE2 that is then imported into Rancher. Right now you have the worst of both worlds.
