### ISSUE TITLE
fix coredns config map warning

### ISSUE THREAD

**Issue by cjellick** [rancher/rke2#376] opened 2020-09-27 22:11 UTC
make this not happen:
```
Sep 27 22:01:11 craig-rke2 rke2[2493703]: time="2020-09-27T22:01:11Z" level=warning msg="Unable to fetch coredns config map: configmap \"coredns\" not found"
```

**Comment by brandond** [comment] 2020-09-28 20:04
@cjellick I think this is a regression caused by #361 that should be fixed before GA. I failed to consider that --disable still turns off controllers associated with a few of the manifests, even if those manifests are disabled at build time. That change means that the coredns and servicelb controllers are now active on rke2, when they should not be.

**Comment by ShylajaDevadiga** [comment] 2020-09-30 21:56
Validated in v1.18.9-beta22+rke2, coredns config map warning is not seen in logs.

**Closed by ShylajaDevadiga** 2020-09-30 21:56 UTC
Labels: [zube]: To Test, kind/bug
