### ISSUE TITLE
Consistent filename and location on Ubuntu and Centos/rhel while using rpm install

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#183] opened 2020-08-13 06:56 UTC
RKE2 Version: v1.18.4-beta1-rke2

Installation using install script on Ubuntu and installation using rpm on Centos/rhel have different filename and location. It would be good to have it consistent across all installs.

**Unit filename and path**
Ubuntu: /etc/systemd/system/rke2
Centos/rhel: /usr/lib/systemd/system/rke2-server.service

**rke2 binary path**
Ubuntu: /usr/local/bin/rke2
Centos/rhel: /usr/bin/rke2

**Environment filename and path**
Ubuntu:  /etc/systemd/system/rke2.service.env
Centos/rhel: /etc/sysconfig/rke2-server

**Comment by cjellick** [comment] 2020-09-11 20:49
closing as a dupe of https://github.com/rancher/rke2/issues/295

**Closed by cjellick** 2020-09-11 20:49 UTC
Labels: [zube]: Backlog
