### ISSUE TITLE
Cilium SELinux AVC denials

### ISSUE THREAD

**Issue by bluikko** [rancher/rke2#1273] opened 2021-07-09 10:04 UTC
**Environmental Info:**
RKE2 Version: 

```
rke2 version v1.21.2+rke2r1 (d58ad6197b05144711671cec03a9027058969bf0)
go version go1.16.4b7
```
Node(s) CPU architecture, OS, and Version: 

```
Linux host 5.13.0-1.el7.elrepo.x86_64 #1 SMP Sun Jun 27 19:45:23 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
```
Cluster Configuration:

- 3 servers
- dual-stack
- cilium
- kube-proxy-less

**Describe the bug:**

SELinux AVC denials are seen when using Cilium CNI, at least in kube-proxy-less mode: noticed when trying to turn on host-reachable services.

**Steps To Reproduce:**

- Installed RKE2: 

/var/lib/rancher/rke2/server/manifests/rke2-cilium.yml
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    ipv6:
      enabled: true
```
/etc/rancher/rke2/config.yaml
```yaml
bind-address: "192.0.2.1"
advertise-address: "192.0.2.1"
cluster-cidr: "10.0.0.0/10,2001:db8:1000::/48"
service-cidr: "10.128.0.0/12,2001:db8:1001::/48"
cluster-dns: "10.128.0.10"
cluster-domain: "c.domain"
node-ip: "192.0.2.1,2001:db8::1"
node-external-ip: "172.16.0.1,2001:db8:f::1"
token: "something"
tls-san:
  - "lb.domain"
  - "192.0.2.1"
  - "192.0.2.2"
  - "192.0.2.3"
  - "2001:db8::1"
  - "2001:db8::2"
  - "2001:db8::3"
cni: cilium
disable:
  - rke2-kube-proxy
```

**Expected behavior:**

SELinux should work in enforcing mode.

**Actual behavior:**

SELinux needs to be put to permissive mode or AVC denials happen.

**Additional context / logs:**

AVC denials:
```
: avc:  denied  { ioctl } for  pid=1234 comm="ip6tables" path="/sys/fs/cgroup" dev="tmpfs" ino=1 scontext=system_u:system_r:iptables_t:s0 tcontext=system_u:object_r:cgroup_t:s0 tclass=dir permissive=1
: avc:  denied  { ioctl } for  pid=1234 comm="iptables" path="/sys/fs/cgroup" dev="tmpfs" ino=1 scontext=system_u:system_r:iptables_t:s0 tcontext=system_u:object_r:cgroup_t:s0 tclass=dir permissive=1
: avc:  denied  { map_create } for  pid=1234 comm="cilium-agent" scontext=system_u:system_r:spc_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=bpf permissive=1
: avc:  denied  { map_read map_write } for  pid=1234 comm="cilium-agent" scontext=system_u:system_r:spc_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=bpf permissive=1
: avc:  denied  { prog_load } for  pid=1234 comm="bpftool" scontext=system_u:system_r:spc_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=bpf permissive=1
: avc:  denied  { prog_run } for  pid=1234 comm="bpftool" scontext=system_u:system_r:spc_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=bpf permissive=1
```

**Comment by brandond** [comment] 2021-07-09 17:03
This sounds like two issues rather than one - would you mind opening a second issue for your IPv6 questions so that we can use this one to track the selinux denials that you're seeing?

**Comment by bluikko** [comment] 2021-07-10 06:36
> This sounds like two issues rather than one - would you mind opening a second issue for your IPv6 questions so that we can use this one to track the selinux denials that you're seeing?

I've opened #1277. I was not sure if that would count as a separate issue so had put them together here.

I have now edited this issue to separate them as 2 totally independent issues.

**Comment by brandond** [comment] 2021-07-12 18:18
cc @manuelbuil @cjellick @cwayne18   - do you know if we've tested cilium on selinux-enabled hosts?

**Comment by manuelbuil** [comment] 2021-07-12 18:54
> cc @manuelbuil @cjellick @cwayne18 - do you know if we've tested cilium on selinux-enabled hosts?

Yes, we did. @vadorovsky fixed one issue related to it

**Comment by vadorovsky** [comment] 2021-07-13 12:01
@rancher-max Have you ever seen this issue when testing with SELinux?

Anyway, I will try to reproduce it now,.

**Comment by rancher-max** [comment] 2021-07-13 16:10
I have not seen this before. My guess is that this has something to do with disabling kube-proxy, as that is not a configuration I have tried before with cilium+selinux.

**Comment by vadorovsky** [comment] 2021-07-13 16:36
I could reproduce it on CentOS 7 + kernel 5.13 (from elrepo) + SELinux. It doesn't seem to have anything in common with disabling kube-proxy - any BPF operations (accessing maps, loading programs) get denied.

Here are the logs:

https://paste.centos.org/view/b870fadb

Almost every bpftool command is denied:

```
proctitle=6970367461626C65732D726573746F7265002D770035002D5700313030303030002D2D6E6F666C757368002D2D636F756E74657273
type=AVC msg=audit(1626189345.067:258): avc:  denied  { prog_load } for  pid=3016 comm="bpftool" scontext=system_u:system_r:spc_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=bpf permissive=1
type=SYSCALL msg=audit(1626189345.067:258): arch=c000003e syscall=321 success=no exit=-14 a0=5 a1=7ffc96bb9580 a2=78 a3=0 items=0 ppid=2963 pid=3016 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="bpftool" exe="/usr/bin/bpftool" subj=system_u:system_r:spc_t:s0 key=(null)
type=PROCTITLE msg=audit(1626189345.067:258): proctitle=627066746F6F6C002D6A00666561747572650070726F6265
type=UNKNOWN[1334] msg=audit(1626189345.067:259): prog-id=1 op=LOAD
type=AVC msg=audit(1626189345.067:259): avc:  denied  { prog_run } for  pid=3016 comm="bpftool" scontext=system_u:system_r:spc_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=bpf permissive=1
type=SYSCALL msg=audit(1626189345.067:259): arch=c000003e syscall=321 success=yes exit=3 a0=5 a1=7ffc96bb9380 a2=78 a3=0 items=0 ppid=2963 pid=3016 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="bpftool" exe="/usr/bin/bpftool" subj=system_u:system_r:spc_t:s0 key=(null)
type=PROCTITLE msg=audit(1626189345.067:259): proctitle=627066746F6F6C002D6A00666561747572650070726F6265
type=UNKNOWN[1334] msg=audit(1626189345.067:260): prog-id=1 op=UNLOAD
type=UNKNOWN[1334] msg=audit(1626189345.067:261): prog-id=2 op=LOAD
type=SYSCALL msg=audit(1626189345.067:261): arch=c000003e syscall=321 success=yes exit=3 a0=5 a1=7ffc96bb9380 a2=78 a3=2d items=0 ppid=2963 pid=3016 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="bpftool" exe="/usr/bin/bpftool" subj=system_u:system_r:spc_t:s0 key=(null)
```

Then cilium-agent trying to do any BPF map operations gets denied:

```
type=AVC msg=audit(1626189363.333:1226): avc:  denied  { map_create } for  pid=2963 comm="cilium-agent" scontext=system_u:system_r:spc_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=bpf permissive=1
type=AVC msg=audit(1626189363.333:1226): avc:  denied  { map_read map_write } for  pid=2963 comm="cilium-agent" 
```

And iproute2 as well:

```
type=AVC msg=audit(1626189363.361:1227): avc:  denied  { prog_load } for  pid=3502 comm="tc" scontext=system_u:system_r:spc_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=bpf permissive=1
type=UNKNOWN[1334] msg=audit(1626189363.361:1227): prog-id=480 op=LOAD
type=AVC msg=audit(1626189363.361:1227): avc:  denied  { prog_run } for  pid=3502 comm="tc" scontext=system_u:system_r:spc_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=bpf permissive=1
```

**Comment by vadorovsky** [comment] 2021-07-13 16:39
I will try out whether applying some SELinux type (`cilium_container_t`?) on Cilium pods and writing a policy for them (which will allow our `cilium_container_t` to do `map_create`, `map_write`, `prog_load` etc.) is going to help.

**Comment by davidnuzik** [comment] 2021-07-13 18:43
@vadorovsky to create github issues to track 1.21 and 1.20 backports as well.

**Comment by vadorovsky** [comment] 2021-07-14 13:00
The issue seems to be not only about BPF. I made a following change to our policy which:

* allows Super Privileged Containers to load BPF programs and access BPF maps
* allows iptables to access /sys/fs/cgroups

```diff
diff --git a/policy/centos7/rke2.te b/policy/centos7/rke2.te
index acb021a..6da6bc4 100644
--- a/policy/centos7/rke2.te
+++ b/policy/centos7/rke2.te
@@ -1,7 +1,8 @@
 policy_module(rke2, 1.0.0)
 
 gen_require(`
-    type container_runtime_t, unconfined_service_t;
+    type container_runtime_t, iptables_t, spc_t, unconfined_service_t;
+    class bpf { map_create map_read map_write prog_load prog_run };
 ')
 rke2_filetrans_named_content(container_runtime_t)
 rke2_filetrans_named_content(unconfined_service_t)
@@ -19,3 +20,13 @@ rke2_service_domain_template(rke2_service_db)
 container_manage_lib_dirs(rke2_service_db_t)
 container_manage_lib_files(rke2_service_db_t)
 allow rke2_service_db_t container_var_lib_t:file { map };
+
+###################
+# type iptables_t #
+###################
+fs_list_cgroup_dirs(iptables_t)
+
+##############
+# type spc_t #
+##############
+allow spc_t self:bpf { map_create map_read map_write prog_load prog_run };
```

After this change, all pods are running:

```
[root@server bin]# ./kubectl get pods -A
NAMESPACE     NAME                                         READY   STATUS      RESTARTS   AGE
cilium-test   client-7b7bf54b85-wd8kd                      1/1     Running     0          72s
cilium-test   client2-666976c95b-j866g                     1/1     Running     0          72s
cilium-test   echo-same-node-745bd5c77-dg8jl               1/1     Running     0          72s
kube-system   cilium-operator-654475f44c-hjdgj             1/1     Running     0          5m45s
kube-system   cilium-z6hxg                                 1/1     Running     0          5m46s
kube-system   etcd-server.local                            1/1     Running     8          26m
kube-system   helm-install-rke2-coredns-zh28d              0/1     Completed   0          27m
kube-system   helm-install-rke2-ingress-nginx-d5jqt        0/1     Completed   0          5m15s
kube-system   helm-install-rke2-kube-proxy-8rtjr           0/1     Completed   0          27m
kube-system   helm-install-rke2-metrics-server-qzjhz       0/1     Completed   0          5m15s
kube-system   kube-apiserver-server.local                  1/1     Running     8          26m
kube-system   kube-controller-manager-server.local         1/1     Running     8          27m
kube-system   kube-proxy-stl5j                             1/1     Running     1          27m
kube-system   kube-scheduler-server.local                  1/1     Running     8          27m
kube-system   rke2-coredns-rke2-coredns-65d668ddf9-f2w2r   1/1     Running     0          5m15s
kube-system   rke2-ingress-nginx-controller-dbdd2          1/1     Running     0          4m52s
kube-system   rke2-metrics-server-6647ffc866-rpb78         1/1     Running     0          5m1s
```

But when doing the connectivity test, kube-dns doesn't seem to work properly:

```
[root@server bin]# /usr/local/bin/cilium connectivity test
ℹ️  Single-node environment detected, enabling single-node connectivity test
ℹ️  Monitor aggregation detected, will skip some flow validation steps
✨ [default] Creating namespace for connectivity check...
✨ [default] Deploying echo-same-node service...
✨ [default] Deploying same-node deployment...
✨ [default] Deploying client deployment...
✨ [default] Deploying client2 deployment...
⌛ [default] Waiting for deployments [client client2 echo-same-node] to become ready...
⌛ [default] Waiting for deployments [] to become ready...
⌛ [default] Waiting for CiliumEndpoint for pod cilium-test/client-7b7bf54b85-wd8kd to appear...
⌛ [default] Waiting for CiliumEndpoint for pod cilium-test/client2-666976c95b-j866g to appear...
⌛ [default] Waiting for CiliumEndpoint for pod cilium-test/echo-same-node-745bd5c77-dg8jl to appear...
⌛ [default] Waiting for Service cilium-test/echo-same-node to become ready...
⌛ [default] Waiting for NodePort 192.168.121.165:32428 (cilium-test/echo-same-node) to become ready...
⌛ [default] Waiting for Cilium pod kube-system/cilium-z6hxg to have all the pod IPs in eBPF ipcache...
⌛ [default] Waiting for pod cilium-test/client-7b7bf54b85-wd8kd to reach kube-dns service...
```

**Comment by rancher-max** [comment] 2021-08-14 03:28
Since this change is only for rke2-selinux package, I am closing it out as validated since it has been confirmed on the `testing` channel.

**Closed by rancher-max** 2021-08-14 03:28 UTC
