### ISSUE TITLE
Three node RKE2 cluster - kubectl on secondary nodes needs 15 seconds for response

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rke2#730] opened 2021-02-25 06:52 UTC
Just deployed new 3 node RKE2 clusters (just servers - no agents).

When I use kubectl on the first node - it works instant.
When I use kubectl on node 2 or node 3 - I have a 15 second "hang" before it responds.

I am using local kubectl with /etc/rancher/rke2/rke2.yaml so against 127.0.0.1 and all PODs are up and running well (also the three ETCD pods)

The problem also persists after waiting a day or so..

Any idea what might be going wrong?

**Comment by Martin-Weiss** [comment] 2021-03-02 06:18
> 
> 
> What is the underlying operating system being used? What version of RKE2 are you performing this testing with?

SLES 15 SP2 with latest patches

rke2 version v1.19.7+rke2r1 (d1430ad44dc162f15a54d093439c20ffb91f559b)
go version go1.15.5b5

**Comment by Oats87** [comment] 2021-03-02 23:50
@Martin-Weiss is there anything special about your environment? I'm unable to reproduce this on a 3 node RKE2 cluster running on SLES 15 SP2, where each node is a "server" node.

**Comment by Martin-Weiss** [comment] 2021-03-03 07:04
> 
> 
> @Martin-Weiss is there anything special about your environment? I'm unable to reproduce this on a 3 node RKE2 cluster running on SLES 15 SP2, where each node is a "server" node.

I do not think that I have anything special in my environment - and I see the same problem on ALL the clusters I deployed with RKE2. So maybe I am the "special" thing, here ;-).

I can give you access to one of my clusters in case you send me your public ssh key via PN..

**Comment by Oats87** [comment] 2021-03-03 17:49
Initial investigation of this issue reveals that `kubectl` is exceeding context deadlines when performing a `kubectl get pod -A`, as it is attempting to query the metrics API and is receiving `503` responses.

```
> kubectl -v=9 get pod -A -o wide
I0303 18:44:40.225342   13979 loader.go:375] Config loaded from file:  /etc/rancher/rke2/rke2.yaml
I0303 18:44:40.236861   13979 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.17.2 (linux/amd64) kubernetes/59603c6" 'https://127.0.0.1:6443/apis/metrics.k8s.io/v1beta1?timeout=32s'
I0303 18:44:45.243652   13979 round_trippers.go:443] GET https://127.0.0.1:6443/apis/metrics.k8s.io/v1beta1?timeout=32s 503 Service Unavailable in 5006 milliseconds
I0303 18:44:45.243675   13979 round_trippers.go:449] Response Headers:
I0303 18:44:45.243680   13979 round_trippers.go:452]     Cache-Control: no-cache, private
I0303 18:44:45.243683   13979 round_trippers.go:452]     Content-Type: text/plain; charset=utf-8
I0303 18:44:45.243686   13979 round_trippers.go:452]     X-Content-Type-Options: nosniff
I0303 18:44:45.243689   13979 round_trippers.go:452]     Content-Length: 57
I0303 18:44:45.243691   13979 round_trippers.go:452]     Date: Wed, 03 Mar 2021 17:44:45 GMT
I0303 18:44:45.246162   13979 request.go:1017] Response Body: error trying to reach service: context deadline exceeded
I0303 18:44:45.247868   13979 request.go:1220] body was not decodable (unable to check for Status): Object 'Kind' is missing in 'error trying to reach service: context deadline exceeded
'
I0303 18:44:45.247914   13979 cached_discovery.go:78] skipped caching discovery info due to the server is currently unable to handle the request
I0303 18:44:45.248483   13979 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.17.2 (linux/amd64) kubernetes/59603c6" 'https://127.0.0.1:6443/apis/metrics.k8s.io/v1beta1?timeout=32s'
I0303 18:44:50.252585   13979 round_trippers.go:443] GET https://127.0.0.1:6443/apis/metrics.k8s.io/v1beta1?timeout=32s 503 Service Unavailable in 5004 milliseconds
I0303 18:44:50.252622   13979 round_trippers.go:449] Response Headers:
I0303 18:44:50.252627   13979 round_trippers.go:452]     Cache-Control: no-cache, private
I0303 18:44:50.252631   13979 round_trippers.go:452]     Content-Type: text/plain; charset=utf-8
I0303 18:44:50.252633   13979 round_trippers.go:452]     X-Content-Type-Options: nosniff
I0303 18:44:50.252636   13979 round_trippers.go:452]     Content-Length: 71
I0303 18:44:50.252639   13979 round_trippers.go:452]     Date: Wed, 03 Mar 2021 17:44:50 GMT
I0303 18:44:50.256288   13979 request.go:1017] Response Body: error trying to reach service: dial tcp 10.43.133.226:443: i/o timeout
I0303 18:44:50.258495   13979 request.go:1220] body was not decodable (unable to check for Status): yaml: mapping values are not allowed in this context
I0303 18:44:50.258539   13979 cached_discovery.go:78] skipped caching discovery info due to the server is currently unable to handle the request
I0303 18:44:50.258580   13979 shortcut.go:89] Error loading discovery information: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
I0303 18:44:50.258952   13979 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.17.2 (linux/amd64) kubernetes/59603c6" 'https://127.0.0.1:6443/apis/metrics.k8s.io/v1beta1?timeout=32s'
I0303 18:44:55.262245   13979 round_trippers.go:443] GET https://127.0.0.1:6443/apis/metrics.k8s.io/v1beta1?timeout=32s 503 Service Unavailable in 5003 milliseconds
I0303 18:44:55.262274   13979 round_trippers.go:449] Response Headers:
I0303 18:44:55.262279   13979 round_trippers.go:452]     Content-Length: 57
I0303 18:44:55.262282   13979 round_trippers.go:452]     Date: Wed, 03 Mar 2021 17:44:55 GMT
I0303 18:44:55.262285   13979 round_trippers.go:452]     Cache-Control: no-cache, private
I0303 18:44:55.262288   13979 round_trippers.go:452]     Content-Type: text/plain; charset=utf-8
I0303 18:44:55.262291   13979 round_trippers.go:452]     X-Content-Type-Options: nosniff
I0303 18:44:55.269335   13979 request.go:1017] Response Body: error trying to reach service: context deadline exceeded
I0303 18:44:55.273914   13979 request.go:1220] body was not decodable (unable to check for Status): Object 'Kind' is missing in 'error trying to reach service: context deadline exceeded
'
I0303 18:44:55.273948   13979 cached_discovery.go:78] skipped caching discovery info due to the server is currently unable to handle the request
I0303 18:44:55.281079   13979 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json;as=Table;v=v1beta1;g=meta.k8s.io, application/json" -H "User-Agent: kubectl/v1.17.2 (linux/amd64) kubernetes/59603c6" 'https://127.0.0.1:6443/api/v1/pods?limit=500'
I0303 18:44:55.312328   13979 round_trippers.go:443] GET https://127.0.0.1:6443/api/v1/pods?limit=500 200 OK in 30 milliseconds
I0303 18:44:55.312368   13979 round_trippers.go:449] Response Headers:
I0303 18:44:55.312373   13979 round_trippers.go:452]     Cache-Control: no-cache, private
I0303 18:44:55.312377   13979 round_trippers.go:452]     Content-Type: application/json
I0303 18:44:55.312380   13979 round_trippers.go:452]     Vary: Accept-Encoding
I0303 18:44:55.312382   13979 round_trippers.go:452]     Date: Wed, 03 Mar 2021 17:44:55 GMT
I0303 18:44:55.313807   13979 request.go:1017] Response Body: <redacted>
```

This cluster has the `cis-1.5` profile enabled, and as such, this looks directly related to: https://github.com/rancher/rke2/issues/745

**Comment by Oats87** [comment] 2021-03-03 17:54
I am going to close this issue in favor of https://github.com/rancher/rke2/issues/745 which is the root cause of this problem.

**Closed by Oats87** 2021-03-03 17:54 UTC
