### ISSUE TITLE
[process][feature] build-time ability to assert correct goboring static linkage

### ISSUE THREAD

**Issue by dweomer** [rancher/rke2#344] opened 2020-09-21 20:42 UTC
As part of the work for rancher/rke2#335 I have hacked together two small scripts for asserting that our executables are statically linked and have goboring symbols, e.g. https://github.com/rancher/image-build-runc/blob/cb9f9a4a4a5417d4838df30c75b3d40c4269e1a0/Dockerfile#L20-L30:
```dockerfile
# build statically linked executables
RUN BUILDTAGS='seccomp selinux apparmor' make static
# assert statically linked executables
RUN echo '[ -e $1 ] && (file $1 | grep -E "executable, x86-64, .*, statically linked")' >> ./assert-static
RUN sh -ex ./assert-static runc
# assert goboring symbols
RUN echo '[ -e $1 ] && (go tool nm $1 | grep Cfunc__goboring > .boring; if [ $(wc -l <.boring) -eq 0 ]; then exit 1; fi)' \
    >> ./assert-boring
RUN sh -ex ./assert-boring runc
# install (with strip) to /usr/local/bin
RUN install -s runc /usr/local/bin
```
This works fine for executables that we can know, a piori, will be linked to goboring (stdlib crypto or tls references) but It would give us flexibility to have a CLI tool that we can make assertions for any statically-linked binary, prior to symbol stripping, that will see tls or crypto references and only under such conditions require the presence of the `*_Cfunc__goboringcrypto_*` symbols.

See:
- https://kupczynski.info/2019/12/15/fips-golang.html#build-process
- https://godoc.org/debug/elf

**Comment by cjellick** [comment] 2020-09-21 20:47
_googles "a piori"_

**Comment by davidnuzik** [comment] 2021-01-05 17:42
This is effectively a duplicate of https://github.com/rancher/rke2/issues/555 and has already been tested and approved by QA. Closing this issue. Reference the #555 issue for details.

**Closed by davidnuzik** 2021-01-05 17:42 UTC
Labels: [zube]: To Test, kind/todo
