### ISSUE TITLE
Request apiserver failed after deleting one of the master nodes

### ISSUE THREAD

**Issue by yaocw2020** [rancher/rke2#1959] opened 2021-10-15 03:14 UTC
**Environmental Info:**
RKE2 Version: 

```
rke2 version v1.21.5+rke2r2 (9e4acdc6018ae74c36523c99af25ab861f3884da)
go version go1.16.6b7

CNI: canal
kube-proxy: iptables mode
```

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

After deleting the master node, some pods will fail to request the apiserver because TCP Conntrack entries remain stale.

**Additional context / logs:**

Related Kubernetes issue: https://github.com/kubernetes/kubernetes/issues/101607

**Comment by brandond** [comment] 2021-10-15 04:30
Do we need a tracking issue here if it's an upstream issue? Is there some action needed on our side?

**Comment by gitlawr** [comment] 2021-10-18 02:59
I believe it is related to the way rke2 runs apiservers. It does not happen in K3S.
Given that this is critical to RKE2 clusters, do you think we can mitigate the problem from RKE2 side?

**Comment by cjellick** [comment] 2021-10-19 21:55
@gitlawr any chance you can spin up rancher 2.5.x, provision an rke1 cluster and see if it repros there? Im just curious

**Comment by cjellick** [comment] 2021-10-19 22:09
@gitlawr can you expand on this:
> Delete the node that has the most contrack table entries.

What do you mean by "delete the node"? Is that `kubectl delete node` or delete the vm from aws or something else?

**Comment by brandond** [comment] 2021-10-20 00:55
In my case I left the node running. I'll see if stopping the service first and/or shutting down the node makes a difference.

**Comment by brandond** [comment] 2021-10-20 06:18
Just deleting the static pod manifests on the deleted node seems to fix things. Having RKE2 do this when it detects an etcd tombstone file might be a suitable workaround, although this relies on RKE2 being online and working in order to create the tombstone file, which makes it not a completely reliable fix for this issue.

It takes a moment for the kubelet to properly tear down all the static pods, and there are a bunch of errors, but it does eventually work. The orphaned workload pods keep running, which probably isn't great, but having at least the control-plane static pods gone seems to allow the rest of the cluster to function properly.

```console
root@ubuntu01:~# crictl ps
CONTAINER           IMAGE               CREATED             STATE               NAME                            ATTEMPT             POD ID
be874f5df2911       7589738b9ae11       8 minutes ago       Running             coredns                         0                   51fe4a0225e70
0617a01f36c1b       69bca36d82432       10 minutes ago      Running             system-upgrade-controller       0                   b1b86b8c964c4
823fedd51bc58       fffb9e128464f       11 minutes ago      Running             rke2-ingress-nginx-controller   0                   c6e0f890aec1e
562cd351c4d66       5aa19aa313a9b       11 minutes ago      Running             autoscaler                      0                   38ae6953af279
eb1f8f504028f       5d05c5a9b5533       11 minutes ago      Running             metrics-server                  0                   bf0b479512a93
a01a196e9e3de       779aa7e4e93c4       11 minutes ago      Running             calico-kube-controllers         0                   d00e845585510
d8a7f3e37f4b1       7aa1277761b51       12 minutes ago      Running             calico-node                     0                   5baff999b7194
177d08dfd84c6       855764fd09700       12 minutes ago      Running             calico-typha                    0                   c7e0a6d85e750
```

```console
NAMESPACE             NAME                                                              READY   STATUS      RESTARTS   AGE     IP            NODE                 NOMINATED NODE   READINESS GATES
calico-system         calico-kube-controllers-748bcb7bb-qgrhv                           1/1     Running     2          7m32s   10.42.173.4   ubuntu03.lan.khaus   <none>           <none>
calico-system         calico-node-2x6ck                                                 1/1     Running     0          14m     10.0.1.169    ubuntu02.lan.khaus   <none>           <none>
calico-system         calico-node-67fl4                                                 1/1     Running     0          13m     10.0.1.231    ubuntu03.lan.khaus   <none>           <none>
calico-system         calico-typha-6d8579c696-847z4                                     1/1     Running     0          14m     10.0.1.169    ubuntu02.lan.khaus   <none>           <none>
calico-system         calico-typha-6d8579c696-lk52v                                     1/1     Running     0          7m32s   10.0.1.231    ubuntu03.lan.khaus   <none>           <none>
cattle-fleet-system   fleet-agent-6f5c7cfdbc-2gr6s                                      1/1     Running     0          7m32s   10.42.213.3   ubuntu02.lan.khaus   <none>           <none>
cattle-system         apply-system-agent-upgrader-on-ubuntu02.lan.khaus-with-61-vm9n6   0/1     Completed   0          14m     10.0.1.169    ubuntu02.lan.khaus   <none>           <none>
cattle-system         apply-system-agent-upgrader-on-ubuntu03.lan.khaus-with-61-r7q56   0/1     Completed   0          13m     10.0.1.231    ubuntu03.lan.khaus   <none>           <none>
cattle-system         cattle-cluster-agent-7494849-9cmqm                                1/1     Running     2          7m32s   10.42.213.4   ubuntu02.lan.khaus   <none>           <none>
cattle-system         cattle-cluster-agent-7494849-ljx2s                                1/1     Running     2          7m32s   10.42.173.5   ubuntu03.lan.khaus   <none>           <none>
cattle-system         system-upgrade-controller-679575c7b4-6sd9v                        1/1     Running     1          7m32s   10.42.173.2   ubuntu03.lan.khaus   <none>           <none>
kube-system           cloud-controller-manager-ubuntu02.lan.khaus                       1/1     Running     0          14m     10.0.1.169    ubuntu02.lan.khaus   <none>           <none>
kube-system           cloud-controller-manager-ubuntu03.lan.khaus                       1/1     Running     0          13m     10.0.1.231    ubuntu03.lan.khaus   <none>           <none>
kube-system           etcd-ubuntu02.lan.khaus                                           1/1     Running     0          13m     10.0.1.169    ubuntu02.lan.khaus   <none>           <none>
kube-system           etcd-ubuntu03.lan.khaus                                           1/1     Running     0          12m     10.0.1.231    ubuntu03.lan.khaus   <none>           <none>
kube-system           kube-apiserver-ubuntu02.lan.khaus                                 1/1     Running     0          13m     10.0.1.169    ubuntu02.lan.khaus   <none>           <none>
kube-system           kube-apiserver-ubuntu03.lan.khaus                                 1/1     Running     0          12m     10.0.1.231    ubuntu03.lan.khaus   <none>           <none>
kube-system           kube-controller-manager-ubuntu02.lan.khaus                        1/1     Running     0          14m     10.0.1.169    ubuntu02.lan.khaus   <none>           <none>
kube-system           kube-controller-manager-ubuntu03.lan.khaus                        1/1     Running     0          13m     10.0.1.231    ubuntu03.lan.khaus   <none>           <none>
kube-system           kube-proxy-ubuntu02.lan.khaus                                     1/1     Running     0          14m     10.0.1.169    ubuntu02.lan.khaus   <none>           <none>
kube-system           kube-proxy-ubuntu03.lan.khaus                                     1/1     Running     0          13m     10.0.1.231    ubuntu03.lan.khaus   <none>           <none>
kube-system           kube-scheduler-ubuntu02.lan.khaus                                 1/1     Running     0          14m     10.0.1.169    ubuntu02.lan.khaus   <none>           <none>
kube-system           kube-scheduler-ubuntu03.lan.khaus                                 1/1     Running     0          13m     10.0.1.231    ubuntu03.lan.khaus   <none>           <none>
kube-system           rke2-coredns-rke2-coredns-7bb4f446c-4xdsr                         1/1     Running     0          10m     10.42.213.1   ubuntu02.lan.khaus   <none>           <none>
kube-system           rke2-coredns-rke2-coredns-7bb4f446c-g966c                         1/1     Running     0          7m32s   10.42.173.1   ubuntu03.lan.khaus   <none>           <none>
kube-system           rke2-coredns-rke2-coredns-autoscaler-7c58bd5b6c-lwlb4             1/1     Running     1          7m32s   10.42.213.2   ubuntu02.lan.khaus   <none>           <none>
kube-system           rke2-ingress-nginx-controller-lm44m                               1/1     Running     0          12m     10.0.1.231    ubuntu03.lan.khaus   <none>           <none>
kube-system           rke2-ingress-nginx-controller-wt546                               1/1     Running     0          13m     10.0.1.169    ubuntu02.lan.khaus   <none>           <none>
kube-system           rke2-metrics-server-5df7d77b5b-v9gv7                              1/1     Running     1          7m32s   10.42.173.3   ubuntu03.lan.khaus   <none>           <none>
tigera-operator       tigera-operator-698786489c-8v946                                  1/1     Running     0          7m32s   10.0.1.169    ubuntu02.lan.khaus   <none>
```

**Comment by brandond** [comment] 2021-10-20 20:18
Yeah, that's another issue. We need some way to have the server reliably shoot itself in the head (from the old STONITH fencing metaphor) when it's deleted from the cluster.

**Comment by cwayne18** [comment] 2021-11-09 21:05
We'll still try to squeeze this into 1.22.4, but if we cannot make code freeze (Nov 10th), we do have a workaround for this (@brandond please do correct me if/when I'm wrong) -- Running rke2-killall.sh after deleting the node should work around this issue.

**Comment by brandond** [comment] 2021-11-09 22:22
Correct. The current workaround is to either run `rke2-killall.sh` on the node after deleting it from the cluster, or shut down the node entirely. It is the continued presence of the control-plane components in the cluster despite deletion of the node that causes the problem.

**Comment by cjellick** [comment] 2021-11-12 16:14
@guangbochen @yasker is this a GA blocker?

**Comment by yasker** [comment] 2021-11-24 18:38
According to @brandond , this will land in `v1.21` release as well.

**Comment by rancher-max** [comment] 2021-12-21 19:37
#### Validated on all of v1.22.5-rc2+rke2r1, v1.21.8-rc2+rke2r1, and v1.20.14-rc2+rke2r1

- Following the steps mentioned by Brad in the recreation scenario, I see the coredns pods reschedule to the remaining node successfully with no errors and the pod manifests related to the control plane on the deleted node are all removed. These include: `cloud-controller-manager.yaml`, `etcd.yaml`, `kube-apiserver.yaml`, `kube-controller-manager.yaml`, and `kube-scheduler.yaml`. The only pod not cleaned up is `kube-proxy.yaml` which is by design as it is not part of the control plane. 
- In order to rejoin this node to the cluster (if desired) operators must first completely uninstall rke2 on the node (with rke2-uninstall.sh script), then reinstall with the appropriate config arguments.

**Closed by rancher-max** 2021-12-21 19:37 UTC
Labels: area/harvester
