### ISSUE TITLE
RKE2 - Upgrade from v1.23.10 to v1.24.4 fails 

### ISSUE THREAD

**Issue by HujinoKun** [rancher/rke2#3379] opened 2022-09-24 16:47 UTC
**Environmental Info:**
RKE2 Version: 

Old : v1.23.10

The version I'm aiming for :  v1.24.4

Node(s) CPU architecture, OS, and Version: 

OS : Debian 10

Linux zeus 4.19.0-21-amd64 #1 SMP Debian 4.19.249-2 (2022-06-30) x86_64 GNU/Linux

Cluster Configuration:

mono-node

**Describe the bug:**

When I restart the rke2 service, I get the following error : 

```
Sep 24 18:29:46 zeus rke2[6728]: time="2022-09-24T18:29:46+02:00" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://162.55.171.47:9345/v1-rke2/readyz: 500 Internal Server Error"
```

**Steps To Reproduce:**

Install version v1.23.10 and try to upgrade to v1.24.4

**Expected behavior:**

I wish I was on version 1.24 of Kubernetes :)

**Additional context / logs:**

```
Sep 24 18:29:29 zeus rke2[6728]: time="2022-09-24T18:29:29+02:00" level=info msg="Latest etcd manifest deployed"
Sep 24 18:29:29 zeus rke2[6728]: time="2022-09-24T18:29:29+02:00" level=info msg="kube-apiserver pod not found, retrying"
Sep 24 18:29:31 zeus rke2[6728]: time="2022-09-24T18:29:31+02:00" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://162.55.171.47:9345/v1-rke2/readyz: 500 Internal Server Error"
Sep 24 18:29:36 zeus rke2[6728]: time="2022-09-24T18:29:36+02:00" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://162.55.171.47:9345/v1-rke2/readyz: 500 Internal Server Error"
Sep 24 18:29:39 zeus rke2[6728]: time="2022-09-24T18:29:39+02:00" level=info msg="Waiting for API server to become available"
Sep 24 18:29:39 zeus rke2[6728]: time="2022-09-24T18:29:39+02:00" level=info msg="Waiting for API server to become available"
Sep 24 18:29:41 zeus rke2[6728]: time="2022-09-24T18:29:41+02:00" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://162.55.171.47:9345/v1-rke2/readyz: 500 Internal Server Error"
Sep 24 18:29:46 zeus rke2[6728]: time="2022-09-24T18:29:46+02:00" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://162.55.171.47:9345/v1-rke2/readyz: 500 Internal Server Error"
Sep 24 18:29:49 zeus rke2[6728]: time="2022-09-24T18:29:49+02:00" level=info msg="Latest etcd manifest deployed"
Sep 24 18:29:49 zeus rke2[6728]: time="2022-09-24T18:29:49+02:00" level=info msg="kube-apiserver pod not found, retrying"
Sep 24 18:32:17 zeus rke2[8756]: Flag --pod-infra-container-image has been deprecated, will be removed in 1.27. Image garbage collector will get sandbox image information from CRI.  
Sep 24 18:32:17 zeus rke2[8756]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 24 18:32:17 zeus rke2[8756]: Flag --read-only-port has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 24 18:32:17 zeus rke2[8756]: Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 24 18:32:17 zeus rke2[8756]: Flag --serialize-image-pulls has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 24 18:32:17 zeus rke2[8756]: Flag --stderrthreshold has been deprecated, will be removed in a future release, see https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components
Sep 24 18:32:17 zeus rke2[8756]: Flag --tls-cert-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 24 18:32:17 zeus rke2[8756]: Flag --tls-private-key-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 24 18:32:22 zeus rke2[8756]: time="2022-09-24T18:32:22+02:00" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://162.55.171.47:9345/v1-rke2/readyz: 500 Internal Server Error"
Sep 24 18:32:27 zeus rke2[8756]: time="2022-09-24T18:32:27+02:00" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://162.55.171.47:9345/v1-rke2/readyz: 500 Internal Server Error"
Sep 24 18:32:32 zeus rke2[8756]: time="2022-09-24T18:32:32+02:00" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://162.55.171.47:9345/v1-rke2/readyz: 500 Internal Server Error"
```

The RKE2 documentation doesn't indicate anything about the version mounts.

**Comment by brandond** [comment] 2022-09-26 01:30
`Sep 24 18:29:49 zeus rke2[6728]: time="2022-09-24T18:29:49+02:00" level=info msg="kube-apiserver pod not found, retrying"`

This is the root cause of your other errors. Check the kubelet and containerd logs to see why the apiserver pod is not running.

**Comment by HujinoKun** [comment] 2022-09-26 18:39
shouldn't the static pod be changed automatically?

I will try again to upgrade soon

**Comment by HujinoKun** [comment] 2022-10-15 21:14
I deleted the static pods, restart the installation script. Still errors.

In the logs, nothing that describes the problem

**Comment by HujinoKun** [comment] 2022-10-15 21:15
On the other hand, small bug kube-proxy does not deploy via the script while kube-api resets itself to the right place

**Comment by brandond** [comment] 2022-10-16 02:09
Please attach logs from rke2-server, containerd, and kubelet.

**Comment by xhejtman** [comment] 2022-10-23 10:02
Hello, the same happens for me. Logs attached. I saw problems with upgrading control plane nodes:
[logs.zip](https://github.com/rancher/rke2/files/9846200/logs.zip) (the logs are when upgrading 1.24.2 -> 1.24.7, system is ubuntu 22.04, but the same happens (1.21.11 -> 1.21.14) on ubuntu 20.04.

* 1.21.11 -> 1.21.14 does not work (seems that kube-proxy is not starting)
* 1.21.11 -> 1.21.13 works ok 
* 1.21.11 -> 1.22.9 works
* 1.21.11->1.22.13 does not work (problem here appears to be same as in the all following cases)
* 1.22.9 -> 1.23.9 works
* 1.22.9 -> 1.23.12 does not work
* 1.23.9 -> 1.24.2 works
* 1.23.9 -> 1.24.4 does not work
* 1.24.2 -> 1.24.4 does not work
* 1.24.2 -> 1.24.7 does not work.

each upgrade has been done via service rke2-server restart and only final versions of rke2 release have been used.

**Comment by brandond** [comment] 2022-10-24 20:15
@xhejtman you appear to be running into several issues. You didn't say which version you're on, but the logs suggest `v1.24.7+rke2r1. 

> `time="2022-10-23T11:51:01.110351928+02:00" level=error msg="StopPodSandbox for \"a6871761968259fa80e113e05689aa927de4b1b9d51c9baebebf4779f25e74c2\" failed" error="failed to destroy network for sandbox \"a6871761968259fa80e113e05689aa927de4b1b9d51c9baebebf4779f25e74c2\": plugin type=\"calico\" failed (delete): error getting ClusterInformation: connection is unauthorized: Unauthorized"`

This is https://github.com/rancher/rke2/issues/3425 which was fixed by https://github.com/rancher/rke2/issues/3429. Please confirm that all of your server nodes have been upgraded to v1.24.7+rke2r1. `kubectl get node -o wide` and `kubectl get helmchart -n kube-system rke2-calico` would confirm that you've upgraded successfully.

> `E1023 11:50:49.895428   35727 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"02570032-e9fd-4e8e-9e4e-5619725dd335\" found, but error occurred when trying to remove the volumes dir: not a directory" numErrs=14`

This is an upstream issue: https://github.com/kubernetes/kubernetes/issues/105536. You may need to manually clean up the orphaned pod directories manually.

**Comment by xhejtman** [comment] 2022-10-24 20:17
Right now I am at 1.24.2 and the logs were from attemtps to upgrade from 1.24.2 to 1.24.7. I think I tried also upgrade to 1.24.4 first but the same result. Node is not operational. 

So, are you suggesting to try to upgrade all nodes to 1.24.7 at once and not one-by-one?

**Comment by brandond** [comment] 2022-10-24 20:18
You're not upgrading the agents before the servers, are you?

**Comment by xhejtman** [comment] 2022-10-24 20:20
Nope, as I have server-only cluster (3 nodes, all being control plane and running rancher only)

**Comment by xhejtman** [comment] 2022-10-24 20:24
so, right now, I have 3-node cluster, all nodes are server nodes. All nodes are running 1.24.2 version and it seems to be ok and operational. If I try upgrade one of the server node to 1.24.4 or 1.24.7, it fails as in logs above. etcd starts but it is stopped after while. 

Perhaps, upgrading cni is the issue? I saw a problem with helm rke2 calico job:
as soon as I upgraded *one* node, it started calico upgrade job that unfortunately stared on *not-upgraded* node and failed about wrong k8s version. So I reverted rke2 version and next time, I tried to start with the node that wants to run helm upgrade job, but result was the same - non operational node.

**Comment by brandond** [comment] 2022-10-24 20:25
Upgrading to a fixed release will resolve the calico issue. For the other problem, I would read through the upstream issue, but as I mentioned above you will probably have to do some manual cleanup of the orphaned mount points under `/var/lib/pods/<pod-id>`

> as soon as I upgraded one node, it started calico upgrade job that unfortunately stared on not-upgraded node and failed about wrong k8s version.

Yes. You're intended to finish the upgrade. The helm job will succeed when it runs on a node that has been upgraded. Just finish upgrading all the servers and let it figure itself out.

**Comment by xhejtman** [comment] 2022-10-24 20:29
> Upgrading to a fixed release will resolve the calico issue. 

meaning, I should upgrade all 3 nodes and do not wait, until a first upgraded node is ok? i.e., just run `service rke2-server restart` on all nodes and it should reconcile?

**Comment by brandond** [comment] 2022-10-24 20:31
Yes. If you're just replacing the binary, do that then restart the service, on all three nodes.

**Comment by xhejtman** [comment] 2022-10-24 20:36
Do you believe that orphaned pods are more than just warning? I think I see those messages under normal operations.

**Comment by xhejtman** [comment] 2022-10-24 20:36
But thanks anyway, will do as you suggest.

**Comment by brandond** [comment] 2022-10-24 20:46
No, the orphaned pods indicate that it's failing to clean up the filesystem for some reason, usually because there's a stale mount point. It's not optimal, and may cause the kubelet to take longer than usual to start new pods or perform other cleanup operations.

**Comment by xhejtman** [comment] 2022-10-24 22:23
Unfortunately, restart rke2-server on all nodes didn't work. node1 is constantly failing to run api. Logs attached.
[logs.zip](https://github.com/rancher/rke2/files/9855741/logs.zip)

**Comment by brandond** [comment] 2022-10-25 00:47
This will be disruptive to the workload, but probably no more disruptive than your current state - run `rke2-killall.sh` on all the nodes, then start the rke2-server service.

**Comment by xhejtman** [comment] 2022-10-25 00:54
I can reboot the nodes without problem. Would it be enough?

**Comment by brandond** [comment] 2022-10-25 01:10
I don't believe that rebooting will fix the orphaned pod dirs, but it probably wouldn't hurt.

**Comment by xhejtman** [comment] 2022-10-25 14:40
So, I found that I have test cluster with 1.24.2 k8s version (RKE2). I tried to upgrade here as it makes no harm if it fails. And it failed.

I tried `./rke2-killall.sh` as you suggested, `service rke2-server start`, but cluster will not boot up. I think the real problem is, that primary node (the one that does not have `server` in `rke2.config` won't start and the other nodes are unable to join. 

I also tried to stop `rke2-server` on all nodes, reboot, still the same. Primary node won't start completely.

**Comment by xhejtman** [comment] 2022-10-25 21:04
I tried to do cluster-reset and start with a single node of the former cluster. Still no luck. I see strange messages in kubeapi logs:
`2022-10-25T23:01:07.823828827+02:00 stderr F E1025 21:01:07.823780       1 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, service account token has been invalidated]"`

**Comment by xhejtman** [comment] 2022-10-25 23:08
I found that if I just run rke2 server instead of service rke2-server start, it works! Any idea what could be wrong?

**Comment by brandond** [comment] 2022-10-25 23:11
Have you perhaps added some CLI flags to the systemd unit that are causing problems?

**Comment by xhejtman** [comment] 2022-10-25 23:14
I added this:
`LimitMEMLOCK=infinity`
and it actually seems to be suspect. But that's quite strange as it should not break things..

**Comment by xhejtman** [comment] 2022-10-25 23:19
Ah, no, it is not. It still works only running `rke2 server`. Whole systemd unit looks like:
```
[Unit]
Description=Rancher Kubernetes Engine v2 (server)
Documentation=https://github.com/rancher/rke2#readme
Wants=network-online.target
After=network-online.target
Conflicts=rke2-agent.service

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=-/etc/default/%N
EnvironmentFile=-/etc/sysconfig/%N
EnvironmentFile=-/usr/lib/systemd/system/%N.env
KillMode=process
Delegate=yes
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=/bin/sh -xc '! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service'
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/bin/rke2 server
ExecStopPost=-/bin/sh -c "systemd-cgls /system.slice/%n | grep -Eo '[0-9]+ (containerd|kubelet)' | awk '{print $1}' | xargs -r kill"
```

**Comment by brandond** [comment] 2022-10-25 23:39
Do you by some chance have multiple `rke2` binaries on the host? What do you get from `rke2 --version` vs `/usr/bin/rke2 --version` ?

**Comment by xhejtman** [comment] 2022-10-25 23:53
```root@kub-b12:/usr/bin# /usr/bin/rke2 --version
rke2 version v1.24.7+rke2r1 (5fd5150f752a663efa16ac3ae2aac5d6bba6c364)
go version go1.18.1b7
root@kub-b12:/usr/bin# rke2 --version
rke2 version v1.24.7+rke2r1 (5fd5150f752a663efa16ac3ae2aac5d6bba6c364)
go version go1.18.1b7
root@kub-b12:/usr/bin#
```

btw, it seems that `etcd` just stops after a while.

**Comment by brandond** [comment] 2022-10-26 01:31
> it seems that etcd just stops after a while.

Can you attach the etcd pod logs from /var/log/pods?

**Comment by xhejtman** [comment] 2022-10-26 07:19
[269.log](https://github.com/rancher/rke2/files/9867078/269.log)
[266.log](https://github.com/rancher/rke2/files/9867079/266.log)
[265.log](https://github.com/rancher/rke2/files/9867080/265.log)

265 and 266 are when starting via systemd. 269 is when starting as `rke2 server`. I see the problem with a certificate, but it does not seem to be problem when starting as `rke2 server`.

**Comment by xhejtman** [comment] 2022-10-26 09:29
[2.log](https://github.com/rancher/rke2/files/9868079/2.log)
[0.log](https://github.com/rancher/rke2/files/9868081/0.log)
[6.log](https://github.com/rancher/rke2/files/9868082/6.log)
[5.log](https://github.com/rancher/rke2/files/9868083/5.log)
[1.log](https://github.com/rancher/rke2/files/9868084/1.log)

These are logs (0.log, 1.log) from the case:
`rke2 server --cluster-reset`
`rke2 server`

at this point, cluster seems to be ok and stable.

then I did `ctrl-c` to stop `rke2 server` and did `service rke2-server start`. 2.log, 5.log, 6.log, etcd keeps restarting and it seems to me, that etcd is the first one who stops. `kubeapi-server` and other kube components follow to crash but without etcd it is obvious.

**Comment by xhejtman** [comment] 2022-10-27 21:32
Hello,

I finally found the root cause. Because of gpu-operator that wants to add nvidia runtime into containerd config.toml that is always (re)generated by rke2, we used config.toml.tmpl. Older version of rke used:
```
[plugins.cri.containerd.runtimes.runc.options]
        SystemdCgroup = false
```

once the config.toml.tmpl exists, it gets never updated, even on rke upgrades. And latest versions of rke require:
```
[plugins.cri.containerd.runtimes.runc.options]
        SystemdCgroup = true
```

unfortunetely, even omitting this options leads to crashes. We have another cluster, that did not set `SystemdCgroup=false`, the option was missing at all and it was wrong as well.

So as soon as I removed config.toml.tmpl, upgrade works as expected.

Perhaps rke2 should stop and blame such config if some hard-required option has wrong value?

**Comment by brandond** [comment] 2022-10-27 22:27
> Perhaps rke2 should stop and blame such config if some hard-required option has wrong value?

We don't actually parse the config file; we just template our configuration into it and then point containerd at it, but we do expect users to keep the template up-to-date with RKE2 if they customize it themselves. I'm not sure how we could effectively warn users if their template has drifted from what we provide, but maybe we could print a warning when a user-provided template is in use.

**Comment by brandond** [comment] 2023-07-19 21:21
Closing as expected - if users provide their own containerd config template, they are expected to keep it up to date when upgrading RKE2.

**Closed by brandond** 2023-07-19 21:21 UTC
