### ISSUE TITLE
No coredns autoscaler in rke2?

### ISSUE THREAD

**Issue by jonaz** [rancher/rke2#879] opened 2021-04-14 06:14 UTC
In rke we had the coredns autoscaler which left us with 5 instances of coredns in production. 

This seems missing in rke2?  We get arround 9k RPS ( sum(rate(coredns_dns_request_count_total[5m])) )  to coredns in rke and think we need it autoscaled in rke2 aswell before moving rke2 into production.

**Comment by brandond** [comment] 2021-04-14 06:58
None of the RKE2 packaged components are autoscaled.

**Comment by jonaz** [comment] 2021-04-16 06:49
Is this something that will be adressed or should we roll our own autoscaler deployment?

**Comment by brandond** [comment] 2021-04-16 08:51
We don't currently have any plans to autoscale it by default, although we could put it on the backlog if you can describe your use case.

**Comment by jonaz** [comment] 2021-04-16 11:00
If single instance coredns can handle 9000 req/sec which is what we have at the moment in old rke cluster ( `sum(rate(coredns_dns_request_count_total[5m]))` )  then there is no need for autoscale. But im pretty sure if rke2 should support big clusters it needs to autoscale it.

**Comment by Martin-Weiss** [comment] 2021-05-18 07:18
While the autoscaler should also address the "single point of failure" scenario in small deployments (do not leave replica=1 and to not run all replicas on the same host) - are there recommended values for the rke2-coredns deployment for fault tolerance / podAntiAffinity when deploying on RKE2?

**Comment by jonaz** [comment] 2021-11-14 19:00
Still relevant

**Comment by brandond** [comment] 2021-11-15 18:09
Duplicate of https://github.com/rancher/rke2/issues/1023

**Closed by brandond** 2021-11-15 18:09 UTC

**Comment by jonaz** [comment] 2021-11-15 18:39
Hmm. This was filed before the duplicate?

**Comment by brandond** [comment] 2021-11-15 18:48
#1023 was the issue opened by our Project Manager to track the work. You can follow the links from there to the PRs in which this functionality was added, back in July.
