### ISSUE TITLE
Race Condition when rotating certificates at startup

### ISSUE THREAD

**Issue by teebeey** [rancher/rke2#6064] opened 2024-05-30 15:19 UTC
**Environmental Info:**
RKE2 Version: 
```
rke2 version v1.26.13+rke2r1 (637e8a38334f603b60650b30547252a5c461fa0d)
go version go1.20.13 X:boringcrypto
```

Node(s) CPU architecture, OS, and Version: 
```
Linux <hostname> 5.14.21-150400.24.21-default #1 SMP PREEMPT_DYNAMIC Wed Sep 7 06:51:18 UTC 2022 (974d0aa) x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
3 servers, 51 agents (6 of them has this older patchlevel due to some workload-specific issues)

**Describe the bug:**
When rke2-agent was started it rotated the certificates and started the kubelet-managed kube-proxy at the same time.  On some of the nodes the kube-proxy couldn't start, probably because of the certificates missing with the following kubelet logs (grep on kube-proxy):
```
I0508 21:40:00.375374   56178 topology_manager.go:210] "Topology Admit Handler" podUID=9fdaf70d3db546ab8e2373fba6646b93 podNamespace="kube-system" podName="kube-proxy-<node>"
I0508 21:40:00.375522   56178 topology_manager.go:210] "Topology Admit Handler" podUID=1efb93492309cfae867284f6e2080687 podNamespace="kube-system" podName="kube-proxy-<node>"
E0508 21:40:00.470798   56178 kubelet.go:1802] "Failed creating a mirror pod for" err="pods \"kube-proxy-<node>\" already exists" pod="kube-system/kube-proxy-<node>"
I0508 21:40:00.470851   56178 reconciler_common.go:253] "operationExecutor.VerifyControllerAttachedVolume started for volume \"file0\" (UniqueName: \"kubernetes.io/host-path/1efb93492309cfae867284f6e2080687-file0\") pod \"kube-proxy-<node>\" (UID: \"1efb93492309cfae867284f6e2080687\") " pod="kube-system/kube-proxy-<node>"
I0508 21:40:00.470904   56178 reconciler_common.go:253] "operationExecutor.VerifyControllerAttachedVolume started for volume \"file1\" (UniqueName: \"kubernetes.io/host-path/1efb93492309cfae867284f6e2080687-file1\") pod \"kube-proxy-<node>\" (UID: \"1efb93492309cfae867284f6e2080687\") " pod="kube-system/kube-proxy-<node>"
I0508 21:40:00.470942   56178 reconciler_common.go:253] "operationExecutor.VerifyControllerAttachedVolume started for volume \"file2\" (UniqueName: \"kubernetes.io/host-path/1efb93492309cfae867284f6e2080687-file2\") pod \"kube-proxy-<node>\" (UID: \"1efb93492309cfae867284f6e2080687\") " pod="kube-system/kube-proxy-<node>"
I0508 21:40:00.471080   56178 reconciler_common.go:253] "operationExecutor.VerifyControllerAttachedVolume started for volume \"file3\" (UniqueName: \"kubernetes.io/host-path/1efb93492309cfae867284f6e2080687-file3\") pod \"kube-proxy-<node>\" (UID: \"1efb93492309cfae867284f6e2080687\") " pod="kube-system/kube-proxy-<node>"
I0508 21:40:15.726487   56802 topology_manager.go:210] "Topology Admit Handler" podUID=1efb93492309cfae867284f6e2080687 podNamespace="kube-system" podName="kube-proxy-<node>"
I0508 21:40:15.726687   56802 topology_manager.go:210] "Topology Admit Handler" podUID=5f9c06f6223f9d5ac0289da55f7dd73f podNamespace="kube-system" podName="kube-proxy-<node>"
I0508 21:40:15.776639   56802 reconciler_common.go:253] "operationExecutor.VerifyControllerAttachedVolume started for volume \"file0\" (UniqueName: \"kubernetes.io/host-path/5f9c06f6223f9d5ac0289da55f7dd73f-file0\") pod \"kube-proxy-<node>\" (UID: \"5f9c06f6223f9d5ac0289da55f7dd73f\") " pod="kube-system/kube-proxy-<node>"
I0508 21:40:15.776703   56802 reconciler_common.go:253] "operationExecutor.VerifyControllerAttachedVolume started for volume \"file1\" (UniqueName: \"kubernetes.io/host-path/5f9c06f6223f9d5ac0289da55f7dd73f-file1\") pod \"kube-proxy-<node>\" (UID: \"5f9c06f6223f9d5ac0289da55f7dd73f\") " pod="kube-system/kube-proxy-<node>"
I0508 21:40:15.776737   56802 reconciler_common.go:253] "operationExecutor.VerifyControllerAttachedVolume started for volume \"file2\" (UniqueName: \"kubernetes.io/host-path/5f9c06f6223f9d5ac0289da55f7dd73f-file2\") pod \"kube-proxy-<node>\" (UID: \"5f9c06f6223f9d5ac0289da55f7dd73f\") " pod="kube-system/kube-proxy-<node>"
I0508 21:40:15.776815   56802 reconciler_common.go:253] "operationExecutor.VerifyControllerAttachedVolume started for volume \"file3\" (UniqueName: \"kubernetes.io/host-path/5f9c06f6223f9d5ac0289da55f7dd73f-file3\") pod \"kube-proxy-<node>\" (UID: \"5f9c06f6223f9d5ac0289da55f7dd73f\") " pod="kube-system/kube-proxy-<node>"
E0508 21:40:15.781229   56802 kubelet.go:1802] "Failed creating a mirror pod for" err="pods \"kube-proxy-<node>\" already exists" pod="kube-system/kube-proxy-<node>"
E0508 21:42:18.781664   56802 kubelet.go:1821] "Unable to attach or mount volumes for pod; skipping pod" err="unmounted volumes=[file1 file2 file3 file0], unattached volumes=[file1 file2 file3 file0]: timed out waiting for the condition" pod="kube-system/kube-proxy-<node>"
E0508 21:42:18.781721   56802 pod_workers.go:965] "Error syncing pod, skipping" err="unmounted volumes=[file1 file2 file3 file0], unattached volumes=[file1 file2 file3 file0]: timed out waiting for the condition" pod="kube-system/kube-proxy-<node>" podUID=1efb93492309cfae867284f6e2080687
```
There was also no retry later on, the kube-proxy was down until I've killed and restarted the kubelet.

**Steps To Reproduce:**
Agent config:
```
server: https://<cluster-api>:9345
data-dir: /var/lib/rancher/rke2
token: <secret-token>
node-name: <node-name>
#node-taint: {}
node-label:
- node-spec.mylabel.com/hardware=virtual
- node-role.my-label.com/system=true
- node-spec.my-label.com/worker=true

kubelet-arg:
- serialize-image-pulls=true
- tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256
- event-qps=5

system-default-registry: <internal repository>
profile: cis-1.23
```
Nothing special within systemd unit or environment variables, I use a proxy.
- Installed RKE2: as a tarball

**Expected behavior:**
- kubelet is being started after the respective certificates are there
- there is a retry/reconciliation loop for the kubelet-managed pods as well which acts in such cases

**Actual behavior:**
Kube-proxy was not started until I've killed and restarted the kubelet.

**Additional context / logs:**
see logs above
The respective volumes:
```
  volumes:
  - hostPath:
      path: /var/lib/rancher/rke2/agent/client-kube-proxy.crt
      type: File
    name: file0
  - hostPath:
      path: /var/lib/rancher/rke2/agent/client-kube-proxy.key
      type: File
    name: file1
  - hostPath:
      path: /var/lib/rancher/rke2/agent/kubeproxy.kubeconfig
      type: File
    name: file2
  - hostPath:
      path: /var/lib/rancher/rke2/agent/server-ca.crt
      type: File
    name: file3
```
These files have been recreated during rke2 agent startup:
```
<hostname>:~ # ls -al /var/lib/rancher/rke2/agent/client-kube-proxy.* /var/lib/rancher/rke2/agent/kubeproxy.kubeconfig /var/lib/rancher/rke2/agent/server-ca.crt
-rw------- 1 root root 1149 May  8 21:40 /var/lib/rancher/rke2/agent/client-kube-proxy.crt
-rw------- 1 root root  227 May  8 21:40 /var/lib/rancher/rke2/agent/client-kube-proxy.key
-rw-r--r-- 1 root root  470 May  8 21:40 /var/lib/rancher/rke2/agent/kubeproxy.kubeconfig
-rw------- 1 root root  570 May  8 21:40 /var/lib/rancher/rke2/agent/server-ca.crt 
```

**Comment by brandond** [comment] 2024-05-30 16:26
This looks like a duplicate of https://github.com/rancher/rke2/issues/4864, which has been fixed on more recent releases. Kubernetes 1.26 is end of life, please update to a newer release of RKE2, which should address this issue.

**Closed by brandond** 2024-05-30 16:26 UTC
