### ISSUE TITLE
Unable to access cluster outside of the node passing tls-san in command line or through INSTALL_RKE2_EXEC as variable not present

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#258] opened 2020-08-28 19:28 UTC
Version:
rke2 version v1.18.4-beta11+rke2 (b459d18894e4f2a625e309f686cd95aa1cccf304)

Describe the issue:
Passing -tls-san in the command line during install is ignored. Unable to access cluster outside of the node

```
kubectl get nodes --kubeconfig=$HOME/.kube/config -w
Unable to connect to the server: x509: certificate is valid for kubernetes.default.svc, kubernetes.default, kubernetes, localhost, not shylaja-route53.qa.rancher.space
```
Additional info:
Using tls-san through config file can be used to access the cluster from outside node alternatively.

**Comment by cjellick** [comment] 2020-08-28 21:25
Could you give the exact command(s) your ran to reproduce this?

**Comment by ShylajaDevadiga** [comment] 2020-08-28 21:31
@cjellick Passing tls-san as flag
```
sudo INSTALL_RKE2_VERSION=v1.18.4-beta11+rke2 INSTALL_RKE2_TYPE='server' INSTALL_RKE2_METHOD='installer' ./install.sh --tls-san=IP
```
Using flags.conf
```
write-kubeconfig-mode: "0644"
tls-san:
  - IP
```

**Comment by cjellick** [comment] 2020-08-31 23:47
Since the install script refactor, this behavior intentionally just doesn't exist in the install script any more. You cannot pass arguments to the rke2 binary by putting them after `./install.sh`

Similarly, `INSTALL_RKE2_EXEC` is not supported in the new install script.

@dweomer hit on that when he demoed the changes, but it was easy to miss, I think.

The motivation here is that the install script for k3s has gotten increasingly complex over time and supports a lot of options. We want to simplify it for rke2. We don't want to support every option under the sun via the script. We want to guide users toward more explicit configuration with rke2 via the config file.

Your options are to download and run the binary directly with the parameters you want or to put your desired configuration in the config file.

--------------

_For the sake of full disclosure_, you can feed SOME params into the rke2 binary from the install script via environment variable. The rke2 arguments that have environment variable support can be set like this:
```
RKE2_DEBUG=true ./install.sh
```
The arguments that are supported are the ones that explicitly say they have a corresponding ENV_VAR in the rke2 help text. For example, in this snippet:
```
--config FILE, -c FILE               (config) Load configuration from FILE (default: "/etc/rancher/rke2/config.yaml") [$K3S_CONFIG_FILE]
--debug                              (logging) Turn on debug logs (default: false) [$RKE2_DEBUG]
   -v value                             (logging) Number for the log level verbosity (default: 0)
```
K3S_CONFIG_FILE and RKE2_DEBUG could be set and passed through to the install script but `-v` could not.
The supported environment variable arguments would be carried through to the systemd unit's environment file so that they persist across restarts/reboots.

**Comment by dweomer** [comment] 2020-08-31 23:57
one caveat: the installer recognizes and saves any environment variable that starts with `RKE2_` and saves that to the `EnvironmentFile` used by the systemd unit. the `K3S_CONFIG_FILE` will not be picked up (however this change to the spur revert would fix this: https://github.com/rancher/k3s/pull/2180/files#r480272052)

**Comment by davidnuzik** [comment] 2020-09-01 15:43
Closing based on the information Craig provided and our internal slack discussion. Essentially, the config file should be leveraged to pass args that do not have env vars associated with them.

**Closed by davidnuzik** 2020-09-01 15:43 UTC
Labels: [zube]: Backlog, area/install-script
