### ISSUE TITLE
Unable to join second node master/agent using beta8

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#227] opened 2020-08-24 16:28 UTC
Version:
rke2 version v1.18.4-beta8+rke2 (b62aa4edd0f80252673754b20ff203379cb59986)

Issue:
Unable to join second node as master or agent using beta8. Kubelet fails to start.
Installation is successful on first master node. 
```
INSTALL_RKE2_VERSION=v1.18.4-beta8+rke2 ./install.sh --tls-san IP
kubectl get nodes --kubeconfig=/etc/rancher/rke2/rke2.yaml
NAME               STATUS   ROLES         AGE   VERSION
ip-172-31-10-173   Ready    etcd,master   16m   v1.18.4-beta8+rke2
```
Second node:
```
INSTALL_RKE2_VERSION=v1.18.4-beta8+rke2 INSTALL_RKE2_EXEC='server --server https://MASTERIP:9345 --token TOKEN' ./install.sh
```

Logs:
```
Aug 24 16:03:22 ip-172-31-12-21 rke2[2253]: time="2020-08-24T16:03:22Z" level=info msg="Waiting for kubelet to be ready on node ip-172-31-12-21: Get \"https://127.0.0.1:6443/api/v1/nodes/ip-172-31-12-21\": dial tcp 127.0.0.1:6443: connect: connection refused"
Aug 24 16:03:27 ip-172-31-12-21 rke2[2253]: time="2020-08-24T16:03:27Z" level=error msg="Unable to watch for tunnel endpoints: Get \"https://127.0.0.1:6443/api/v1/namespaces/default/endpoints?fieldSelector=metadata.name%3Dkubernetes&resourceVersion=0&watch=true\": dial tcp 127.0.0.1:6443: connect: connection refused"
Aug 24 16:03:31 ip-172-31-12-21 rke2[2253]: time="2020-08-24T16:03:31Z" level=info msg="Waiting for etcd server to become available"
```

**Comment by davidnuzik** [comment] 2020-08-24 16:31
This could be a duplicate of https://github.com/rancher/rke2/issues/120 the only difference seems to be using flags instead of env var.

**Comment by briandowns** [comment] 2020-08-24 22:47
It appears as though the server being added is being marked as an etcd learning as it should be however getting stuck in a learning state and not getting promoted.

**Comment by briandowns** [comment] 2020-08-26 23:08
This issue has been handled in #237.

**Comment by ShylajaDevadiga** [comment] 2020-08-27 21:34
Same issue seen in beta11:
Unit file does not have reference to the server IP or token info
Second node is created as a separate cluster.
```
INSTALL_RKE2_VERSION=v1.18.4-beta11+rke2 ./install.sh --tls-san IP

INSTALL_RKE2_VERSION=v1.18.4-beta11+rke2 INSTALL_RKE2_EXEC='server --tls-san IP  --server https://MASTERIP:9345 --token TOKEN' ./install.sh
```
Unit file
 
```
cat /etc/systemd/system/multi-user.target.wants/rke2.service
[Unit]
Description=Rancher Kubernetes Engine v2
Documentation=https://github.com/rancher/rke2#readme
Wants=network-online.target
After=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
EnvironmentFile=-/etc/systemd/system/rke2.env
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=rke2 server
Type=notify
```
Also tried passing server and token through config.yaml
```
cat /etc/rancher/rke2/config.yaml 
write-kubeconfig-mode: "0644"
tls-san:
  - IP
server: https://MASTERIP:9345
token:
```

**Comment by ShylajaDevadiga** [comment] 2020-08-28 16:13
Issue is resolved in beta11.
Validated using updated install script ENV_VAR.

rke2 version: v1.18.4-beta11+rke2
OS: Ubuntu 20.04
```
kubectl get nodes --kubeconfig=/etc/rancher/rke2/rke2.yaml 
NAME               STATUS   ROLES         AGE     VERSION
ip-172-31-33-67    Ready    etcd,master   76m     v1.18.4-beta11+rke2
ip-172-31-43-69    Ready    etcd,master   11m     v1.18.4-beta11+rke2
ip-172-31-45-228   Ready    <none>        6m36s   v1.18.4-beta11+rke2

kubectl get pods -A --kubeconfig=/etc/rancher/rke2/rke2.yaml 
NAMESPACE     NAME                                                  READY   STATUS      RESTARTS   AGE
kube-system   etcd-ip-172-31-33-67                                  1/1     Running     0          77m
kube-system   etcd-ip-172-31-37-71                                  1/1     Running     0          46s
kube-system   etcd-ip-172-31-43-69                                  1/1     Running     0          102s
kube-system   helm-install-rke2-canal-bhnd4                         0/1     Completed   0          78m
kube-system   helm-install-rke2-coredns-mcksh                       0/1     Completed   0          78m
kube-system   helm-install-rke2-ingress-nginx-5qbvx                 0/1     Completed   0          78m
kube-system   helm-install-rke2-kube-proxy-x8bvx                    0/1     Completed   0          78m
kube-system   helm-install-rke2-metrics-server-xns56                0/1     Completed   0          78m
kube-system   kube-apiserver-ip-172-31-33-67                        1/1     Running     0          77m
kube-system   kube-apiserver-ip-172-31-37-71                        1/1     Running     0          42s
kube-system   kube-apiserver-ip-172-31-43-69                        1/1     Running     0          90s
kube-system   kube-controller-manager-ip-172-31-33-67               1/1     Running     0          77m
kube-system   kube-controller-manager-ip-172-31-37-71               1/1     Running     0          18s
kube-system   kube-controller-manager-ip-172-31-43-69               1/1     Running     0          87s
kube-system   kube-proxy-2gtkb                                      1/1     Running     0          8m34s
kube-system   kube-proxy-frmgl                                      1/1     Running     0          102s
kube-system   kube-proxy-np4wc                                      1/1     Running     0          78m
kube-system   kube-proxy-vcv7x                                      1/1     Running     0          13m
kube-system   kube-scheduler-ip-172-31-33-67                        1/1     Running     0          77m
kube-system   kube-scheduler-ip-172-31-37-71                        1/1     Running     0          31s
kube-system   kube-scheduler-ip-172-31-43-69                        1/1     Running     0          72s
kube-system   rke2-canal-dqfst                                      2/2     Running     0          78m
kube-system   rke2-canal-n9p7p                                      2/2     Running     0          102s
kube-system   rke2-canal-p7tjg                                      2/2     Running     0          8m34s
kube-system   rke2-canal-x2drg                                      2/2     Running     0          13m
kube-system   rke2-coredns-rke2-coredns-7979fc655-zqfkr             1/1     Running     0          78m
kube-system   rke2-ingress-nginx-controller-d78b898d5-vbgmm         1/1     Running     0          77m
kube-system   rke2-ingress-nginx-default-backend-5787b8798f-zggvl   1/1     Running     0          77m
kube-system   rke2-metrics-server-8c48bb8f7-b4c68                   1/1     Running     0          77m
```

**Closed** 2020-08-28 17:34 UTC
Labels: [zube]: To Test, kind/bug, priority/critical-urgent
