### ISSUE TITLE
[bug] rke2-coredns-rke2-coredns-autoscaler timeout after cluster reboot

### ISSUE THREAD

**Issue by guangbochen** [rancher/rke2#2175] opened 2021-11-29 13:50 UTC
**Environmental Info:**
RKE2 Version: v1.21.5+rke2r1

Node(s) CPU architecture, OS, and Version: 
A cluster with 3 server nodes, openSUSE Leap 15.3

**Describe the bug:**
- reboot all off 3 server node together and the `rke2-coredns-rke2-coredns-autoscaler-7c58bd5b6c-n8qwj` pod is failed to start with the following errors:

```
rke2-coredns-rke2-coredns-7bb4f446c-6gbmr               1/1     Running            1          6h58m   10.52.1.116   harvester-7bbvj   <none>           <none>
rke2-coredns-rke2-coredns-7bb4f446c-z2x6j               1/1     Running            1          6h58m   10.52.1.103   harvester-7bbvj   <none>           <none>
rke2-coredns-rke2-coredns-autoscaler-7c58bd5b6c-n8qwj   0/1     CrashLoopBackOff   115        7h34m   10.52.2.68    harvester-6qwss   <none>           <none>

$ks logs -f rke2-coredns-rke2-coredns-autoscaler-7c58bd5b6c-n8qwj
I1129 13:43:58.641857       1 autoscaler.go:49] Scaling Namespace: kube-system, Target: deployment/rke2-coredns-rke2-coredns
E1129 13:44:07.741874       1 autoscaler_server.go:108] Error while getting cluster status: timed out waiting for the condition


$ks logs -f rke2-coredns-rke2-coredns-7bb4f446c-6gbmr
W1129 07:37:09.321438       1 warnings.go:70] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W1129 07:37:09.323119       1 warnings.go:70] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
.:53
[INFO] plugin/reload: Running configuration MD5 = 7da3877dbcacfd983f39051ecafd33bd
CoreDNS-1.8.3
linux/amd64, go1.15.8b5, 4293992b
```

**Expected behavior:**
the `rke2-coredns-rke2-coredns-autoscaler` should be resumed properly.

**Additional context / logs:**
Related to https://github.com/harvester/harvester/issues/1428

**Comment by brandond** [comment] 2021-11-29 22:05
It's unclear to me what condition it's waiting for. It appears to me that the deployment is already scaled to the correct number of replicas, since there are two pods - but the logs don't say what it's trying to scale to, and you haven't included the output of `kubectl get deployment -n kube-system` that would confirm the deployment status. Can you show that output?

**Comment by guangbochen** [comment] 2021-11-30 03:23
yep, the deployment replicas of the `rke2-coredns-rke2-coredns` is showing as expected
```
NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
rke2-coredns-rke2-coredns              2/2     2            2           24h
rke2-coredns-rke2-coredns-autoscaler   0/1     1            0           24h
rke2-metrics-server                    1/1     1            1           24h
snapshot-controller                    2/2     2            2           24h
```
```
Name:                   rke2-coredns-rke2-coredns
Namespace:              kube-system
CreationTimestamp:      Mon, 29 Nov 2021 10:32:02 +0800
Labels:                 app.kubernetes.io/instance=rke2-coredns
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=rke2-coredns
                        app.kubernetes.io/version=1.8.4
                        helm.sh/chart=rke2-coredns-1.16.201-build2021072308
                        k8s-app=kube-dns
                        kubernetes.io/cluster-service=true
                        kubernetes.io/name=CoreDNS
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: rke2-coredns
                        meta.helm.sh/release-namespace: kube-system
Selector:               app.kubernetes.io/instance=rke2-coredns,app.kubernetes.io/name=rke2-coredns,k8s-app=kube-dns
Replicas:               2 desired | 2 updated | 2 total | 2 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/instance=rke2-coredns
                    app.kubernetes.io/name=rke2-coredns
                    k8s-app=kube-dns
  Annotations:      checksum/config: 5e864c06bb1e984f9c9034a73f59495c5b74675a01366d3b038e98732a6d6170
                    scheduler.alpha.kubernetes.io/critical-pod:
  Service Account:  coredns
  Containers:
   coredns:
    Image:       rancher/hardened-coredns:v1.8.3-build20210720
    Ports:       53/UDP, 53/TCP
    Host Ports:  0/UDP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    Limits:
      cpu:     100m
      memory:  128Mi
    Requests:
      cpu:        100m
      memory:     128Mi
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:    http-get http://:8181/ready delay=30s timeout=5s period=10s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (rw)
  Volumes:
   config-volume:
    Type:               ConfigMap (a volume populated by a ConfigMap)
    Name:               rke2-coredns-rke2-coredns
    Optional:           false
  Priority Class Name:  system-cluster-critical
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   rke2-coredns-rke2-coredns-7bb4f446c (2/2 replicas created)
Events:          <none>
```

**Comment by brandond** [comment] 2021-11-30 08:37
From a quick look at the code, it appears to just be timing out waiting for the node list cache to populate:
https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/blob/1.8.5/pkg/autoscaler/k8sclient/k8sclient.go#L172

This suggests that the pod can't talk to the apiserver for some reason, but clearly other things that would also want to talk to the apiserver (like coredns) are working fine - although it does look like both of them are running on the same node, which isn't ideal, and may in fact be related.

I'd like to see if this is fixed by the upcoming release of RKE2; we've updated coredns, the autoscaler, and the chart as well.

**Comment by guangbochen** [comment] 2021-11-30 09:24
what's the upcoming release version of the RKE2 we are referring in here? e.g, the `v1.21.6-rc2+rke2r2` or `v1.22.x`? thanks

**Comment by brandond** [comment] 2021-11-30 09:53
v1.21.7, which should have an RC available tomorrow.

**Comment by guangbochen** [comment] 2021-12-03 07:41
confirm this is resolved with bump RKE2 to version `v1.21.7`, would be good if we can have a QA double-check it since it is a common RKE2 issue, thanks.

**Comment by ShylajaDevadiga** [comment] 2021-12-08 07:59
Using rke2 version v1.21.7+rke2r2, created a 3 node cluster. After the nodes were ready and pods running, rebooted the nodes together and verified coredns-autoscaler does not timeout after reboot.
On another note, I was not able to reproduce this issue in rke2 version v1.21.5+rke2r1. Rebooted all nodes at once multiple times. 
```
> cat /etc/os-release
NAME="openSUSE Leap"
VERSION="15.3"
ID="opensuse-leap"
> kubectl get deploy -A
NAMESPACE     NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   rke2-coredns-rke2-coredns              2/2     2            2           7h47m
kube-system   rke2-coredns-rke2-coredns-autoscaler   1/1     1            1           7h47m
kube-system   rke2-metrics-server                    1/1     1            1           7h46m
```
Closing issue as resolved. Please feel free to re-open if you still see the issue.

**Comment by kajla** [comment] 2022-02-03 10:18
Hello,

I upgraded to v1.21.7+rke2r2, then v1.21.8+rke2r2 but none of them solved the problem.
Here is the technical data:
# kubectl get deploy -A
NAMESPACE               NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
cattle-fleet-system     fleet-agent                            1/1     1            1           21d
cattle-logging-system   rancher-logging                        1/1     1            1           21d
cattle-system           cattle-cluster-agent                   2/2     2            2           21d
cattle-system           system-upgrade-controller              1/1     1            1           5d22h
kube-system             rke2-coredns-rke2-coredns              2/2     2            2           21d
kube-system             rke2-coredns-rke2-coredns-autoscaler   0/1     1            0           21d
kube-system             rke2-metrics-server                    1/1     1            1           21d

# kubectl get nodes
NAME               STATUS   ROLES                       AGE   VERSION
rke2-agent1    Ready    <none>                      21d   v1.21.8+rke2r2
rke2-agent2    Ready    <none>                      21d   v1.21.8+rke2r2
rke2-agent3    Ready    <none>                      21d   v1.21.8+rke2r2
rke2-server1   Ready    control-plane,etcd,master   21d   v1.21.8+rke2r2
rke2-server2   Ready    control-plane,etcd,master   21d   v1.21.8+rke2r2
rke2-server3   Ready    control-plane,etcd,master   21d   v1.21.8+rke2r2

# kubectl -n kube-system get events
LAST SEEN   TYPE      REASON      OBJECT                                                      MESSAGE
3m21s       Warning   Unhealthy   pod/rke2-coredns-rke2-coredns-autoscaler-84dd9d7588-xkx5n   Liveness probe failed: Get "http://10.42.1.154:8080/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
48m         Normal    Pulled      pod/rke2-coredns-rke2-coredns-autoscaler-84dd9d7588-xkx5n   Container image "rancher/hardened-cluster-autoscaler:v1.8.5-build20211119" already present on machine
8m12s       Warning   BackOff     pod/rke2-coredns-rke2-coredns-autoscaler-84dd9d7588-xkx5n   Back-off restarting failed container

# kubectl -n kube-system get pods
NAME                                                    READY   STATUS             RESTARTS   AGE
cloud-controller-manager-bkp-avsz-server1               1/1     Running            2          21d
cloud-controller-manager-bkp-avsz-server2               1/1     Running            3          21d
cloud-controller-manager-bkp-avsz-server3               1/1     Running            2          21d
etcd-bkp-avsz-server1                                   1/1     Running            2          21d
etcd-bkp-avsz-server2                                   1/1     Running            2          21d
etcd-bkp-avsz-server3                                   1/1     Running            2          21d
kube-apiserver-bkp-avsz-server1                         1/1     Running            0          5d22h
kube-apiserver-bkp-avsz-server2                         1/1     Running            0          5d22h
kube-apiserver-bkp-avsz-server3                         1/1     Running            0          5d22h
kube-controller-manager-bkp-avsz-server1                1/1     Running            0          5d22h
kube-controller-manager-bkp-avsz-server2                1/1     Running            0          5d22h
kube-controller-manager-bkp-avsz-server3                1/1     Running            0          5d22h
kube-proxy-bkp-avsz-agent1                              1/1     Running            0          5d22h
kube-proxy-bkp-avsz-agent2                              1/1     Running            0          5d22h
kube-proxy-bkp-avsz-agent3                              1/1     Running            0          5d22h
kube-proxy-bkp-avsz-server1                             1/1     Running            0          5d22h
kube-proxy-bkp-avsz-server2                             1/1     Running            0          5d22h
kube-proxy-bkp-avsz-server3                             1/1     Running            0          5d22h
kube-scheduler-bkp-avsz-server1                         1/1     Running            0          5d22h
kube-scheduler-bkp-avsz-server2                         1/1     Running            0          5d22h
kube-scheduler-bkp-avsz-server3                         1/1     Running            0          5d22h
kured-cjvgf                                             1/1     Running            2          20d
kured-clsvp                                             1/1     Running            3          20d
kured-gwhhl                                             1/1     Running            3          20d
kured-snpd8                                             1/1     Running            2          20d
kured-tx96l                                             1/1     Running            2          20d
kured-vhrwr                                             1/1     Running            3          20d
rke2-canal-6r9gs                                        2/2     Running            6          21d
rke2-canal-8ctgn                                        2/2     Running            6          21d
rke2-canal-942ll                                        2/2     Running            6          21d
rke2-canal-l2pq6                                        2/2     Running            4          21d
rke2-canal-lk6fs                                        2/2     Running            4          21d
rke2-canal-x97js                                        2/2     Running            4          21d
rke2-coredns-rke2-coredns-5679c85bbb-fvs6f              1/1     Running            0          7d7h
rke2-coredns-rke2-coredns-5679c85bbb-hstkd              1/1     Running            0          5d23h
rke2-coredns-rke2-coredns-autoscaler-84dd9d7588-xkx5n   0/1     CrashLoopBackOff   1992       6d
rke2-ingress-nginx-controller-4pzmg                     1/1     Running            3          21d
rke2-ingress-nginx-controller-jxdjp                     1/1     Running            3          21d
rke2-ingress-nginx-controller-mzv62                     1/1     Running            3          21d
rke2-metrics-server-8574659c85-wczn9                    1/1     Running            0          6d

# kubectl -n kube-system logs rke2-coredns-rke2-coredns-autoscaler-84dd9d7588-xkx5n
I0203 10:11:32.686280       1 autoscaler.go:49] Scaling Namespace: kube-system, Target: deployment/rke2-coredns-rke2-coredns

# cat /etc/os-release
NAME="SLES"
VERSION="15-SP3"
VERSION_ID="15.3"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP3"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp3"
DOCUMENTATION_URL="https://documentation.suse.com/"

Can anyone help, what can I do to solve this issue, please? 
Thank you in advance.

**Comment by brandond** [comment] 2022-02-03 18:38
Can you get the logs from the previous (crashed) instance of the pod?
```bash
kubectl -n kube-system logs rke2-coredns-rke2-coredns-autoscaler-84dd9d7588-xkx5n --previous
kubectl -n kube-system describe pod rke2-coredns-rke2-coredns-autoscaler-84dd9d7588-xkx5n
```

**Comment by kajla** [comment] 2022-02-03 18:42
Of course, here is it:
```
 # kubectl -n kube-system logs rke2-coredns-rke2-coredns-autoscaler-84dd9d7588-xkx5n --previous
I0203 18:33:37.385428       1 autoscaler.go:49] Scaling Namespace: kube-system, Target: deployment/rke2-coredns-rke2-coredns
E0203 18:33:55.784280       1 autoscaler_server.go:108] Error while getting cluster status: timed out waiting for the condition
E0203 18:34:05.784283       1 autoscaler_server.go:108] Error while getting cluster status: timed out waiting for the condition
E0203 18:34:19.684352       1 autoscaler_server.go:108] Error while getting cluster status: timed out waiting for the condition
E0203 18:34:39.084427       1 autoscaler_server.go:108] Error while getting cluster status: timed out waiting for the condition

# kubectl -n kube-system describe pod rke2-coredns-rke2-coredns-autoscaler-84dd9d7588-xkx5n
Name:                 rke2-coredns-rke2-coredns-autoscaler-84dd9d7588-xkx5n
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 rke2-agent1/10.204.11.34
Start Time:           Fri, 28 Jan 2022 10:50:42 +0100
Labels:               app.kubernetes.io/instance=rke2-coredns
                      app.kubernetes.io/name=rke2-coredns-autoscaler
                      k8s-app=kube-dns-autoscaler
                      pod-template-hash=84dd9d7588
Annotations:          cattle.io/timestamp: 2022-01-20T07:32:43Z
                      checksum/configmap: 302890d39c0765f3d9fd90a403a965cc309ed8232e87a6d6e191049b84453b92
                      cni.projectcalico.org/containerID: c286a0a7acf5f2f00ecfc1f2dd826f48c205b7108cbb290773b09c451f90745c
                      cni.projectcalico.org/podIP: 10.42.1.154/32
                      cni.projectcalico.org/podIPs: 10.42.1.154/32
                      kubernetes.io/psp: global-unrestricted-psp
                      scheduler.alpha.kubernetes.io/critical-pod:
                      scheduler.alpha.kubernetes.io/tolerations: [{"key":"CriticalAddonsOnly", "operator":"Exists"}]
Status:               Running
IP:                   10.42.1.154
IPs:
  IP:           10.42.1.154
Controlled By:  ReplicaSet/rke2-coredns-rke2-coredns-autoscaler-84dd9d7588
Containers:
  autoscaler:
    Container ID:  containerd://52907ca25ebd0d1a0fae927b9ddf8791f0e63ecbe3cee0cef1ff0d3b748929df
    Image:         rancher/hardened-cluster-autoscaler:v1.8.5-build20211119
    Image ID:      docker.io/rancher/hardened-cluster-autoscaler@sha256:7cc3ec1030240a8b69d1185611c1f89cf357cddae642e8cc082e1a49ebc3611d
    Port:          <none>
    Host Port:     <none>
    Command:
      /cluster-proportional-autoscaler
      --namespace=kube-system
      --configmap=rke2-coredns-rke2-coredns-autoscaler
      --target=Deployment/rke2-coredns-rke2-coredns
      --logtostderr=true
      --v=2
    State:          Running
      Started:      Thu, 03 Feb 2022 19:39:44 +0100
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 03 Feb 2022 19:33:12 +0100
      Finished:     Thu, 03 Feb 2022 19:34:41 +0100
    Ready:          True
    Restart Count:  2109
    Limits:
      cpu:     20m
      memory:  20Mi
    Requests:
      cpu:        20m
      memory:     20Mi
    Liveness:     http-get http://:8080/healthz delay=10s timeout=10s period=30s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-q5gqt (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  kube-api-access-q5gqt:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Guaranteed
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 node-role.kubernetes.io/control-plane:NoSchedule op=Exists
                             node-role.kubernetes.io/etcd:NoExecute op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                      From     Message
  ----     ------     ----                     ----     -------
  Warning  Unhealthy  56m (x2431 over 6d7h)    kubelet  Liveness probe failed: Get "http://10.42.1.154:8080/healthz": dial tcp 10.42.1.154:8080: connect: connection refused
  Warning  Unhealthy  6m48s (x4460 over 6d7h)  kubelet  Liveness probe failed: Get "http://10.42.1.154:8080/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  BackOff    103s (x24527 over 6d7h)  kubelet  Back-off restarting failed container

```

**Comment by celsolom** [comment] 2022-02-03 18:46
Same problem

```sh
# kubectl version 
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+rke2r1", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T21:17:43Z", GoVersion:"go1.16.12b7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+rke2r1", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T21:17:43Z", GoVersion:"go1.16.12b7", Compiler:"gc", Platform:"linux/amd64"}

# kubectl -n kube-system logs rke2-coredns-rke2-coredns-autoscaler-6889866896-gzncj --previous
I0203 18:38:15.114736       1 autoscaler.go:49] Scaling Namespace: kube-system, Target: deployment/rke2-coredns-rke2-coredns
E0203 18:38:29.715075       1 autoscaler_server.go:108] Error while getting cluster status: timed out waiting for the condition
E0203 18:38:41.514305       1 autoscaler_server.go:108] Error while getting cluster status: timed out waiting for the condition
E0203 18:38:52.815156       1 autoscaler_server.go:108] Error while getting cluster status: timed out waiting for the condition

# kubectl -n kube-system describe pod rke2-coredns-rke2-coredns-autoscaler-6889866896-gzncj
Name:                 rke2-coredns-rke2-coredns-autoscaler-6889866896-gzncj
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 emtucontainersp1.redeemtu.sp.gov.br/10.11.0.8
Start Time:           Wed, 02 Feb 2022 16:18:33 -0300
Labels:               app.kubernetes.io/instance=rke2-coredns
                      app.kubernetes.io/name=rke2-coredns-autoscaler
                      k8s-app=kube-dns-autoscaler
                      pod-template-hash=6889866896
Annotations:          checksum/configmap: 302890d39c0765f3d9fd90a403a965cc309ed8232e87a6d6e191049b84453b92
                      cni.projectcalico.org/containerID: 429cf35c3fed6a813791024633a7b48f30b2666abf0b35d52018ae6b46df5cfa
                      cni.projectcalico.org/podIP: 10.42.0.4/32
                      cni.projectcalico.org/podIPs: 10.42.0.4/32
                      kubernetes.io/psp: global-unrestricted-psp
                      scheduler.alpha.kubernetes.io/critical-pod: 
                      scheduler.alpha.kubernetes.io/tolerations: [{"key":"CriticalAddonsOnly", "operator":"Exists"}]
Status:               Running
IP:                   10.42.0.4
IPs:
  IP:           10.42.0.4
Controlled By:  ReplicaSet/rke2-coredns-rke2-coredns-autoscaler-6889866896
Containers:
  autoscaler:
    Container ID:  containerd://35a299750c1afd6e71eff7d6edfd6478f299569e61b80f764241188e1a247b54
    Image:         rancher/hardened-cluster-autoscaler:v1.8.5-build20211119
    Image ID:      docker.io/rancher/hardened-cluster-autoscaler@sha256:7cc3ec1030240a8b69d1185611c1f89cf357cddae642e8cc082e1a49ebc3611d
    Port:          <none>
    Host Port:     <none>
    Command:
      /cluster-proportional-autoscaler
      --namespace=kube-system
      --configmap=rke2-coredns-rke2-coredns-autoscaler
      --target=Deployment/rke2-coredns-rke2-coredns
      --logtostderr=true
      --v=2
    State:          Running
      Started:      Thu, 03 Feb 2022 15:39:35 -0300
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 03 Feb 2022 15:37:47 -0300
      Finished:     Thu, 03 Feb 2022 15:39:30 -0300
    Ready:          True
    Restart Count:  337
    Limits:
      cpu:     20m
      memory:  20Mi
    Requests:
      cpu:        20m
      memory:     20Mi
    Liveness:     http-get http://:8080/healthz delay=10s timeout=10s period=30s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-92dnh (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  kube-api-access-92dnh:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Guaranteed
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 node-role.kubernetes.io/control-plane:NoSchedule op=Exists
                             node-role.kubernetes.io/etcd:NoExecute op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                     From     Message
  ----     ------     ----                    ----     -------
  Normal   Pulled     11m (x57 over 3h26m)    kubelet  Container image "rancher/hardened-cluster-autoscaler:v1.8.5-build20211119" already present on machine
  Warning  BackOff    6m18s (x336 over 3h9m)  kubelet  Back-off restarting failed container
  Warning  Unhealthy  60s (x132 over 3h25m)   kubelet  Liveness probe failed: Get "http://10.42.0.4:8080/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

**Comment by celsolom** [comment] 2022-02-03 18:49
Can be related?
![image](https://user-images.githubusercontent.com/20339961/152408855-56a381cc-3cba-4a34-9306-89245693065c.png)

**Comment by kajla** [comment] 2022-02-03 18:54
> Can be related? ![image](https://user-images.githubusercontent.com/20339961/152408855-56a381cc-3cba-4a34-9306-89245693065c.png)

I think no:
![image](https://user-images.githubusercontent.com/5457824/152409287-67dc28ad-9d68-43ab-b8fe-4eeaa5382a0a.png)

**Comment by brandond** [comment] 2022-02-03 19:52
It looks like the client is logging errors accessing the apiserver, which in turn causes the liveness probes to fail. What CNI are you using? Do you see any logs from other pods regarding errors accessing the apiserver?

**Comment by brandond** [comment] 2022-02-04 17:03
Other than the notably high restart count on the autoscaler pod, are you seeing this impact your cluster at all?

**Comment by kajla** [comment] 2022-02-04 17:09
No, only monitoring system alerts for this. I use this for monitoring: https://www.claudiokuenzler.com/monitoring-plugins/check_rancher2.php

I can reproduce on other RKE2 cluster.

**Comment by makton-dev** [comment] 2022-02-08 17:27
Running into the exact same issue. had to shutdown all nodes of the cluster and ended up with the autoscaler crashloop. using 1.21.8+rke2r1. redepoloyed the autoscaler and looks to be holding again.

**Comment by haowang1018** [comment] 2022-02-17 05:38
We have the same issue (autoscaler crashes continously) in our environment and fixed by increasing CPU limitation.

I used **kubectl edit deployment rke2-coredns-rke2-coredns-autoscaler** to change the CPU limitation from 20m to 200m and it seems no crashes any more (on v1.20.14+rke2r1).

Does anyone know how to change the helm chart of coredns deployment for permant effective?

**Comment by alb-dev** [comment] 2022-02-24 10:17
Updated RKE2 v1.23.3 to v1.23.4 and  i am seeing the same "problem" autoscaler keeps restarting, without any error besides "Container autoscaler failed liveness probe, will be restarted" . No errors in the logs. Also no "crash loop back off". The pods simply restarts. No Impact on the Cluster what so ever. 

```
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  41m                 default-scheduler  Successfully assigned kube-system/rke2-coredns-rke2-coredns-autoscaler-5b947fbb77-9v65g to kg-c01wk90902p
  Normal   Created    35m (x3 over 41m)   kubelet            Created container autoscaler
  Normal   Started    35m (x3 over 41m)   kubelet            Started container autoscaler
  Normal   Killing    21m (x3 over 36m)   kubelet            Container autoscaler failed liveness probe, will be restarted
  Normal   Pulled     21m (x4 over 41m)   kubelet            Container image "rancher/hardened-cluster-autoscaler:v1.8.5-build20211119" already present on machine
  Warning  Unhealthy  79s (x37 over 41m)  kubelet            Liveness probe failed: Get "http://10.233.1.201:8080/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

CNI = cilium 1.11.1

**Comment by brandond** [comment] 2022-05-19 06:47
It does sound like the default resources might need to be increased.

**Comment by brandond** [comment] 2022-06-06 17:44
Related:
*  https://github.com/rancher/rke2/issues/2885

**Comment by guangbochen** [comment] 2022-06-13 01:05
The default memory of atuoscaler pod is 20MiB and it is not enough per monitoring metrics, probably need to bump it to 50MiB.
![image](https://user-images.githubusercontent.com/4569037/173230435-4df0408b-38b9-4fb2-8c14-e6cad399afc5.png)

**Comment by ShylajaDevadiga** [comment] 2022-06-29 13:59
@kajla Could you share the setup including OS, OS version and rke2 config used to create the cluster. I tried to reproduce the issue on following setups

1. Standalone with 3 nodes. Rebooted all nodes at once
2. Upgrade and reboot
3. Import to rancher and install apps
4. Configure as local management cluster for rancher.

Resource limit on autoscaler pod is now bumped. Any pointers to reproduce the issue would be helpful to validate the issue is resolved

**Comment by ShylajaDevadiga** [comment] 2022-06-29 17:46
Closing issue as validated. Please feel free to reopen if it reoccurs.

**Closed by ShylajaDevadiga** 2022-06-29 17:46 UTC
Labels: area/harvester
