### ISSUE TITLE
Install.sh on does not work on aarch64 RPM systems

### ISSUE THREAD

**Issue by TomWis97** [rancher/rke2#6312] opened 2024-07-12 18:00 UTC
**Environmental Info:**
RKE2 Version: v1.28.11+rke2r1

Node(s) CPU architecture, OS, and Version: 
In this case RHEL 9, but this occures on every aarch64 machine.
`Linux ip-x-x-x-x.eu-west-3.compute.internal 5.14.0-427.20.1.el9_4.aarch64 #1 SMP PREEMPT_DYNAMIC Thu May 23 21:07:05 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux`

Cluster Configuration:
(Not relevant.) 1 Server.

**Describe the bug:**
When running the installation script from https://get.rke2.io on a aarch64 machine with an RPM-based package manager, installation fails.  
The script places a repository config, referring to the x86_64 repository. Obviously, packages from that repo cannot be installed on aarch64 machines. So the script fails, leaving an incorrect Yum configuration.
Also, ARM64 RPM packages may not be available, but I think that's out of scope for this bug.

**Steps To Reproduce:**

- Have a aarch64 machine with a RPM-based distribution.
- Run `curl https://get.rke2.io | sudo sh`.

**Expected behavior:**
- If aarch64 RPMs are available, the script should refer to the repository containing the correct architecture.
- If aarch64 RPMs are _not_ available: fall back to .tar installation method.

**Actual behavior:**
- Yum repository configuration referring to incorrect architecture is placed.
- Installation fails.

**Additional context / logs:**

N/A.

**Comment by brandond** [comment] 2024-07-13 06:51
Duplicate of https://github.com/rancher/rke2/issues/5135 which I have installed.

**Closed by brandond** 2024-07-13 06:51 UTC
