### ISSUE TITLE
ebtablesd marked as malware

### ISSUE THREAD

**Issue by canle1404** [rancher/rke2#5656] opened 2024-04-02 02:34 UTC
**Environmental Info:**
RKE2 Version: v1.25.16+rke2r1

Node(s) CPU architecture, OS, and Version: Linux ***************-3ff50b01-r276g 5.4.0-1041-aws #43-Ubuntu SMP Fri Mar 19 22:06:16 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 3 nodes

**Describe the bug:** We are using ORCA for scanning security and ORCA marked this file as malware `/var/lib/rancher/rke2/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/7/fs/usr/sbin/ebtablesd`
VirusTotal scan result: https://www.virustotal.com/gui/file/c4af716f77714aa5dd16f570a76d4fc890cbcf17d1f7c7b1bed4aff2a67a127e

**Steps To Reproduce:**

- Installed RKE2 cluster with Rancher
- Get hash file: `sha256sum /var/lib/rancher/rke2/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/<snapshot ID>/fs/usr/sbin/ebtablesd`
- Copy the sha into https://www.virustotal.com/gui/home/search

**Expected behavior:**
![image](https://github.com/rancher/rke2/assets/132538505/ac598988-6500-49e5-a711-8a30449a01d0)

**Actual behavior:**

![image](https://github.com/rancher/rke2/assets/132538505/297cbeca-439d-4725-aa82-6285d96b5e07)

**Additional context / logs:**

**Comment by canle1404** [comment] 2024-04-02 02:35
I think this issue will relate to https://github.com/k3s-io/k3s/issues/9738

**Comment by brandond** [comment] 2024-04-02 06:14
Yes, closing this as a duplicate of that issue.

**Closed by brandond** 2024-04-02 06:14 UTC
