### ISSUE TITLE
Upgrade from 1.19 to 1.20 causes helm deployments to be deleted 

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rke2#826] opened 2021-03-30 16:56 UTC
3 node rke2 cluster 1.19 (just masters without taint) with rancher and cert-manager as applications. 

All "addons" i.e. rancher and cert-manager were deployed using static/charts and manifests.

Then I did a rolling upgrade - node by node using tarball, image-tar and rke2-service restart.

During this process some deployed helm charts somehow got deleted - so "helm list -A" does not show cert-manager deployed anymore but the deployments are still there and running - it just seems that the helm "objects" are gone for some reason.

```
NAME                    NAMESPACE               REVISION        UPDATED                                 STATUS          CHART                                                                                   APP VERSION
fleet                   fleet-system            392             2021-03-29 09:18:59.262488056 +0000 UTC deployed        fleet-0.3.300                                                                           0.3.3
fleet-agent             fleet-system            3               2021-03-25 14:51:05.158688289 +0000 UTC deployed        fleet-agent-v0.0.0+s-5c689aa28caaf99eb3bfafd0efc65e6ad68b84f036b3a5f8b62a2fd0f9071         
fleet-crd               fleet-system            2               2021-03-25 07:38:34.426381565 +0000 UTC deployed        fleet-crd-0.3.300                                                                       0.3.3
rancher-operator        rancher-operator-system 1               2021-03-25 07:23:16.800608132 +0000 UTC deployed        rancher-operator-0.1.200                                                                0.1.2
rancher-operator-crd    rancher-operator-system 1               2021-03-25 07:23:40.813539238 +0000 UTC deployed        rancher-operator-crd-0.1.200                                                            0.1.2
rancher-webhook         cattle-system           1               2021-03-25 07:23:32.076197692 +0000 UTC deployed        rancher-webhook-0.1.0-beta900                                                           0.1.0-beta9
rke2-kube-proxy         kube-system             270             2021-03-30 15:25:07.119968444 +0000 UTC deployed        rke2-kube-proxy-v1.20.4-build2021030201                                                 v1.20.4

```

```
kubectl get pods -A|grep Crash

kube-system               helm-install-cert-manager-tnn89                       0/1     CrashLoopBackOff   21         87m
kube-system               helm-install-rancher-backup-crd-9xjwq                 0/1     CrashLoopBackOff   21         87m
kube-system               helm-install-rancher-backup-fcr2b                     0/1     CrashLoopBackOff   21         87m
kube-system               helm-install-rke2-canal-mrs82                         0/1     CrashLoopBackOff   21         87m
kube-system               helm-install-rke2-coredns-959fr                       0/1     CrashLoopBackOff   21         87m
kube-system               helm-install-rke2-ingress-nginx-c9znc                 0/1     CrashLoopBackOff   21         87m
kube-system               helm-install-rke2-metrics-server-lzmqn                0/1     CrashLoopBackOff   21         87m
```

Now the helm install jobs are stuck in "CrashLoopBackOff" with this:

```
+ helm_v3 install --namespace cert-manager cert-manager https://rancher.suse:9345/static/charts/cert-manager-v1.2.0.tgz --values /config/values-01_HelmChart.yaml
Error: cannot re-use a name that is still in use
```

or this:

```
+ helm_v3 install --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string global.systemDefaultRegistry=registry01.suse:5000 rke2-canal /rke2-canal.tgz --values /config/values-10_HelmChartConfig.yaml
Error: cannot re-use a name that is still in use

```

It seems that for some reason the "upgrade" fails (even though cert-manager did not change) - and then the deployment is deleted from the helm CRDs and due to that "helm list" does not show it anymore. When the helm operator then tries to re-deploy it can not because the application is still there..

Is this a known issue and does someone have an idea how to repair and avoid this problem?

**Comment by brandond** [comment] 2021-03-30 17:28
Can you include the full output of the helm job pods? It should be doing an upgrade instead of an install, but for some reason the existing chart isn't being found.

https://github.com/k3s-io/klipper-helm/blob/master/entry#L35

**Comment by Martin-Weiss** [comment] 2021-03-31 07:04
> 
> 
> Can you include the full output of the helm job pods? It should be doing an upgrade instead of an install, but for some reason the existing chart isn't being returned by `helm ls`.
> 
> https://github.com/k3s-io/klipper-helm/blob/master/entry#L35

Something deleted the already deployed charts during the upgrade:

```
rancher-master-01:~ # helm ls -A
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/rke2/rke2.yaml
NAME                    NAMESPACE               REVISION        UPDATED                                 STATUS          CHART                                                                                   APP VERSION
fleet                   fleet-system            392             2021-03-29 09:18:59.262488056 +0000 UTC deployed        fleet-0.3.300                                                                           0.3.3
fleet-agent             fleet-system            3               2021-03-25 14:51:05.158688289 +0000 UTC deployed        fleet-agent-v0.0.0+s-5c689aa28caaf99eb3bfafd0efc65e6ad68b84f036b3a5f8b62a2fd0f9071
fleet-crd               fleet-system            2               2021-03-25 07:38:34.426381565 +0000 UTC deployed        fleet-crd-0.3.300                                                                       0.3.3
rancher-operator        rancher-operator-system 1               2021-03-25 07:23:16.800608132 +0000 UTC deployed        rancher-operator-0.1.200                                                                0.1.2
rancher-operator-crd    rancher-operator-system 1               2021-03-25 07:23:40.813539238 +0000 UTC deployed        rancher-operator-crd-0.1.200                                                            0.1.2
rancher-webhook         cattle-system           1               2021-03-25 07:23:32.076197692 +0000 UTC deployed        rancher-webhook-0.1.0-beta900                                                           0.1.0-beta9
rke2-kube-proxy         kube-system             270             2021-03-30 15:25:07.119968444 +0000 UTC deployed        rke2-kube-proxy-v1.20.4-build2021030201                                                 v1.20.4

```

And in the log I just see this:

```
rancher-master-01:~ # kubectl -n kube-system logs helm-install-rke2-canal-mrs82
CHART=$(sed -e "s/%{KUBERNETES_API}%/${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}/g" <<< "${CHART}")
set +v -x
+ cp /var/run/secrets/kubernetes.io/serviceaccount/ca.crt /usr/local/share/ca-certificates/
+ update-ca-certificates
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
+ '[' true '!=' true ']'
+ '[' '' == 1 ']'
+ '[' '' == v2 ']'
+ shopt -s nullglob
+ helm_content_decode
+ set -e
+ ENC_CHART_PATH=/chart/rke2-canal.tgz.base64
+ CHART_PATH=/rke2-canal.tgz
+ '[' '!' -f /chart/rke2-canal.tgz.base64 ']'
+ base64 -d
+ cat /chart/rke2-canal.tgz.base64
+ CHART=/rke2-canal.tgz
+ set +e
+ '[' install '!=' delete ']'
+ helm_repo_init
+ grep -q -e 'https\?://'
+ '[' helm_v3 == helm_v3 ']'
+ [[ /rke2-canal.tgz == stable/* ]]
+ '[' -n '' ']'
+ helm_update install --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string global.systemDefaultRegistry=registry01.suse:5000
+ '[' helm_v3 == helm_v3 ']'
++ jq -r '"\(.[0].app_version),\(.[0].status)"'
++ tr '[:upper:]' '[:lower:]'
++ helm_v3 ls -f '^rke2-canal$' --namespace kube-system --output json
+ LINE=null,null
++ echo null,null
++ cut -f1 -d,
+ INSTALLED_VERSION=null
++ echo null,null
++ cut -f2 -d,
+ STATUS=null
+ VALUES=
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-10_HelmChartConfig.yaml'
+ '[' install = delete ']'
+ '[' -z null ']'
+ '[' null = deployed ']'
+ '[' null = failed ']'
+ '[' null = deleted ']'
+ helm_v3 install --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string global.systemDefaultRegistry=registry01.suse:5000 rke2-canal /rke2-canal.tgz --values /config/values-10_HelmChartConfig.yaml
Error: cannot re-use a name that is still in use

```

But I can not find the log of the job that deleted the helm deployment..

A wild assumption is that during the upgrade of RKE2 the first "helm upgrade" failed and that failure caused the deletion in the next step but the deletion did not delete everything..

**Comment by Martin-Weiss** [comment] 2021-03-31 10:17
Just trying to reproducing the issue... will update later.. assumption is that this is related to the speed / wait between upgrading the masters.. either waiting too long or not waiting long enough before upgrading the next master might be related..

**Comment by brandond** [comment] 2021-03-31 21:57
Just out of curiosity, are you deploying the same manifests to all nodes in the cluster? I see that rke2-kube-proxy and fleet have both been re-deployed by Helm almost 300 times. This is usually caused by different nodes having different manifests and going back and forth re-deploying their local version.

**Comment by Martin-Weiss** [comment] 2021-04-01 08:34
> 
> 
> Just out of curiosity, are you deploying the same manifests to all nodes in the cluster? I see that rke2-kube-proxy and fleet have both been re-deployed by Helm almost 300 times. This is usually caused by different nodes having different manifests and going back and forth re-deploying their local version.

During 1.19 deployment I copy identical static/charts and manifests to ALL three masters.
During upgrade to 1.20 I upgrade the first master and it can happen that one or the other chart is now different based on required changes between k8s releases or due to changes in image versions etc.. So during the upgrade - yes - there are different versions on the masters - but after all three masters are upgraded - all have the same again.

In case of changes in helm charts - how does RKE2 ensure that only the latest version that exists on all three masters is applied and used? How is a change of a manifest detected at all?

**Comment by brandond** [comment] 2021-04-01 19:43
It does not make any effort to ensure that the manifests are in sync across nodes. When a node starts up, all manifests are applied to the cluster. Afterwards, the manifests are checked at 1 minute intervals for changes, and if change is found, the manifests are again applied until the apply succeeds.

There is a PR out there to store modification times on the AddOn resource so that only the node with the newest manifest applies the change, but this has not been merged due to some disagreements within the team on whether or not this is the best approach. https://github.com/k3s-io/k3s/pull/2169

**Comment by Martin-Weiss** [comment] 2021-04-06 06:55
> 
> 
> It does not make any effort to ensure that the manifests are in sync across nodes. 

How do you ensure that this is "not any effort"? 
How do you keep these in sync between all your masters especially during day 2 operations where we have mixed versions?
Should we update the manifests on masters before upgrading k8s/rke2 on the first node?
What if the update happens while one or the other machine is not there?
How do we deal with this during adding more masters?

Maybe we need to get rid of the local manifests after they got applied or they should come from a central store/git instead from local files?

> When a node starts up, all manifests are applied to the cluster. Afterwards, the manifests are checked at 1 minute intervals for changes, and if change is found, the manifests are again applied until the apply succeeds.

What exactly does the system check? Modification time or md5sum?

> 
> There is a PR out there to store modification times on the AddOn resource so that only the node with the newest manifest applies the change, but this has not been merged due to some disagreements within the team on whether or not this is the best approach. [k3s-io/k3s#2169](https://github.com/k3s-io/k3s/pull/2169)

**Comment by brandond** [comment] 2021-04-06 18:44
> How do you ensure that this is "not any effort"?

I didn't say that it isn't any effort, I said that k3s "does not make any effort" as in it does nothing to ensure this. If the user wants to use the deploy controller to install things to the cluster, it is up to them to either do it on a single node, or keep the content in sync across the servers.

> What exactly does the system check? Modification time or md5sum?

All manifests on disk are deployed on server startup, the file mtimes stored in-memory, and hashes stored in the AddOn CRD. After startup is complete, k3s checks file mtimes on disk once a minute. If the mtimes change or a new file is created, the file is hashed and compared to the hash stored in the AddOn CRD. If the hashes do not match, the manifest is deployed. You can check this out yourself: https://github.com/k3s-io/k3s/blob/master/pkg/deploy/controller.go

**Comment by VestigeJ** [comment] 2022-07-19 23:18
**Validated using VERSION=[v1.22.12-rc2+rke2r1](https://github.com/rancher/rke2/releases/tag/v1.22.12-rc2%2Brke2r1)**

##Environment Details
 
*Infrastructure*
- [X] Cloud

*Node(s) CPU architecture, OS, and Version:*
```
Linux 5.3.18-59.37-default x86_64 GNU/Linux-SUSE Linux Enterprise Server 15 SP3
```
 
*Cluster Configuration:*
```
NAME               STATUS   ROLES                       AGE   VERSION
ip-1-1-3-2   Ready    control-plane,etcd,master   70m   v1.22.12+rke2r1 
```

## Replication Steps
 
$  VERSION=v1.22.12-rc2+rke2r1
$  sudo INSTALL_RKE2_VERSION=$VERSION INSTALL_RKE2_EXEC=server sh - ./install-rke2.sh

$ kgp -A -o wide #note default cluster ipv4 CIDR block
```
kube-system   pod/rke2-coredns-rke2-coredns-6775f768c8-kq8k2              1/1     Running     0          15m   10.42.0.3       ip-1-1-3-2   <none>           <none>
kube-system   pod/rke2-coredns-rke2-coredns-autoscaler-7c77dcfb76-p9fxh   1/1     Running     0          15m   10.42.0.2       ip-1-1-3-2   <none>           <none>
kube-system   pod/rke2-ingress-nginx-controller-xc7zl                     1/1     Running     0          14m   10.42.0.8       ip-1-1-3-2   <none>           <none>
kube-system   pod/rke2-metrics-server-8574659c85-s7gvt                    1/1     Running     0          14m   10.42.0.6       ip-1-1-3-2   <none>           <none>
```

$  k annotate -n kube-system helmchart/rke2-ingress-nginx helmcharts.helm.cattle.io/unmanaged=true
```
helmchart.helm.cattle.io/rke2-ingress-nginx annotated
```

$  k edit -n kube-system helmchart/rke2-ingress-nginx #note modified cluster ipv4 CIDR block
```
set:
    global.cattle.systemDefaultRegistry: ""
    global.clusterCIDR: 10.42.14.0/16
    global.clusterCIDRv4: 10.42.14.0/16
    global.clusterCIDRv6: ""
    global.clusterDNS: 10.43.0.10
    global.clusterDomain: cluster.local
    global.rke2DataDir: /var/lib/rancher/rke2
    global.serviceCIDR: 10.43.0.0/16
    global.systemDefaultRegistry: ""
status:
  jobName: helm-install-rke2-ingress-nginx
```


$  kgp -A -o wide
 ```
kube-system   rke2-coredns-rke2-coredns-6775f768c8-kq8k2              1/1     Running     0          69m   10.42.0.3       ip-1-1-3-2   <none>           <none>
kube-system   rke2-coredns-rke2-coredns-autoscaler-7c77dcfb76-p9fxh   1/1     Running     0          69m   10.42.0.2       ip-1-1-3-2   <none>           <none>
kube-system   rke2-ingress-nginx-controller-xc7zl                     1/1     Running     0          68m   10.42.0.8      ip-1-1-3-2   <none>           <none>
kube-system   rke2-metrics-server-8574659c85-s7gvt                    1/1     Running     0          68m   10.42.0.6       ip-1-1-3-2   <none>           <none>
```

$ kubectl delete -n kube-system helmchart/rke2-ingress-nginx
```
helmchart.helm.cattle.io "rke2-ingress-nginx" deleted
```

$ kgp -A -o wide
```
NAMESPACE     NAME                                                    READY   STATUS      RESTARTS   AGE    IP              NODE               NOMINATED NODE   READINESS GATES
kube-system   cloud-controller-manager-ip-1-1-3-2               1/1     Running     0          125m   1-1-3-2   ip-1-1-3-2   <none>           <none>
kube-system   etcd-ip-1-1-3-2                                   1/1     Running     0          125m   1-1-3-2   ip-1-1-3-2   <none>           <none>
kube-system   helm-install-rke2-canal-876jk                           0/1     Completed   0          125m   1-1-3-2   ip-1-1-3-2   <none>           <none>
kube-system   helm-install-rke2-coredns-kj8pk                         0/1     Completed   0          125m   1-1-3-2   ip-1-1-3-2   <none>           <none>
kube-system   helm-install-rke2-ingress-nginx-56r6j                   0/1     Completed   0          125m   10.42.0.4       ip-1-1-3-2   <none>           <none>
kube-system   helm-install-rke2-metrics-server-ljwzz                  0/1     Completed   0          125m   10.42.0.5       ip-1-1-3-2   <none>           <none>
kube-system   kube-apiserver-ip-1-1-3-2                         1/1     Running     0          124m   1-1-3-2   ip-1-1-3-2   <none>           <none>
kube-system   kube-controller-manager-ip-1-1-3-2                1/1     Running     0          125m   1-1-3-2   ip-1-1-3-2   <none>           <none>
kube-system   kube-proxy-ip-1-1-3-2                             1/1     Running     0          125m   ip-1-1-3-2   ip-1-1-3-2   <none>           <none>
kube-system   kube-scheduler-ip-1-1-3-2                         1/1     Running     0          125m   1-1-3-2   ip-1-1-3-2   <none>           <none>
kube-system   rke2-canal-nmdg6                                        2/2     Running     0          125m   1-1-3-2   ip-1-1-3-2   <none>           <none>
kube-system   rke2-coredns-rke2-coredns-6775f768c8-kq8k2              1/1     Running     0          125m   10.42.0.3       ip-1-1-3-2   <none>           <none>
kube-system   rke2-coredns-rke2-coredns-autoscaler-7c77dcfb76-p9fxh   1/1     Running     0          125m   10.42.0.2      ip-1-1-3-2   <none>           <none>
kube-system   rke2-ingress-nginx-controller-xc7zl                     1/1     Running     0          124m   10.42.0.8       ip-1-1-3-2   <none>           <none>
kube-system   rke2-metrics-server-8574659c85-s7gvt                    1/1     Running     0          124m   10.42.0.6       ip-1-1-3-2   <none>           <none>
```

----------------------------------------------------------------------------------------
**Validated using VERSION=[v1.23.9-rc2+rke2r1](https://github.com/rancher/rke2/releases/tag/v1.23.9-rc2%2Brke2r1)**


*Node(s) CPU architecture, OS, and Version:*
```
Linux 5.3.18-59.37-default x86_64 GNU/Linux-SUSE Linux Enterprise Server 15 SP3"
```
 
*Cluster Configuration:*
```
NAME               STATUS   ROLES                       AGE   VERSION
ip-12-1-19-23   Ready    control-plane,etcd,master   71m   v1.23.9+rke2r1 
```
## Replication Steps
 
$ VERSION=v1.23.9-rc2+rke2r1
$ sudo INSTALL_RKE2_VERSION=$VERSION INSTALL_RKE2_EXEC=server sh - ./install-rke2.sh

$  k annotate -n kube-system helmchart/rke2-ingress-nginx helmcharts.helm.cattle.io/unmanaged=true
```
helmchart.helm.cattle.io/rke2-ingress-nginx annotated
```

$  kgp -A -o wide
```
kube-system   rke2-coredns-rke2-coredns-545d64676-jxgg5               1/1     Running     0          13m   10.42.0.4       ip-12-1-19-23   <none>           <none>
kube-system   rke2-coredns-rke2-coredns-autoscaler-5dd676f5c7-bp4ng   1/1     Running     0          13m   10.42.0.3       ip-12-1-19-23   <none>           <none>
kube-system   rke2-ingress-nginx-controller-4kn6z                     1/1     Running     0          12m   10.42.0.8       ip-12-1-19-23   <none>           <none>
kube-system   rke2-metrics-server-6564db4569-8np5f                    1/1     Running     0          12m   10.42.0.7       ip-12-1-19-23   <none>           <none>
```


$  k edit -n kube-system helmchart/rke2-ingress-nginx #note modified cluster ipv4 CIDR block

```
set:
    global.cattle.systemDefaultRegistry: ""
    global.clusterCIDR: 10.42.77.0/16
    global.clusterCIDRv4: 10.42.77.0/16
    global.clusterCIDRv6: ""
    global.clusterDNS: 10.43.0.10
    global.clusterDomain: cluster.local
    global.rke2DataDir: /var/lib/rancher/rke2
    global.serviceCIDR: 10.43.0.0/16
    global.systemDefaultRegistry: ""
status:
  jobName: helm-install-rke2-ingress-nginx
```

$  kgp -A -o wide
```
kube-system   rke2-coredns-rke2-coredns-545d64676-jxgg5               1/1     Running     0          13m   10.42.0.4       ip-12-1-19-23   <none>           <none>
kube-system   rke2-coredns-rke2-coredns-autoscaler-5dd676f5c7-bp4ng   1/1     Running     0          13m   10.42.0.3       ip-12-1-19-23   <none>           <none>
kube-system   rke2-ingress-nginx-controller-4kn6z                     1/1     Running     0          12m   10.42.0.8       ip-12-1-19-23   <none>           <none>
kube-system   rke2-metrics-server-6564db4569-8np5f                    1/1     Running     0          12m   10.42.0.7       ip-12-1-19-23   <none>           <none>
```

$ kubectl delete -n kube-system helmchart/rke2-ingress-nginx
```
helmchart.helm.cattle.io "rke2-ingress-nginx" deleted
```

$ kgp -A -o wide
```
NAMESPACE     NAME                                                    READY   STATUS      RESTARTS   AGE    IP              NODE               NOMINATED NODE   READINESS GATES
kube-system   cloud-controller-manager-ip-12-1-19-23               1/1     Running     0          126m   12-1-19-23   ip-12-1-19-23   <none>           <none>
kube-system   etcd-ip-12-1-19-23                                   1/1     Running     0          126m   12-1-19-23   ip-12-1-19-23   <none>           <none>
kube-system   helm-install-rke2-canal-4mht7                           0/1     Completed   0          126m   12-1-19-23   ip-12-1-19-23   <none>           <none>
kube-system   helm-install-rke2-coredns-4d6nz                         0/1     Completed   0          126m   12-1-19-23   ip-12-1-19-23   <none>           <none>
kube-system   helm-install-rke2-ingress-nginx-c5zlk                   0/1     Completed   0          126m   10.42.0.2       ip-12-1-19-23   <none>           <none>
kube-system   helm-install-rke2-metrics-server-wz8m2                  0/1     Completed   0          126m   10.42.0.6       ip-12-1-19-23   <none>           <none>
kube-system   kube-apiserver-ip-12-1-19-23                         1/1     Running     0          126m   12-1-19-23   ip-12-1-19-23   <none>           <none>
kube-system   kube-controller-manager-ip-12-1-19-23                1/1     Running     0          126m   12-1-19-23   ip-12-1-19-23   <none>           <none>
kube-system   kube-proxy-ip-12-1-19-23                             1/1     Running     0          126m   12-1-19-23   ip-12-1-19-23   <none>           <none>
kube-system   kube-scheduler-ip-12-1-19-23                         1/1     Running     0          126m   12-1-19-23   ip-12-1-19-23   <none>           <none>
kube-system   rke2-canal-w7g24                                        2/2     Running     0          126m   12-1-19-23   ip-12-1-19-23   <none>           <none>
kube-system   rke2-coredns-rke2-coredns-545d64676-jxgg5               1/1     Running     0          126m   10.42.0.4       ip-12-1-19-23   <none>           <none>
kube-system   rke2-coredns-rke2-coredns-autoscaler-5dd676f5c7-bp4ng   1/1     Running     0          126m   10.42.0.3       ip-12-1-19-23   <none>           <none>
kube-system   rke2-ingress-nginx-controller-4kn6z                     1/1     Running     0          125m   10.42.0.8       ip-12-1-19-23   <none>           <none>
kube-system   rke2-metrics-server-6564db4569-8np5f                    1/1     Running     0          125m   10.42.0.7       ip-12-1-19-23   <none>           <none>
```
----------------------------------------------------------------------------------------

**Validated using VERSION=[v1.24.3-rc2+rke2r1](https://github.com/rancher/rke2/releases/tag/v1.24.3-rc2%2Brke2r1)**


*Node(s) CPU architecture, OS, and Version:*
```
Linux 5.3.18-59.37-default x86_64 GNU/Linux-SUSE Linux Enterprise Server 15 SP3"
```
 
*Cluster Configuration:*
```
NAME               STATUS   ROLES                       AGE   VERSION
ip-17-3-0-12   Ready    control-plane,etcd,master   71m   v1.24.3+rke2r1 
```

$ VERSION=v1.24.3-rc2+rke2r1
$ sudo INSTALL_RKE2_VERSION=$VERSION INSTALL_RKE2_EXEC=server sh - ./install-rke2.sh

$  k annotate -n kube-system helmchart/rke2-ingress-nginx helmcharts.helm.cattle.io/unmanaged=true
```
helmchart.helm.cattle.io/rke2-ingress-nginx annotated
```

$  kgp -A -o wide
```
kube-system   rke2-coredns-rke2-coredns-76cb76d66-5pwxl               1/1     Running     0          19m   10.42.0.2       ip-17-3-0-12   <none>           <none>
kube-system   rke2-coredns-rke2-coredns-autoscaler-58867f8fc5-c9hjm   1/1     Running     0          19m   10.42.0.3       ip-17-3-0-12   <none>           <none>
kube-system   rke2-ingress-nginx-controller-88rlp                     1/1     Running     0          17m   10.42.0.8       ip-17-3-0-12   <none>           <none>
kube-system   rke2-metrics-server-6979d95f95-vslq9                    1/1     Running     0          17m   10.42.0.6       ip-17-3-0-12   <none>           <none>
```

$  k edit -n kube-system helmchart/rke2-ingress-nginx #note modified cluster ipv4 CIDR block
```
set:
    global.cattle.systemDefaultRegistry: ""
    global.clusterCIDR: 10.42.99.0/16
    global.clusterCIDRv4: 10.42.99.0/16
    global.clusterCIDRv6: ""
    global.clusterDNS: 10.43.0.10
    global.clusterDomain: cluster.local
    global.rke2DataDir: /var/lib/rancher/rke2
    global.serviceCIDR: 10.43.0.0/16
    global.systemDefaultRegistry: ""
status:
  jobName: helm-install-rke2-ingress-nginx
```

$  kgp -A -o wide
```
kube-system   rke2-coredns-rke2-coredns-76cb76d66-5pwxl               1/1     Running     0          69m   10.42.0.2       ip-17-3-0-12   <none>           <none>
kube-system   rke2-coredns-rke2-coredns-autoscaler-58867f8fc5-c9hjm   1/1     Running     0          69m   10.42.0.3       ip-17-3-0-12   <none>           <none>
kube-system   rke2-ingress-nginx-controller-88rlp                     1/1     Running     0          68m   10.42.0.8       ip-17-3-0-12   <none>           <none>
kube-system   rke2-metrics-server-6979d95f95-vslq9                    1/1     Running     0          68m   10.42.0.6       ip-17-3-0-12   <none>           <none>
``` 

$ kubectl delete -n kube-system helmchart/rke2-ingress-nginx
```
helmchart.helm.cattle.io "rke2-ingress-nginx" deleted
```

$ kgp -A -o wide
```
NAMESPACE     NAME                                                    READY   STATUS      RESTARTS   AGE    IP              NODE               NOMINATED NODE   READINESS GATES
kube-system   cloud-controller-manager-ip-17-3-0-12               1/1     Running     0          127m   17-3-0-12   ip-17-3-0-12   <none>           <none>
kube-system   etcd-ip-17-3-0-12                                   1/1     Running     0          127m   17-3-0-12   ip-17-3-0-12   <none>           <none>
kube-system   helm-install-rke2-canal-l579q                           0/1     Completed   0          127m   17-3-0-12   ip-17-3-0-12   <none>           <none>
kube-system   helm-install-rke2-coredns-zntfh                         0/1     Completed   0          127m   17-3-0-12   ip-17-3-0-12   <none>           <none>
kube-system   helm-install-rke2-ingress-nginx-wfxgx                   0/1     Completed   0          127m   10.42.0.4       ip-17-3-0-12   <none>           <none>
kube-system   helm-install-rke2-metrics-server-zrqt9                  0/1     Completed   0          127m   10.42.0.5       ip-17-3-0-12   <none>           <none>
kube-system   kube-apiserver-ip-17-3-0-12                         1/1     Running     0          126m   17-3-0-12   ip-17-3-0-12   <none>           <none>
kube-system   kube-controller-manager-ip-17-3-0-12                1/1     Running     0          126m   17-3-0-12   ip-17-3-0-12   <none>           <none>
kube-system   kube-proxy-ip-17-3-0-12                             1/1     Running     0          127m   17-3-0-12   ip-17-3-0-12   <none>           <none>
kube-system   kube-scheduler-ip-17-3-0-12                         1/1     Running     0          126m   17-3-0-12   ip-17-3-0-12   <none>           <none>
kube-system   rke2-canal-2hznp                                        2/2     Running     0          127m   17-3-0-12   ip-17-3-0-12   <none>           <none>
kube-system   rke2-coredns-rke2-coredns-76cb76d66-5pwxl               1/1     Running     0          127m   10.42.0.2       ip-17-3-0-12   <none>           <none>
kube-system   rke2-coredns-rke2-coredns-autoscaler-58867f8fc5-c9hjm   1/1     Running     0          127m   10.42.0.3       ip-17-3-0-12   <none>           <none>
kube-system   rke2-ingress-nginx-controller-88rlp                     1/1     Running     0          126m   10.42.0.8       ip-17-3-0-12   <none>           <none>
kube-system   rke2-metrics-server-6979d95f95-vslq9                    1/1     Running     0          126m   10.42.0.6       ip-17-3-0-12   <none>           <none>
```

**Closed by VestigeJ** 2022-07-19 23:18 UTC
Labels: status/more-info
