### ISSUE TITLE
flag provided but not defined: -agent-token

### ISSUE THREAD

**Issue by cloudcafetech** [rancher/rke2#2121] opened 2021-11-13 23:42 UTC
RKE2 - v1.21.6+rke2r1

- command

```rke2 etcd-snapshot --dir /caas/rk2/etcd-backup/```

- Output

```
Incorrect Usage. flag provided but not defined: -agent-token

NAME:
   rke2 etcd-snapshot - Trigger an immediate etcd snapshot

USAGE:
   rke2 etcd-snapshot command [command options] [arguments...]

COMMANDS:
   delete       Delete given snapshot(s)
   ls, list, l  List snapshots
   prune        Remove snapshots that exceed the configured retention count
   save         Trigger an immediate etcd snapshot

OPTIONS:
   --debug                                              (logging) Turn on debug logs [$RKE2_DEBUG]
   --config FILE, -c FILE                               (config) Load configuration from FILE (default: "/etc/rancher/rke2/config.yaml") [$RKE2_CONFIG_FILE]
   --log value, -l value                                (logging) Log to file
   --alsologtostderr                                    (logging) Log to standard error as well as file (if set)
   --node-name value                                    (agent/node) Node name [$RKE2_NODE_NAME]
   --data-dir value, -d value                           (data) Folder to hold state (default: "/var/lib/rancher/rke2")
   --name value                                         (db) Set the base name of the etcd on-demand snapshot (appended with UNIX timestamp). (default: "on-demand")
   --s3, --etcd-s3                                      (db) Enable backup to S3
   --s3-endpoint value, --etcd-s3-endpoint value        (db) S3 endpoint url (default: "s3.amazonaws.com")
   --s3-endpoint-ca value, --etcd-s3-endpoint-ca value  (db) S3 custom CA cert to connect to S3 endpoint
   --s3-skip-ssl-verify, --etcd-s3-skip-ssl-verify      (db) Disables S3 SSL certificate validation
   --s3-access-key value, --etcd-s3-access-key value    (db) S3 access key [$AWS_ACCESS_KEY_ID]
   --s3-secret-key value, --etcd-s3-secret-key value    (db) S3 secret key [$AWS_SECRET_ACCESS_KEY]
   --s3-bucket value, --etcd-s3-bucket value            (db) S3 bucket name
   --s3-region value, --etcd-s3-region value            (db) S3 region / bucket location (optional) (default: "us-east-1")
   --s3-folder value, --etcd-s3-folder value            (db) S3 folder
   --s3-insecure, --etcd-s3-insecure                    (db) Disables S3 over HTTPS
   --s3-timeout value, --etcd-s3-timeout value          (db) S3 timeout (default: 30s)
   --dir value, --etcd-snapshot-dir value               (db) Directory to save etcd on-demand snapshot. (default: ${data-dir}/db/snapshots)
   --help, -h                                           show help

FATA[0000] flag provided but not defined: -agent-token
```

**Comment by brandond** [comment] 2021-11-16 00:32
Duplicate of https://github.com/rancher/rke2/issues/2103

**Closed by brandond** 2021-11-16 00:32 UTC

**Comment by cloudcafetech** [comment] 2021-11-16 00:43
@brandond 
Is there any old version (1.21) I can use which don't have this issue?

**Comment by brandond** [comment] 2021-11-16 08:48
You can go back to the previous release in whatever branch you're using, or wait until the end of the week for the next one.

**Comment by cloudcafetech** [comment] 2021-11-16 08:52
v1.21.5+rke2r1 ? Is this OK
