### ISSUE TITLE
ClusterRole calico-node is missing a number of RBAC permissions

### ISSUE THREAD

**Issue by benc-uk** [rancher/rke2#1249] opened 2021-07-06 13:38 UTC
**Environmental Info:**
RKE2 Version: rke2 version v1.20.8+rke2r1 (53564f7b22271ced120480dd5f4c9d76d14ed2d3)

Node(s) CPU architecture, OS, and Version: 
Linux server 5.8.0-1036-azure #38~20.04.1-Ubuntu SMP Thu Jun 17 14:14:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 server node, 1 agent node

**Describe the bug:**
The calico-node ClusterRole is missing a number of permissions which results in several pods being stuck ContainerCreating
e.g.
```
Failed to create pod sandbox: rpc error:
code = Unknown desc = failed to setup network for sandbox "da805874bc3450c7bc1701b964b54ffdc8cb8c4c2064c88394d09d49
b7ba5035": connection is unauthorized: ipamconfigs.crd.projectcalico.org "default" is forbidden: User "system:servi
ceaccount:kube-system:canal" cannot get resource "ipamconfigs" in API group "crd.projectcalico.org" at the cluster
scope
```

The missing permissions are for ipamconfigs & blockaffinities

**Steps To Reproduce:**

- Installed RKE2 from https://docs.rke2.io/install/quickstart/
- Ran kubectl get po -A
- See an number of pods (helm-install-rke2-ingress-nginx, helm-install-rke2-metrics-server, rke2-coredns-rke2-coredns) all stuck ContainerCreating
- describing the pods results in errors described

**Expected behavior:**
Pods start without any additional config

**Actual behavior:**

**Additional context / logs:**

**Comment by benc-uk** [comment] 2021-07-06 13:40
Attached is a YAML which fixes this ClusterRole
[calico-node.yaml.txt](https://github.com/rancher/rke2/files/6770424/calico-node.yaml.txt)

**Comment by brandond** [comment] 2021-07-06 19:38
@manuelbuil can you take a look at this? I believe the Tigera Operator is responsible for creating this RBAC, as the Helm chart only contains RBAC for the operator itself.

**Comment by manuelbuil** [comment] 2021-07-07 09:01
@benc-uk you are deploying with standard config? Or are you changing the cni config to deploy calico? If so, how are you doing so?

**Comment by benc-uk** [comment] 2021-07-08 10:56
@manuelbuil I just ran the quick start https://docs.rke2.io/install/quickstart/
No changes to CNI configuration, everything is vanilla

**Comment by manuelbuil** [comment] 2021-07-09 08:22
It seems like an intermittent problem, I can't reproduce it but I had seen it once and redeploying fixed it. Perhaps this is triggered by a race condition. @benc-uk do you see it every time you deploy?

**Comment by benc-uk** [comment] 2021-07-09 08:37
No I was going to update and say sometimes it deploys fine.
I'm doing some automation/IaC on this so have deployed the cluster from scratch *many* times over the last few days and only see it sometimes

**Comment by caroline-suse-rancher** [comment] 2023-06-29 23:15
Closing due to age and apparent resolution

**Comment by caroline-suse-rancher** [comment] 2023-06-29 23:15
Closing due to age and apparent resolution

**Closed by caroline-suse-rancher** 2023-06-29 23:15 UTC
