### ISSUE TITLE
etcd-snapshot --s3 should use the rke2-server config files s3 settings

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rke2#1629] opened 2021-08-13 05:15 UTC
**Is your feature request related to a problem? Please describe.**
Would like to kick off an on demand s3 snapshot but the cli requires all the same s3 arguments that are already in the server config yaml file.

**Describe the solution you'd like**
Allow the rke2 etcd-snapshot --s3 command to read from the default server config file and use the same settings that are used by the scheduled snapshot. 

**Describe alternatives you've considered**
None

**Comment by brandond** [comment] 2021-08-13 05:43
Duplicate of #1628

**Closed by brandond** 2021-08-13 05:43 UTC
