### ISSUE TITLE
Windows: Agent version is reported as v1.21.3 instead of v1.21.4+rke2r2

### ISSUE THREAD

**Issue by rgl** [rancher/rke2#1763] opened 2021-09-07 06:04 UTC
**Environmental Info:**

RKE2 Version: 

```
I0907 09:32:00.966089    5540 ipsec_windows.go:20] ipsec is not supported on this platform
rke2.exe version v1.21.4+rke2r2 (d5746a33b001dcf1a24cd3256e9f1df2a43ff3dd)
go version go1.16.6b7
```

Node(s) CPU architecture, OS, and Version: 

AMD64. Windows 2019 1809.

Cluster Configuration:

1 Server Ubuntu 20.04 node.
1 Agent Windows 2019 1809 node.

**Describe the bug:**

The Windows agent nodes returned by `kubectl get nodes` report their `VERSION` as `v1.21.3` instead of `v1.21.4+rke2r2`.

**Steps To Reproduce:**

- Install RKE2 as described at https://docs.rke2.io/install/quickstart/ and explicitly set the version as:

```powershell
.\install.ps1 `
    -Version 'v1.21.4+rke2r2' `
    -Type agent
```

**Expected behavior:**

`kubectl get nodes` to return the expected `VERSION` `v1.21.4+rke2r2` instead of `v1.21.3`.

**Actual behavior:**

```console
root@u0:~# kubectl get nodes -o wide
NAME   STATUS   ROLES                       AGE     VERSION          INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                                  KERNEL-VERSION     CONTAINER-RUNTIME
u0     Ready    control-plane,etcd,master   13h     v1.21.4+rke2r2   10.1.2.134   <none>        Ubuntu 20.04.2 LTS                        5.4.0-80-generic   containerd://1.4.8-k3s1
u1     Ready    <none>                      13h     v1.21.4+rke2r2   10.1.2.184   <none>        Ubuntu 20.04.2 LTS                        5.4.0-80-generic   containerd://1.4.8-k3s1
w0     Ready    <none>                      58m     v1.21.3          10.1.2.197   <none>        Windows Server 2019 Standard Evaluation   10.0.17763.2061    containerd://1.5.4
```

**Comment by brandond** [comment] 2021-09-07 07:15
Duplicate of https://github.com/rancher/rke2/issues/1744

**Closed by brandond** 2021-09-07 07:15 UTC
