### ISSUE TITLE
RKE2 [DOC] - Containerd needs the apparmor packet to run

### ISSUE THREAD

**Issue by qdupuy** [rancher/rke2#1888] opened 2021-09-29 13:39 UTC
Hello,

Would it be possible to update your documentation ?

Containerd needs the apparmor packet to run.

Example log:

```
time="2021-09-18T15:00:31.089596546+02:00" level=error msg="CreateContainer within sandbox \"a2dab68fda99df23ee88bb003e18dc5f09065bfc5d58a346b8d8ea9a17c715f8\" for &ContainerMetadata{Name:etcd,Attempt:0,} failed" error="failed to create containerd container: get apparmor_parser version: exec: \"apparmor_parser\": executable file not found in $PATH"
```

PS : I'm running on debian 10 and latest version of rke2

**Comment by brandond** [comment] 2021-09-29 18:28
Duplicate of #1806

**Closed** 2021-09-29 18:28 UTC

**Comment by vmoutoussamy** [comment] 2021-11-16 14:19
why was this issue closed? https://github.com/rancher/rke2/issues/1806 is not mentioning or dealing with doc at all..
Could you please confirm that this will be documented? Please reopen this issue if it's a yes.
