### ISSUE TITLE
rke2 agent Kubelet exited: exit status 1 in selinux true hardened environment

### ISSUE THREAD

**Issue by uchalasani** [rancher/rke2#4512] opened 2023-07-26 19:38 UTC
**Environmental Info:**
RKE2 Version: 
v1.27.2+rke2r1

Node(s) CPU architecture, OS, and Version: 

Linux ktdso1 3.10.0-1160.92.1.el7.x86_64 #1 SMP Tue Jun 20 11:48:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Linux ktdso2 3.10.0-1160.92.1.el7.x86_64 #1 SMP Tue Jun 20 11:48:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

I tested with all 3 server nodes. That seems to come up fine. But when I uninstalled and re-installing with either 2servers/1agent or 1server/2agents, Only the first server is coming up.

**Describe the bug:**

Only first server node comes up and the remaining are failing to join the cluster.
journalctl -u rke2-agent -f
-- Logs begin at Wed 2023-07-26 14:58:44 EDT. --
Jul 26 15:22:13 ktdso2 rke2[1527]: time="2023-07-26T15:22:13-04:00" level=error msg="Kubelet exited: exit status 1"
Jul 26 15:22:18 ktdso2 rke2[1527]: time="2023-07-26T15:22:18-04:00" level=error msg="Kubelet exited: exit status 1"

**Steps To Reproduce:**

- Installed RKE2: 
**using First Server config file and Tar method using Ansible:**
```yaml
node-label:
  - "nodeload=control"
debug: false
write-kubeconfig-mode: "0644"
cluster-cidr: "10.42.0.0/16"
service-cidr: "10.43.0.0/16"
token: <CustomPrefix>-rke2-v1-27-2-2023-07-10
tls-san:
  - rancher.<PrivateDomain>
  - 127.0.0.1
node-taint:
  - "CriticalAddonsOnly=true:NoExecute"
selinux: true
system-default-registry: "<PrivateDockerRegistryServerName>:5000"
```

**Second Agent Node config file:**
```yaml
token: <CustomPrefix>-rke2-v1-27-2-2023-07-10
server: https://rancher.<PrivateDomain>:9345
write-kubeconfig-mode: "0644"
tls-san:
  - rancher.<PrivateDomain>
  - 127.0.0.1
node-label:
  - "nodeload=medium"
  - "node-role.kubernetes.io/worker=true"
selinux: true
```

**Expected behavior:**

kubectl get nodes -o wide: .hould display all 3 nodes/

**Actual behavior:**

See only 1 first server node shows up, but not the rest of the 2 more nodes.
kubectl get nodes -o wide
NAME     STATUS   ROLES                       AGE   VERSION          INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME
ktdso1   Ready    control-plane,etcd,master   46m   v1.27.2+rke2r1   <Private IP>   <none>        CentOS Linux 7 (Core)   3.10.0-1160.92.1.el7.x86_64   containerd://1.7.1-k3s1

**Additional context / logs:**

None

**Comment by brandond** [comment] 2023-07-26 19:43
```yaml
node-label:
  - "nodeload=medium"
  - "node-role.kubernetes.io/worker=true"
```

Duplicate of https://github.com/rancher/rke2/issues/3730#issuecomment-1368077700 - see the discussion posted in that comment.

**Closed by brandond** 2023-07-26 19:43 UTC

**Comment by uchalasani** [comment] 2023-07-27 20:16
@brandond Thanks for your help. I was able to deploy 3 node cluster with RKE2 v1.27.2 successfully. My real test is I am supposed to upgrade Production from RKE2 v1.23.9 RKE2 v1.27.2. I uninstalled all the nodes. When I installed on the first server, It is not coming up. FYI I was using the above "First Server config" above with a taint. I removed Taint, still it had the same issue. Is there anything specific I am missing SELinux Enforcing environment?

**Comment by brandond** [comment] 2023-07-27 21:06
Check the etcd pod logs under /var/log/pods?  Is this just normal selinux hardening, or have you done some DISA STIG type stuff on here as well?

**Comment by uchalasani** [comment] 2023-07-28 13:49
There are no entries in both etcd logs:
```
ls -l kube-system_etcd-ktdso1_*/etcd/
kube-system_etcd-ktdso1_b486f2d6347835bec5c4099a2adc47dd/etcd/:
total 0
-rw-r-----. 1 root root 0 Jul 28 09:44 466.log

kube-system_etcd-ktdso1_ff5f43f5f0f28451be2bc86e2a4b4a5a/etcd/:
total 0
-rw-r-----. 1 root root 0 Jul 27 15:39 28.log
[root@ktdso1 pods]# less kube-system_etcd-ktdso1_*/etcd/28.log
```

I was told these VM's were created with stig gold image. I will check and confirm.

**Comment by uchalasani** [comment] 2023-07-31 18:03
Thanks for all your help! I finally was able to resolve issues. All are working fine now.

**Comment by brandond** [comment] 2023-07-31 18:05
Can you help the next person, and provide some information on what the problem was, and how you solved it?

**Comment by uchalasani** [comment] 2023-07-31 18:11
I searched for the issues based on the containrd logs. One of the key issues was rke2-uninstall.sh is not removing the following 2 files. I had to remove manually.
`rm -rf /var/lib/calico /var/run/calico
`
After this, I was able to install RKE2 cluster just fine. I did not find any issues so far.
