### ISSUE TITLE
CIS 1.6 hardened scan - 5.1.5 test - fails on a rke2 hardened local cluster with Rancher installed

### ISSUE THREAD

**Issue by briandowns** [rancher/rke2#1181] opened 2021-06-24 04:32 UTC
What kind of request is this (question/bug/enhancement/feature request): bug

Steps to reproduce (least amount of steps as possible):

* Deploy an rke2 cluster - selinux enabled cis mode on, CENTOS nodes
* RKE2 version - v1.21.1-rc1+rke2r1
* Deploy Rancher on it
* Run CIS scan on the hardened local cluster.
* 5.1.5 test fails.
* Namespaces breaking 5.1.5 test

```sh
kubectl get serviceaccounts --all-namespaces -o json | jq -r '.items[] | select(.metadata.name=="default") | select((.automountServiceAccountToken == null) or (.automountServiceAccountToken == true))' | jq .metadata.namespace
"cluster-fleet-local-local-1a3d67d0a899"
"default"
"fleet-clusters-system"
"fleet-default"
"fleet-local"
"kube-system"
"local"
"p-5k9v9"
"p-nznr2"
"rancher-operator-system"
"user-2dnhl"
```

**Expected Result**:
all tests should pass.

**Environment information**

Rancher version (rancher/rancher/rancher/server image tag or shown bottom left in the UI): 2.5.8
Installation option (single install/HA): HA

**Comment by cjellick** [comment] 2021-06-26 00:13
This is partially a duplicate of https://github.com/rancher/rke2/issues/549

Early in RKE2, we chose to not immediately implement the remediation for this particular control. We can pick that up. When we do, we will effectively just implement in code what we outline here: https://docs.rke2.io/security/hardening_guide/#control-515

That will fix the built-in namespaces kube-system, kube-public, kube-node-lease, and default. However, the other namespaces listed are rancher specific and we need to work with the rancher core team about how they want to handle those. Those would fail regardless of the underlying local cluster (eks, rke2, rke1, k3s).

**Comment by cjellick** [comment] 2021-06-26 00:15
I want to close this issue since we have #549 and the rest will need to be handle by the rancher core team, but let's wait until we triage as a team.

**Comment by cjellick** [comment] 2021-06-29 15:29
closing, based on my above assesment

**Closed by cjellick** 2021-06-29 15:29 UTC
