### ISSUE TITLE
RKE2 crashes on startup with `CRNGT failed` on Linux guests under Windows 10 Pro HyperV

### ISSUE THREAD

**Issue by chillwinston** [rancher/rke2#3327] opened 2022-09-10 04:15 UTC
**Environmental Info:**
RKE2 Version: 
As per this page 10 Sep 2022
https://docs.rke2.io/install/quickstart/

Node(s) CPU architecture, OS, and Version: 
Single node, AMD64, 8Gb RAM, 32 cores, fast SSD
HyperV, Win 10 Pro
Guest OSes tried (as per prerequisites for RKE2)
https://docs.rke2.io/install/requirements/
Ubuntu 20.04 and Ubuntu 18.04
Centos (RHEL) 7.8
In every case the following error:
....
....
Installed:
  rke2-server.x86_64 0:1.24.4~rke2r1-0.el7                                                                          

Dependency Installed:
  container-selinux.noarch 2:2.119.2-1.911c772.el7_8            rke2-common.x86_64 0:1.24.4~rke2r1-0.el7           
  rke2-selinux.noarch 0:0.9-1.el7                              

Complete!
[root@localhost david]# systemctl enable rke2-server.service
Created symlink from /etc/systemd/system/multi-user.target.wants/rke2-server.service to /usr/lib/systemd/system/rke2-server.service.
[root@localhost david]# systemctl start rke2-server.service
Job for rke2-server.service failed because the control process exited with error code. See "systemctl status rke2-server.service" and "journalctl -xe" for details.

journalctl:
```
....
-- Unit rke2-server.service has begun starting up.
Sep 10 14:10:16 ub18rke2.modem sh[19840]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Sep 10 14:10:16 ub18rke2.modem sh[19840]: Failed to get unit file state for nm-cloud-setup.service: No such file or 
Sep 10 14:10:16 ub18rke2.modem rke2[19850]: CRNGT failed.
Sep 10 14:10:16 ub18rke2.modem rke2[19850]: SIGABRT: abort
Sep 10 14:10:16 ub18rke2.modem rke2[19850]: PC=0x52674a4 m=0 sigcode=18446744073709551610
Sep 10 14:10:16 ub18rke2.modem rke2[19850]: signal arrived during cgo execution
Sep 10 14:10:16 ub18rke2.modem rke2[19850]: goroutine 1 [syscall, locked to thread]:
Sep 10 14:10:16 ub18rke2.modem rke2[19850]: runtime.cgocall(0x50272c0, 0xc000b1f218)
Sep 10 14:10:16 ub18rke2.modem rke2[19850]: /usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc000b1f1f0 sp=0xc000
Sep 10 14:10:16 ub18rke2.modem rke2[19850]: crypto/internal/boring._Cfunc__goboringcrypto_RAND_bytes(0xc000c00010, 0
Sep 10 14:10:16 ub18rke2.modem rke2[19850]: _cgo_gotypes.go:1140 +0x4c fp=0xc000b1f218 sp=0xc000b1f1f0 pc=0x66f46c
Sep 10 14:10:16 ub18rke2.modem rke2[19850]: crypto/internal/boring.randReader.Read(0x7efbd0c456c0, {0xc000c00010?, 0
Sep 10 14:10:16 ub18rke2.modem rke2[19850]: /usr/local/go/src/crypto/internal/boring/rand.go:19 +0x31 fp=0xc000b1f24
Sep 10 14:10:16 ub18rke2.modem rke2[19850]: crypto/internal/boring.(*randReader).Read(0xc0000021a0?, {0xc000c00010?,
Sep 10 14:10:16 ub18rke2.modem rke2[19850]: <autogenerated>:1 +0x2f fp=0xc000b1f270 sp=0xc000b1f240 pc=0x67c00f
Sep 10 14:10:16 ub18rke2.modem rke2[19850]: io.ReadAtLeast({0x73fa2c0, 0x73d7b08}, {0xc000c00010, 0x8, 0x8}, 0x8)
Sep 10 14:10:16 ub18rke2.modem rke2[19850]: /usr/local/go/src/io/io.go:331 +0x9a fp=0xc000b1f2b8 sp=0xc000b1f270 pc=
Sep 10 14:10:16 ub18rke2.modem rke2[19850]: io.ReadFull(...)
Sep 10 14:10:16 ub18rke2.modem rke2[19850]: /usr/local/go/src/io/io.go:350
Sep 10 14:10:16 ub18rke2.modem rke2[19850]: crypto/rand.Int({0x73fa2c0, 0x73d7b08}, 0xc000b1f370)
.....
...
Sep 10 14:10:16 ub18rke2.modem rke2[19850]: fs     0x0
Sep 10 14:10:16 ub18rke2.modem rke2[19850]: gs     0x0
Sep 10 14:10:16 ub18rke2.modem systemd[1]: Failed to start Rancher Kubernetes Engine v2 (server).
-- Subject: Unit rke2-server.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit rke2-server.service has failed.
-- 
-- The result is failed.
Sep 10 14:10:16 ub18rke2.modem systemd[1]: Unit rke2-server.service entered failed state.
Sep 10 14:10:16 ub18rke2.modem systemd[1]: rke2-server.service failed.
```

Cluster Configuration:
Quickstart only as above. No cluster

**Describe the bug:**
Service fails to start
Bizarrely this may be related to the random function as referenced in the stack trace

**Steps To Reproduce:**
- Install OS as above
- run quick start

- Installed RKE2: 

**Expected behavior:**
... Working system

**Actual behavior:**
.... Not working system

**Additional context / logs:**
Logs as above

**Comment by brandond** [comment] 2022-09-10 05:30
> `CRNGT failed.`

The cryptograph random number generator of your virtualization platform is insecure, and fails startup checks by returning the same sequence of random bytes on multiple reads. This appears to be a duplicate of https://github.com/rancher/rke2/issues/3312#issuecomment-1235974654, except with HyperV instead of QEMU.

**Comment by chillwinston** [comment] 2022-09-10 07:29
So - If I read between the lines of your statement:

DEVELOPMENT PHASE
1. At some point use of the hardware random number generator was made
2. It was checked with code to ensure it MUST be present or the system fails

TEST PHASE PRIOR TO RELEASE

1. Testing was made under either bare-metal Linux environments or a limited number of virtualisation frameworks
2. Testing passed
3. Code was released to production (the website)

Can you confirm:
1. The list of test systems that the RKE2 was tested under.  This includes the virtualisation frameworks / products that are supported.  I note that "HyperV is not supported" is never mentioned on the prerequisites page in any prominent position
2. The testing process for RKE2 and where this is documented

REQUEST:
- Please raise a change on the documentation team to update the "PREREQUISITES" page to include "HyperV not supported due to hardware random number generation support".

**Comment by brandond** [comment] 2022-09-10 17:33
> If I read between the lines of your statement

No. We develop, build, and test RKE2 extensively on VMs from many different providers, including both of the affected platforms. At no point did I say or imply that virtualization is not supported. We actually don't cover virtualization platforms in our support matrix; up to this point we have not had problems with any of them. I'm not sure why we are just now encountering this issue, but I would recommend avoid drawing any sweeping conclusions from it.

As discussed in the other issue I linked to, we use goboring, which performs FIPS compliance checks of the RNG at startup:
> FIPS requires that the output of the entropy source be checked to ensure that no two n-bit blocks are equal.

It has done so for 5 years - longer than RKE2 has existed, so this is not new behavior or something we have changed in our product. Since this problem is seen across multiple operating systems when using affected virtualization platforms, I suspect that there have been some recent changes to the hardware RNG support on that side.

**Comment by chillwinston** [comment] 2022-09-11 01:11
I will test HyperV later today on Server 2019 with RKE2 and if that also fails then I will change the bug title back to my clearer statement of lack of support.   Your current title does not prevent a new user of RKE2 from burning time trying to resolve the issue, whereas a clear statement of lack of HyperV support will.   

Frankly, my biggest frustration is having lost a number of hours of work on what appears to be a product issue due potentially to a lack of testing prior to release.  I am likely one of a number of people that burnt time due to this bug, meaning that this particular bug has wasted the time of a large group of people - all because the product was released without testing if it actually worked in one of the most common hypervisor scenarios.  RKE2 should be automatically tested on each HyperV update.  This is a standard approach to DevSecOps and build and test automation.

At this time I feel like a test team member burning time rather than a consumer of a product where I am (rightfully) expecting stability and quality of that product.  Hence my request for details of the testing processes for RKE.  I would assume such processes are documented along with OS versions and hypervisors.  Note that virtually no major project of any form today will launch on bare metal, so hypervisor systems should be the first and most highly tested of platforms rather than the last.  One of the largest cloud providers is Azure with HyperV - so again, it should be tested more completely than other vastly smaller user-base hypervisors such as QEMU.

It seems highly unusual that two virtualisation providers - HyperV and QEMU - and would both  change their hardware RNG support at virtually the same time.   The one constant here is the RKE2 product and is therefore the more likely source of fault.  

The simplest mechanism to understand whether a product change is at fault is to try the previous production-grade release of RKE2 on any one of the OS's mentioned under current HyperV.   

As mentioned, I'd appreciate the following as you seem to have ignored this request on my previous message:
1. Please provide the testing processes for RKE2.  I'm afraid that stating that "...We develop, build, and test RKE2 extensively on VMs from many different providers..." is vastly insufficient detail of those processes.  These processes should be documented and I would expect publicly so.  A  "release gate" approach to production release is typically used that provides details of the conditions for a release to attain production readiness for release to users.  I would appreciate viewing those release gate requirements.
2. I bring up this requirement for details of the testing processes as I have personally had issues with another Suse-Rancher product: Longhorn.  In that case it was a large project unrelated to RKE2 yet also had in-production issues that turned out to be Longhorn.  Longhorn is a current issue for that project.

**Comment by brandond** [comment] 2022-09-11 04:35
To be clear, this issue would affect anything using goboring/boringssl, and is not a defect in rke2. The FIPS test has identified an issue in your virtualization platform that prevents it from being suitable for use in hardened environments.

**Comment by chillwinston** [comment] 2022-09-11 05:42
Also to be clear: a defect in a subcomponent of a product that prevents that product from working is a bug in the product itself, and brushing it off as "not a defect in RKE2" is a **falsehood**.  I am not "brushing this off as a bug".  It's a bug, and significant one.  If anyone is brushing it off - it is not me.  Both the change in title that you made and the way that all your responses have been couched as "issues in the hypervisor", as well as your refusal twice to provide any details of testing standards appears to me an evasion of responsibility as well as seeking to be the absolute opposite of "open source" in terms of development transparency.

Incidentally - I have tried this now on a non-cloud based server, Intel based, using Server 2019 Hyper V.  RKE successfully installed and started.   Note that the QEMU ticket referenced a 3900 series AMD CPU.  I also have a 3900 series AMD CPU.

From your responses this will ticket will be not be resolved.  I am stopping evaluation of RKE2 at this stage.

**Comment by brandond** [comment] 2022-09-12 19:23
> I am stopping evaluation of RKE2 at this stage.

OK, thanks! I'll leave the issue open in case someone wants to chase this down further and confirm whether or not it affects HyperV on actual server platforms or different CPUs.

**Comment by brandond** [comment] 2022-09-12 20:28
FWIW, I just did a quick test on a WIndows 11 Pro workstation:

```console
root@hyperv-ubuntu01:~# dmidecode -s bios-version
Hyper-V UEFI Release v4.1

root@hyperv-ubuntu01:~# curl -ksL get.rke2.io | sh -s
[INFO]  finding release for channel stable
[INFO]  using v1.24.4+rke2r1 as release
[INFO]  downloading checksums at https://github.com/rancher/rke2/releases/download/v1.24.4+rke2r1/sha256sum-amd64.txt
[INFO]  downloading tarball at https://github.com/rancher/rke2/releases/download/v1.24.4+rke2r1/rke2.linux-amd64.tar.gz
[INFO]  verifying tarball
[INFO]  unpacking tarball file to /usr/local

root@hyperv-ubuntu01:~# systemctl start --no-block rke2-server

root@hyperv-ubuntu01:~# KUBECONFIG=/etc/rancher/rke2/rke2.yaml /var/lib/rancher/rke2/bin/kubectl get node -o wide
NAME              STATUS   ROLES                       AGE   VERSION          INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
hyperv-ubuntu01   Ready    control-plane,etcd,master   57s   v1.24.4+rke2r1   10.0.1.200    <none>        Ubuntu 22.04.1 LTS   5.15.0-1019-azure   containerd://1.6.6-k3s1
```

So yeah, I continue to assert that this is an issue with your HyperV configuration.

**Closed** 2022-09-12 20:49 UTC
