### ISSUE TITLE
tarball uninstall.sh doesnt remove /var/lib/rancher

### ISSUE THREAD

**Issue by cjellick** [rancher/rke2#471] opened 2020-10-06 20:26 UTC
it removes everythign under that directory, but not that directory

it also leaves behind /etc/rancher/...something something/none..something. is that intnetional?

**Comment by rancher-max** [comment] 2021-01-19 23:21
https://github.com/rancher/rke2/pull/626 was merged to address this, but on a freshly installed cluster on an Ubuntu 20.04 system, this is not yet resolved as I see the `/var/lib/rancher` directory still present even though I didn't have any other directories or files in it.

**Comment by davidnuzik** [comment] 2021-01-19 23:48
FYI @innobead @c3y1huang we need to follow proper process with GitHub. Please reach out to me on Slack if you have questions. Assigning this back to @c3y1huang and reopening.

**Comment by brandond** [comment] 2021-02-18 21:08
I have been unable to reproduce this with tarball or rpm install on EL7 or tarball on Ubuntu, using either the stable or testing channels.

```
+ uninstall_remove_files
+ [ -r /etc/redhat-release ]
+ [ -r /etc/centos-release ]
+ [ -r /etc/oracle-release ]
+ find /usr/local/lib/systemd/system -name rke2-*.service -type f -delete
+ rm -f /usr/local/bin/rke2
+ rm -f /usr/local/bin/rke2-killall.sh
+ rm -rf /usr/local/share/rke2
+ rm -rf /etc/rancher/rke2
+ rm -rf /etc/rancher/node
+ rm -d /etc/rancher
+ rm -rf /var/lib/kubelet
+ rm -rf /var/lib/rancher/rke2
+ rm -d /var/lib/rancher
+ uninstall_remove_self
+ rm -f /usr/local/bin/rke2-uninstall.sh


root@ubuntu01:~# find /var/lib/rancher
find: ‘/var/lib/rancher’: No such file or directory
```

**Comment by rancher-max** [comment] 2021-02-18 22:02
I can no longer recreate this either, so looks like it's working as intended now

**Closed by rancher-max** 2021-02-18 22:02 UTC
Labels: [zube]: To Test
