### ISSUE TITLE
Cilium Operator deploys with scale of 2 by default

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#933] opened 2021-04-29 18:24 UTC
This is purely cosmetic. In a single node cluster there will be one cilium-operator pod stuck in Pending state since there is not another node available to schedule:

```
$ k get all -n kube-system
NAME                                                     READY   STATUS      RESTARTS   AGE
pod/cilium-8vtkt                                         1/1     Running     0          25h
pod/cilium-node-init-gmnkn                               1/1     Running     0          25h
pod/cilium-operator-6fccb6b48-7fm2w                      0/1     Pending     0          25h
pod/cilium-operator-6fccb6b48-whr2m                      1/1     Running     0          25h
pod/etcd-ip-172-31-32-165                                1/1     Running     0          25h
pod/helm-install-rke2-cilium-s44fh                       0/1     Completed   0          25h
pod/helm-install-rke2-coredns-tcrbk                      0/1     Completed   0          25h
pod/helm-install-rke2-ingress-nginx-zb7mh                0/1     Completed   0          25h
pod/helm-install-rke2-kube-proxy-v7d49                   0/1     Completed   0          25h
pod/helm-install-rke2-metrics-server-p7xhq               0/1     Completed   0          25h
pod/kube-apiserver-ip-172-31-32-165                      1/1     Running     0          25h
pod/kube-controller-manager-ip-172-31-32-165             1/1     Running     0          25h
pod/kube-proxy-sl7jt                                     1/1     Running     0          25h
pod/kube-scheduler-ip-172-31-32-165                      1/1     Running     0          25h
pod/rke2-coredns-rke2-coredns-9d9bf756f-qkxhw            1/1     Running     0          25h
pod/rke2-ingress-nginx-controller-54946dd48f-fhdn5       1/1     Running     0          25h
pod/rke2-ingress-nginx-default-backend-5795954f8-5nhjl   1/1     Running     0          25h
pod/rke2-metrics-server-559dc47bd8-6k2k5                 1/1     Running     0          25h

NAME                                         TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)         AGE
service/cilium-agent                         ClusterIP   None           <none>        9095/TCP        25h
service/rke2-coredns-rke2-coredns            ClusterIP   10.43.0.10     <none>        53/UDP,53/TCP   25h
service/rke2-ingress-nginx-default-backend   ClusterIP   10.43.151.42   <none>        80/TCP          25h
service/rke2-metrics-server                  ClusterIP   10.43.16.91    <none>        443/TCP         25h

NAME                              DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
daemonset.apps/cilium             1         1         1       1            1           <none>                   25h
daemonset.apps/cilium-node-init   1         1         1       1            1           <none>                   25h
daemonset.apps/kube-proxy         1         1         1       1            1           kubernetes.io/os=linux   25h

NAME                                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/cilium-operator                      1/2     2            1           25h
deployment.apps/rke2-coredns-rke2-coredns            1/1     1            1           25h
deployment.apps/rke2-ingress-nginx-controller        1/1     1            1           25h
deployment.apps/rke2-ingress-nginx-default-backend   1/1     1            1           25h
deployment.apps/rke2-metrics-server                  1/1     1            1           25h

NAME                                                           DESIRED   CURRENT   READY   AGE
replicaset.apps/cilium-operator-6fccb6b48                      2         2         1       25h
replicaset.apps/rke2-coredns-rke2-coredns-9d9bf756f            1         1         1       25h
replicaset.apps/rke2-ingress-nginx-controller-54946dd48f       1         1         1       25h
replicaset.apps/rke2-ingress-nginx-default-backend-5795954f8   1         1         1       25h
replicaset.apps/rke2-metrics-server-559dc47bd8                 1         1         1       25h

NAME                                         COMPLETIONS   DURATION   AGE
job.batch/helm-install-rke2-cilium           1/1           18s        25h
job.batch/helm-install-rke2-coredns          1/1           16s        25h
job.batch/helm-install-rke2-ingress-nginx    1/1           66s        25h
job.batch/helm-install-rke2-kube-proxy       1/1           15s        25h
job.batch/helm-install-rke2-metrics-server   1/1           65s        25h
```

**Comment by lowmanb** [comment] 2021-11-10 15:00
I'm attempting to fix this issue on `v1.22.3+rke2r1` using the following HelmChartConfig:

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: disabled
    operator:
      replicas: 1
```
While the `kubeProxyReplacement` value is set (confirmed by inspecting the cilium ConfigMap), I still get two replicas.

The Cilium 1.10.4 `values.yaml` does contain the [`operator.replicas` value](https://github.com/cilium/cilium/blob/v1.10.4/install/kubernetes/cilium/values.yaml#L1225). Based on [this line](https://github.com/rancher/rke2/blob/v1.22.3%2Brke2r1/Dockerfile#L98) in the rke2 `Dockerfile`, I'm believe that rke2 is using rke2-charts version `04` defined [here](https://github.com/rancher/rke2-charts/blob/main-source/packages/rke2-cilium/package.yaml#L2), which [has a dependency](https://github.com/rancher/rke2-charts/blob/main-source/packages/rke2-cilium/charts/requirements.yaml#L3) on the [cilium `1.10.4`](https://github.com/rancher/rke2-charts/blob/main-source/packages/cilium/package.yaml#L1) chart (`1.10.4 + 04 = 1.10.404)`.

Am I missing something?

**Comment by brandond** [comment] 2021-11-10 17:28
Its actually packaged as a subchart of the rke2-cilium chart: https://github.com/rancher/rke2-charts/tree/main/charts/rke2-cilium/rke2-cilium/1.10.404

I'm not quite sure how to pass options to a subchart. @manuelbuil might you know?

**Comment by manuelbuil** [comment] 2021-11-10 18:21
> Its actually packaged as a subchart of the rke2-cilium chart: https://github.com/rancher/rke2-charts/tree/main/charts/rke2-cilium/rke2-cilium/1.10.404
> 
> I'm not quite sure how to pass options to a subchart. @manuelbuil might you know?

Exactly, we are using subchartting to show only the supported variables. However, it is still possible to change all variables. If I remember correctly, the way to do it is by adding cilium to the top hierarchy. Can you test this one:
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    cilium:
      kubeProxyReplacement: disabled
      operator:
        replicas: 1
```

**Comment by lowmanb** [comment] 2021-11-11 03:47
@manuelbuil Your suggestion worked. Thanks!

**Comment by caroline-suse-rancher** [comment] 2023-04-13 16:07
Closing as it looks like the workaround is sufficient

**Closed by caroline-suse-rancher** 2023-04-13 16:07 UTC
Labels: status/2023 confirmed
