### ISSUE TITLE
CPU usage 100%

### ISSUE THREAD

**Issue by asm76** [rancher/rke2#57] opened 2020-07-03 14:06 UTC
Hi! I am using
```
curl https://raw.githubusercontent.com/rancher/rke2/master/install.sh | INSTALL_RKE2_VERSION=v0.0.1-alpha.5 sh -
```
command to start single-node cluster on Ubuntu 20.04 VM (1 CPU, 2GB RAM) .

When canal helm charts is deployed CPU usage is 100% and logs full of

```
Jul 03 13:32:49 rke2-1 systemd-udevd[3692]: calico_tmp_A: Failed to get link config: No such device
Jul 03 13:32:49 rke2-1 networkd-dispatcher[697]: ERROR:Unknown interface index 150 seen even after reload
Jul 03 13:32:49 rke2-1 networkd-dispatcher[697]: WARNING:Unknown index 151 seen, reloading interface list
Jul 03 13:32:49 rke2-1 systemd-udevd[3698]: calico_tmp_B: Failed to get link config: No such device
Jul 03 13:32:49 rke2-1 networkd-dispatcher[697]: ERROR:Unknown interface index 151 seen even after reload
Jul 03 13:32:49 rke2-1 networkd-dispatcher[697]: WARNING:Unknown index 151 seen, reloading interface list
Jul 03 13:32:49 rke2-1 systemd-networkd[569]: calico_tmp_B: Could not find device, waiting for device initialization: No such device
Jul 03 13:32:49 rke2-1 systemd-networkd[569]: calico_tmp_A: Could not find device, waiting for device initialization: No such device
Jul 03 13:32:49 rke2-1 networkd-dispatcher[697]: ERROR:Unknown interface index 151 seen even after reload
Jul 03 13:32:49 rke2-1 networkd-dispatcher[697]: WARNING:Unknown index 150 seen, reloading interface list
Jul 03 13:32:49 rke2-1 systemd-networkd[569]: calico_tmp_B: Could not find device, waiting for device initialization: No such device
Jul 03 13:32:49 rke2-1 systemd-networkd[569]: calico_tmp_A: Could not find device, waiting for device initialization: No such device
Jul 03 13:32:49 rke2-1 networkd-dispatcher[697]: ERROR:Unknown interface index 150 seen even after reload
Jul 03 13:32:49 rke2-1 networkd-dispatcher[697]: WARNING:Unknown index 152 seen, reloading interface list
Jul 03 13:32:49 rke2-1 systemd-networkd[569]: calico_tmp_B: Could not find device, waiting for device initialization: No such device
Jul 03 13:32:49 rke2-1 systemd-networkd[569]: calico_tmp_A: Could not find device, waiting for device initialization: No such device
Jul 03 13:32:49 rke2-1 networkd-dispatcher[697]: ERROR:Unknown interface index 152 seen even after reload
Jul 03 13:32:49 rke2-1 networkd-dispatcher[697]: WARNING:Unknown index 153 seen, reloading interface list
Jul 03 13:32:49 rke2-1 networkd-dispatcher[697]: ERROR:Unknown interface index 153 seen even after reload
Jul 03 13:32:49 rke2-1 networkd-dispatcher[697]: WARNING:Unknown index 153 seen, reloading interface list
Jul 03 13:32:49 rke2-1 systemd-udevd[3692]: calico_tmp_A: Failed to get link config: No such device
Jul 03 13:32:49 rke2-1 networkd-dispatcher[697]: ERROR:Unknown interface index 153 seen even after reload
Jul 03 13:32:49 rke2-1 networkd-dispatcher[697]: WARNING:Unknown index 152 seen, reloading interface list
Jul 03 13:32:50 rke2-1 systemd-udevd[3698]: calico_tmp_B: Failed to get link config: No such device
```
In calico-node container's log i see
```
2020-07-03T13:43:51.219280859Z stdout F 2020-07-03 13:43:51.217 [INFO][25660] int_dataplane.go 1258: Applying XDP actions did not succeed, disabling XDP error=failed to resync: cannot find XDP object "/usr/lib/calico/bpf/filter.o"
2020-07-03T13:43:51.311974047Z stdout F 2020-07-03 13:43:51.298 [INFO][25660] int_dataplane.go 778: Linux interface addrs changed. addrs=set.mapSet{} ifaceName="calico_tmp_B"
2020-07-03T13:43:51.312013473Z stdout F 2020-07-03 13:43:51.300 [INFO][25660] int_dataplane.go 778: Linux interface addrs changed. addrs=set.mapSet{} ifaceName="calico_tmp_A"
2020-07-03T13:43:51.325926965Z stdout F 2020-07-03 13:43:51.325 [WARNING][25660] int_dataplane.go 981: failed to wipe the XDP state error=cannot find XDP object "/usr/lib/calico/bpf/filter.o" try=0
2020-07-03T13:43:51.510189347Z stdout F 2020-07-03 13:43:51.509 [WARNING][25660] int_dataplane.go 981: failed to wipe the XDP state error=cannot find XDP object "/usr/lib/calico/bpf/filter.o" try=1
2020-07-03T13:43:51.724108398Z stdout F 2020-07-03 13:43:51.718 [WARNING][25660] int_dataplane.go 981: failed to wipe the XDP state error=cannot find XDP object "/usr/lib/calico/bpf/filter.o" try=2
2020-07-03T13:43:51.927056232Z stdout F 2020-07-03 13:43:51.913 [WARNING][25660] int_dataplane.go 981: failed to wipe the XDP state error=cannot find XDP object "/usr/lib/calico/bpf/filter.o" try=3
2020-07-03T13:43:52.102314442Z stdout F 2020-07-03 13:43:52.097 [WARNING][25660] int_dataplane.go 981: failed to wipe the XDP state error=cannot find XDP object "/usr/lib/calico/bpf/filter.o" try=4
```
`kubectl -n kube-system set env ds/canal -c calico-node FELIX_XDPENABLED=false` and reboot is fixing the problem. Looks like in `ranchertest/calico:v3.13.3` docker image is missing `/usr/lib/calico/bpf/` directory:
```
docker run --rm ranchertest/calico:v3.13.3 ls -l /usr/lib/calico
ls: cannot access /usr/lib/calico: No such file or directory
```

**Comment by briandowns** [comment] 2020-07-20 21:40
A new version of the calico node image has been pushed. We're about to release alpha12 so likely best to wait until then to retest.

**Comment by asm76** [comment] 2020-07-23 08:41
@briandowns i retested v1.18.4-alpha15+rke2 version and nothing changed.

**Comment by asm76** [comment] 2020-09-01 12:27
@briandowns How can i tell rke2 to use custom calico docker image?

**Comment by briandowns** [comment] 2020-09-01 15:55
There's currently no way to do so. What version rke2 are you running? If not the latest, please try the latest release.

**Comment by asm76** [comment] 2020-09-01 16:41
I'm trying to add bpf object files into calico docker image and i need a way to check that it works.

**Comment by cjellick** [comment] 2020-09-09 15:41
We minimally need to investigate this before ga

**Comment by dweomer** [comment] 2020-09-09 22:30
I am unable to reproduce high CPU usage with beta17:

```shell
# recipe to create vm using multipass
multipass launch -c 1 -d 20G -m 2G --name primary focal
```

`curl -fsSL https://raw.githubusercontent.com/rancher/rke2/master/install.sh | sudo RKE2_KUBECONFIG_MODE=0644 sh`:
```
[INFO]  finding release for channel 
[INFO]  using v1.18.4-beta17+rke2 as release
[INFO]  downloading checksums at https://github.com/rancher/rke2/releases/download/v1.18.4-beta17+rke2/sha256sum-amd64.txt
[INFO]  downloading installer at https://github.com/rancher/rke2/releases/download/v1.18.4-beta17+rke2/rke2-installer.linux-amd64.run
[INFO]  verifying installer
Creating directory /usr/local
Verifying archive integrity...  100%   SHA256 checksums are OK.  100%   MD5 checksums are OK. All good.
Uncompressing rke2 v1.18.4-beta17+rke2  100%  
Created symlink /etc/systemd/system/multi-user.target.wants/rke2.service → /usr/local/lib/systemd/system/rke2.service.
```

```
# setup kubectl
export PATH=/var/lib/rancher/rke2/bin:$PATH KUBECONFIG=/etc/rancher/rke2/rke2.yaml

# wait about 30 seconds
kubectl get node,pod -A -o wide

NAME           STATUS   ROLES         AGE    VERSION               INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
node/primary   Ready    etcd,master   111s   v1.18.4-beta17+rke2   10.210.8.109   <none>        Ubuntu 20.04.1 LTS   5.4.0-47-generic   containerd://1.3.6-k3s2

NAMESPACE     NAME                                                      READY   STATUS      RESTARTS   AGE    IP             NODE      NOMINATED NODE   READINESS GATES
kube-system   pod/etcd-primary                                          1/1     Running     0          59s    10.210.8.109   primary   <none>           <none>
kube-system   pod/helm-install-rke2-canal-8lntb                         0/1     Completed   0          97s    10.210.8.109   primary   <none>           <none>
kube-system   pod/helm-install-rke2-coredns-ph692                       0/1     Completed   0          97s    10.210.8.109   primary   <none>           <none>
kube-system   pod/helm-install-rke2-ingress-nginx-k77gl                 0/1     Completed   0          97s    10.42.0.4      primary   <none>           <none>
kube-system   pod/helm-install-rke2-kube-proxy-h4p8f                    0/1     Completed   0          97s    10.210.8.109   primary   <none>           <none>
kube-system   pod/helm-install-rke2-metrics-server-h8ggk                0/1     Completed   0          97s    10.42.0.3      primary   <none>           <none>
kube-system   pod/kube-apiserver-primary                                1/1     Running     0          52s    10.210.8.109   primary   <none>           <none>
kube-system   pod/kube-controller-manager-primary                       1/1     Running     0          110s   10.210.8.109   primary   <none>           <none>
kube-system   pod/kube-proxy-l5vnn                                      1/1     Running     0          80s    10.210.8.109   primary   <none>           <none>
kube-system   pod/kube-scheduler-primary                                1/1     Running     0          111s   10.210.8.109   primary   <none>           <none>
kube-system   pod/rke2-canal-vcx2w                                      2/2     Running     0          79s    10.210.8.109   primary   <none>           <none>
kube-system   pod/rke2-coredns-rke2-coredns-7979fc655-jbsn7             1/1     Running     0          79s    10.42.0.2      primary   <none>           <none>
kube-system   pod/rke2-ingress-nginx-controller-d78b898d5-zkl78         1/1     Running     0          45s    10.210.8.109   primary   <none>           <none>
kube-system   pod/rke2-ingress-nginx-default-backend-5787b8798f-2svrf   1/1     Running     0          45s    10.42.0.6      primary   <none>           <none>
kube-system   pod/rke2-metrics-server-8c48bb8f7-fvv4t                   1/1     Running     0          47s    10.42.0.5      primary   <none>           <none>
```
`uptime`:
```
 15:29:48 up 13 min,  1 user,  load average: 0.16, 0.31, 0.27
```

**Comment by galal-hussein** [comment] 2020-09-21 19:56
I am unable to reproduce this problem as well with beta20, I can see the cpu usage under 5%:
```
root@ip-172-31-7-252:~# mpstat -P ALL
Linux 5.4.0-1024-aws (ip-172-31-7-252) 	09/21/2020 	_x86_64_	(2 CPU)

07:51:22 PM  CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
07:51:22 PM  all    4.91    0.01    1.75    1.43    0.00    0.16    0.60    0.00    0.00   91.15
07:51:22 PM    0    4.85    0.02    1.73    1.41    0.00    0.18    0.59    0.00    0.00   91.22
07:51:22 PM    1    4.96    0.01    1.77    1.45    0.00    0.13    0.60    0.00    0.00   91.07
```
with 2 CPUs, I am closing the issue but @asm76 please feel free to reopen if you are still getting the same cpu usage with beta20

**Closed by galal-hussein** 2020-09-21 19:56 UTC
Labels: [zube]: Working
