### ISSUE TITLE
Extended provisioning time using airgap tarball method

### ISSUE THREAD

**Issue by chadningle** [rancher/rke2#797] opened 2021-03-17 20:30 UTC
There are currently two methods for airgap.  One is the tarball and another is the private registry.  However, using the tarball method extends provisioning time because the rke2-service is loading the containerd sock at the time of service startup.  This adds to the provisioning time greatly for servers and agents to come online.  

Can we alter the rke2-server service and decouple it from containerd such that we can pre-import these images during the AMI creation phase so that an import is not needed when the rke2-server or agent services get started?

**Comment by brandond** [comment] 2021-03-17 20:34
This is a duplicate of https://github.com/rancher/rke2/issues/773#issuecomment-797370504 - you might check out the discussion over there.

The tl;dr is that it should add no more than ~45 seconds to an already fairly slow cold startup. Are you seeing something else?

**Comment by chadningle** [comment] 2021-03-17 20:45
We would like to stage more images to the AMIs and not just the rke2 ones.  Adding all of our images using 1.19.7 right now adds about 15 min for the import at time of service startup.  It would be great if the containerd service and sock path was available at time of install of rke2-server or rke2-agent so this pre-importing can take place and not at node provisioning time.

**Comment by chadningle** [comment] 2021-03-17 20:46
You'd have the customer run the ctr or crictl commands to do the import themselves OR us the tarball method at node provisioning times.

**Comment by brandond** [comment] 2021-03-17 20:59
I have seen other folks talking about wanting to run an in-cluster registry mirror that they preloaded the bulk of their common images into, so that all you would need to preload to nodes is RKE2 itself plus the registry image. I haven't seen a good demo of this yet though - there are some wrinkles to solve around making the registry itself HA; it would effectively rely on having shared storage (PVCs or NFS) so that the registry could run HA or migrate between nodes. You would also need to solve the problem of getting the images loaded into the registry itself once the cluster is up.

**Comment by chadningle** [comment] 2021-03-17 21:31
Ok.  But even with an in-cluster registry mirror, the node will still need to pull and unpack.  Its the pulling and the unpacking on the node's containerd service that I think would give us that speed when having packer execute it.  Then when another node fires off, the image is already local and is unpacked and ready.

**Comment by Martin-Weiss** [comment] 2021-03-18 06:27
> Ok. But even with an in-cluster registry mirror, the node will still need to pull and unpack. Its the pulling and the unpacking on the node's containerd service that I think would give us that speed when having packer execute it. Then when another node fires off, the image is already local and is unpacked and ready.

Trying to understand this a bit better..

- Are you building single node clusters or bigger ones? 
- What is there reason to preload the images instead of pulling them from a private registry when containers start?
- How big are your images?

**Comment by chadningle** [comment] 2021-03-24 15:55
I think this one should be closed. 

Summary:  RKE2 has no plans to have containerd running as a service upon install of rke2 and will leave it as is.  To improve pod provisioning performance, we can implement a custom pre-warming solution for our clusters AND use a local private registry so pulls are fast.

**Comment by chadningle** [comment] 2021-03-24 15:55
Closing.

**Closed** 2021-03-24 15:55 UTC
