### ISSUE TITLE
Error from server: error dialing backend: dial tcp: lookup

### ISSUE THREAD

**Issue by grk-pancham** [rancher/rke2#716] opened 2021-02-20 22:33 UTC
We are getting dns lookup failures in all kube system logs (namely coredns, api server) with version RKE Government v1.19.7+rke2r1. 
the kube system pods are unable to lookup host from the upstream dns host.

Error:
Error from server: error dialing backend. dial tcp: lookup <hostname> on <dns host>:53: no such host

**Comment by brandond** [comment] 2021-02-22 22:42
Duplicate of #662

**Closed by brandond** 2021-02-22 22:42 UTC
